#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# Optional dependencies for r
#     tk: tcl/tk interface
#     texlive-bin: latex sty files
#     gcc-fortran: needed to compile some CRAN packages
#     openblas: faster linear algebra
#
# Note that Arch is currently overwriting PS1 for root.
# This is due to configuration in '/etc/profile'.
# """

name_fancy="Arch base system"

_koopa_install_start "$name_fancy"

sudo pacman -Syyu --noconfirm

sudo pacman-db-upgrade

packages=(
    autoconf
    awk
    bash
    fish
    gcc
    gettext
    git
    grep
    libevent
    libffi
    make
    man
    parallel
    r
    sudo
    tcl
    texlive-core
    tree
    wget
    which
    zsh
)
sudo pacman -S --noconfirm "${packages[@]}"

# Arch symlinks '/usr/local/share/man' to '/usr/local/man' by default, which
# is non-standard and can cause cellar link script to break.
if [[ -L /usr/local/share/man ]]
then
    sudo rm -v /usr/local/share/man
fi

_koopa_install_success "$name_fancy"
