#!/usr/bin/env zsh

# Koopa ZSH prompt.
# Updated 2019-10-23.

# Modified, lighter version of Pure, by Sindre Sorhus.
# https://github.com/sindresorhus/pure

# Debugging:
# > typeset _koopa_prompt_state

# Prompt:
# - %* : time
# - %F : color dict
# - %M : machine (host) name (full)
# - %f : reset color
# - %m : machine (host) name (up to first '.')
# - %n : user name
# - %~ : current path
# - %(?..) : prompt conditional - %(condition.true.false)

_koopa_prompt_precmd() {
    if [[ -n "${ZSH_THEME:-}" ]]
    then
        _koopa_warning "Oh My Zsh theme is enabled."
        unset ZSH_THEME
    fi
}

_koopa_prompt_setup() {
    add-zsh-hook precmd _koopa_prompt_precmd
    PROMPT="$(_koopa_prompt)"
}

_koopa_prompt_setup "$@"
