#!/usr/bin/env zsh

# """
# Koopa ZSH prompt.
# @note Updated 2020-07-07.
#
# Modified, lighter version of Pure, by Sindre Sorhus.
# https://github.com/sindresorhus/pure
#
# Prompt:
# - %* : time
# - %F : color dict
# - %M : machine (host) name (full)
# - %f : reset color
# - %m : machine (host) name (up to first '.')
# - %n : user name
# - %~ : current path
# - %(?..) : prompt conditional - %(condition.true.false)
# """

koopa::prompt_setup() {
    PROMPT="$(koopa::prompt)"
}

koopa::prompt_setup "$@"
