resources:
  default:
    # Bump up the default from 3G.
    memory: 6G
    # Use n-2 cores.
    cores: 30
    jvm_opts: ["-Xms750m", "-Xmx3500m"]
  gatk:
    jvm_opts: ["-Xms500m", "-Xmx3500m"]
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
  qualimap:
    memory: 4g
  express:
    memory: 8g
  dexseq:
    memory: 10g
  hisat2:
    memory: 50g
  macs2:
    memory: 8g
  seqcluster:
    memory: 8g
  tmp:
    dir: /mnt/resource
galaxy_config: universe_wsgi.ini
