language: shell

branches:
  only:
    - master

# > before_script:
# >   - curl -L "https://github.com/kward/shunit2/archive/v2.1.7.tar.gz" | tar xz
# >   - export PATH="shunit2-2.1.7:${PATH}"

jobs:
  include:
    - stage: test
      name: "linux"
      os: linux
      addons:
        apt:
          packages:
            - r-base
            - shellcheck
            - shunit2
            - zsh
      script:
        - bash -c 'set -x; test=1 . ./activate'
        - zsh  -c 'set -x; test=1 . ./activate'
        - bash -c './tests/travis.sh'
    - stage: test
      name: "macos"
      os: osx
      addons:
        homebrew:
          packages:
            - bash
            - r
            - shellcheck
            - shunit2
            - zsh
      script:
        - bash -c 'set -x; test=1 . ./activate'
        - zsh  -c 'set -x; test=1 . ./activate'
        - bash -c './tests/travis.sh'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
