language: shell

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      name: "linux"
      addons:
        apt:
          packages:
            - ksh
            - zsh
      script:
        - bash -c 'set -x; test=1 . ./activate'
        - zsh  -c 'set -x; test=1 . ./activate'
        - bash -c './system/checks/linter.sh'
        - bash -c './system/checks/help.sh'
    - stage: test
      name: "macos"
      os: osx
      script:
        - bash -c 'set -x; test=1 . ./activate'
        - zsh  -c 'set -x; test=1 . ./activate'
        - bash -c './system/checks/linter.sh'
        - bash -c './system/checks/help.sh'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
