# Note that Travis CI has now integrated ShellCheck by default.
# See also:
# - https://github.com/koalaman/shellcheck#travis-ci
# - https://github.com/koalaman/shellcheck/wiki/TravisCI

# Install shunit2 to for shell unit tests.
# See also:
# - https://github.com/kward/shunit2
# - https://travis-ci.org/soulseekah/test-shunit2-travis
#
# before_script:
#   - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx

language: shell

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      name: "linux"
      addons:
        apt:
          packages:
            - ksh
            - zsh
      script:
        - bash -c 'set -x; test=1 . ./activate'
        - bash -c './bin/shellcheck-recursive'
        - bash -c './system/linter/fixme-comments.sh'
        - zsh  -c 'set -x; test=1 . ./activate'
        - ksh  -c 'set -x; test=1 . ./activate'
    - stage: test
      name: "macos"
      os: osx
      script:
        - bash -c 'set -x; test=1 . ./activate'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
