language: shell

branches:
  only:
    - master

before_script:
    - curl -L "https://github.com/kward/shunit2/archive/v2.1.7.tar.gz" | tar xz

jobs:
  include:
    - stage: test
      name: "linux"
      os: linux
      addons:
        apt:
          packages:
            - ksh
            - zsh
      script:
        - bash -c 'set -x; test=1 . ./activate'
        - zsh  -c 'set -x; test=1 . ./activate'
        - bash -c './tests/travis.sh'
    - stage: test
      name: "macos"
      os: osx
      script:
        - bash -c 'set -x; test=1 . ./activate'
        - zsh  -c 'set -x; test=1 . ./activate'
        - bash -c './tests/travis.sh'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
