os: linux
language: shell

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      name: "debian"
      services: docker
      script: image="acidgenomics/debian" ./tests/docker
    - stage: test
      name: "fedora"
      services: docker
      script: image="acidgenomics/fedora" ./tests/docker
  fast_finish: true

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
