#!/usr/bin/env python3
"""Inject descriptions into etc/koopa/app.json."""

from __future__ import annotations

import json
from pathlib import Path

DESCRIPTIONS: dict[str, str] = {
    # a
    "ack": "grep-like text finder optimized for source code",
    "agat": "toolkit for working with GFF/GTF annotation files",
    "air": "R code formatter",
    "anaconda": "full Anaconda Python distribution",
    "apache-airflow": "workflow orchestration platform",
    "apache-arrow": "cross-language columnar in-memory data format",
    "apache-spark": "distributed large-scale data processing engine",
    "apptainer": "container runtime for HPC environments",
    "apr": "Apache Portable Runtime library",
    "apr-util": "Apache Portable Runtime utility library",
    "aria2": "lightweight multi-protocol download utility",
    "armadillo": "C++ linear algebra library",
    "asdf": "multi-language runtime version manager",
    "aspell": "spell checker",
    "aspera-connect": "high-speed file transfer client by IBM",
    "attr": "utilities for managing extended filesystem attributes",
    "autoconf": "generates configure scripts for build systems",
    "autodock": "molecular docking software",
    "autodock-adfr": "AutoDock Flexible Receptor docking suite",
    "autodock-vina": "fast molecular docking software",
    "autoflake": "removes unused imports from Python files",
    "automake": "generates Makefiles from simple descriptions",
    "aws-azure-login": "authenticates to AWS via Azure Active Directory",
    "aws-cli": "official Amazon Web Services command-line interface",
    "aws-mountpoint-s3": "mount S3 buckets as local filesystems",
    "axel": "lightweight command-line download accelerator",
    "azure-cli": "official Microsoft Azure command-line interface",
    # b
    "bamtools": "C++ API and toolkit for working with BAM files",
    "bandit": "security linting tool for Python code",
    "bandwhich": "terminal bandwidth utilization tool",
    "bash": "GNU Bourne Again Shell",
    "bash-completion": "programmable completion functions for bash",
    "bash-language-server": "LSP server for bash scripts",
    "bashcov": "code coverage tool for bash scripts",
    "bat": "cat clone with syntax highlighting and Git integration",
    "bc": "arbitrary-precision numeric processing language",
    "bcbio-nextgen": "validated, scalable variant and RNA-seq analysis pipeline",
    "bcl2fastq": "Illumina BCL to FASTQ conversion software",
    "bedtools": "swiss-army knife for genome interval arithmetic",
    "bfg": "removes large files and secrets from Git history",
    "binutils": "GNU binary file utilities (ld, as, objdump, etc.)",
    "bioawk": "awk extended with bioinformatics-aware field parsing",
    "bioconda-utils": "helper tools for building Bioconda packages",
    "bison": "GNU parser generator (YACC-compatible)",
    "black": "opinionated Python code formatter",
    "blast": "NCBI sequence similarity search tool",
    "boost": "peer-reviewed portable C++ libraries",
    "bottom": "cross-platform graphical process and system monitor",
    "bowtie2": "fast short-read aligner for long reference sequences",
    "bpytop": "resource monitor with a stylish terminal UI",
    "broot": "interactive tree view and fuzzy file finder",
    "brotli": "lossless compression algorithm and library by Google",
    "btop": "resource monitor showing CPU, memory, disks, and network",
    "bumpver": "version bumping tool for Python projects",
    "bustools": "utilities for processing BUS format single-cell data",
    "byobu": "text-based window manager and terminal multiplexer",
    "bzip2": "high-quality block-sorting file compressor",
    # c
    "c-ares": "asynchronous DNS resolver library",
    "ca-certificates": "Mozilla CA certificate bundle",
    "cairo": "2D graphics library with multiple output targets",
    "cellranger": "10x Genomics single-cell RNA-seq pipeline",
    "cereal": "C++11 header-only serialization library",
    "cheat": "interactive cheatsheet tool for the command line",
    "chemacs": "Emacs profile switcher",
    "chezmoi": "dotfile manager with templating and secrets support",
    "claude-code": "Anthropic Claude AI coding assistant CLI",
    "cli11": "command-line argument parser library for C++11",
    "cloudbiolinux": "automated bioinformatics environment setup",
    "cmake": "cross-platform build system generator",
    "colorls": "colorized ls replacement written in Ruby",
    "commitizen": "conventional commit message tooling for Python projects",
    "conda": "cross-platform package and environment manager",
    "convmv": "converts filenames between character encodings",
    "coreutils": "GNU file, text, and shell utilities",
    "cpufetch": "simple CPU microarchitecture information tool",
    "csvkit": "suite of command-line tools for working with CSV files",
    "csvtk": "cross-platform CSV/TSV toolkit",
    "curl": "command-line tool for transferring data with URLs",
    # d
    "dash": "POSIX-compliant shell, faster and lighter than bash",
    "databricks-cli": "command-line interface for Databricks",
    "deeptools": "tools for analysis of deep-sequencing data",
    "delta": "syntax-highlighting pager for git and diff output",
    "diff-so-fancy": "human-readable diff output for git",
    "difftastic": "structural diff tool that understands syntax",
    "direnv": "loads and unloads environment variables per directory",
    "docker-credential-helpers": "credential helpers for Docker",
    "doom-emacs": "opinionated Emacs configuration framework",
    "dotfiles": "acidgenomics personal dotfiles managed with chezmoi",
    "du-dust": "more intuitive disk usage tool (du + rust = dust)",
    "duckdb": "in-process analytical SQL database",
    # e
    "ed": "classic line-oriented text editor",
    "editorconfig": "maintain consistent coding styles across editors",
    "elfutils": "utilities for ELF files and DWARF debug information",
    "elvish": "expressive shell with structured data pipelines",
    "emacs": "extensible, customizable GNU text editor",
    "ensembl-perl-api": "Perl API for Ensembl genomics databases",
    "entrez-direct": "NCBI E-utilities command-line tools",
    "exa": "modern ls replacement with color and Git support (deprecated; use eza)",
    "exiftool": "read and write metadata in image and media files",
    "expat": "fast stream-oriented XML parser library",
    "eza": "modern ls replacement with color, icons, and Git support",
    # f
    "fastqc": "quality control analysis for high-throughput sequencing data",
    "fd-find": "simple, fast alternative to the find command",
    "ffmpeg": "record, convert, and stream audio and video",
    "ffq": "retrieve metadata from sequencing data repositories",
    "fgbio": "tools for working with genomic and sequencing data",
    "findutils": "GNU find, locate, updatedb, and xargs utilities",
    "fish": "friendly interactive shell",
    "flac": "free lossless audio codec",
    "flake8": "Python style guide enforcement and linting tool",
    "flex": "fast lexical analyzer generator",
    "fltk": "cross-platform C++ GUI toolkit",
    "fmt": "modern C++ formatting library",
    "fontconfig": "font configuration and customization library",
    "fq": "bioformat-aware FASTQ file toolkit",
    "fqtk": "full-featured FASTQ toolkit for genomics",
    "freetype": "font rendering library",
    "fribidi": "implementation of the Unicode Bidirectional Algorithm",
    "fzf": "command-line fuzzy finder",
    # g
    "gatk": "GATK variant discovery toolkit from Broad Institute",
    "gawk": "GNU implementation of the awk programming language",
    "gcc": "GNU Compiler Collection (C, C++, Fortran, and more)",
    "gdal": "geospatial data abstraction library",
    "gdbm": "GNU dbm key-value database library",
    "gdc-client": "NCI Genomic Data Commons data transfer tool",
    "gemini-cli": "Google Gemini AI assistant CLI",
    "genomepy": "download and manage genomic sequences and annotation",
    "gentropy": "open-source genetics evidence platform",
    "geos": "geometry engine for geographic information systems",
    "gettext": "GNU internationalization and localization tools",
    "gffutils": "Python interface for working with GFF and GTF files",
    "gget": "efficient querying of genomic databases",
    "gh": "official GitHub command-line interface",
    "ghostscript": "PostScript and PDF interpreter",
    "git": "distributed version control system",
    "git-filter-repo": "fast and flexible rewriting of Git history",
    "git-lfs": "Git extension for versioning large files",
    "gitui": "blazing fast terminal UI for Git",
    "glances": "cross-platform system monitoring tool",
    "glib": "low-level core library for GNOME",
    "gmp": "GNU multiple precision arithmetic library",
    "gnupg": "GNU Privacy Guard for encryption and signing",
    "gnutls": "secure communications library implementing TLS and SSL",
    "go": "Go programming language toolchain",
    "google-cloud-sdk": "command-line tools for Google Cloud Platform",
    "googletest": "Google C++ testing and mocking framework",
    "gperf": "perfect hash function generator",
    "graphviz": "graph visualization software",
    "grep": "GNU pattern-matching text search utility",
    "grex": "generate regular expressions from example test cases",
    "groff": "GNU document formatting system",
    "gseapy": "gene set enrichment analysis in Python",
    "gsl": "GNU Scientific Library for numerical computation",
    "gtop": "graphical process viewer in the terminal",
    "gum": "tool for building charming interactive shell scripts",
    "gzip": "GNU file compression and decompression utility",
    # h
    "hadolint": "Dockerfile linter that enforces best practices",
    "harfbuzz": "text shaping engine",
    "haskell-cabal": "Haskell package and build manager",
    "haskell-ghcup": "Haskell toolchain installer",
    "haskell-stack": "cross-platform Haskell build tool",
    "hdf5": "library for the HDF5 hierarchical data format",
    "hexyl": "command-line hex viewer with color output",
    "hisat2": "graph-based aligner for spliced RNA-seq reads",
    "htop": "interactive process viewer",
    "htseq": "Python framework for processing NGS data",
    "htslib": "C library for high-throughput sequencing data formats",
    "httpie": "user-friendly command-line HTTP client",
    "httpx": "fully featured HTTP client library for Python",
    "huggingface-hub": "client library for the Hugging Face Hub",
    "hugo": "fast static site generator written in Go",
    "hyperfine": "command-line benchmarking tool",
    # i
    "icu4c": "International Components for Unicode C and C++ libraries",
    "illumina-ica-cli": "command-line interface for Illumina Connected Analytics",
    "imagemagick": "create, edit, compose, and convert images",
    "ipython": "enhanced interactive Python shell",
    "isl": "integer set library for polyhedral compilation",
    "isort": "sort Python imports automatically",
    # j
    "jemalloc": "general-purpose malloc implementation with profiling support",
    "jfrog-cli": "JFrog platform command-line interface",
    "jless": "command-line JSON viewer and pager",
    "jpeg": "IJG JPEG image compression library",
    "jq": "lightweight command-line JSON processor",
    "julia": "high-performance dynamic programming language",
    "jupyterlab": "web-based interactive development environment for notebooks",
    # k
    "k9s": "terminal UI for managing Kubernetes clusters",
    "kallisto": "fast RNA-seq quantification via pseudoalignment",
    "krb5": "MIT Kerberos 5 authentication system",
    "ksh93": "KornShell 93 POSIX-compatible shell",
    # l
    "lame": "LAME MP3 encoder",
    "lapack": "linear algebra package for numerical computation",
    "latch": "bioinformatics platform SDK and CLI",
    "ldc": "LLVM-based D programming language compiler",
    "ldns": "library for DNS programming",
    "less": "terminal pager with backward navigation",
    "lesspipe": "preprocessor for less to display non-text files",
    "libaec": "adaptive entropy coding library",
    "libarchive": "library for reading and writing archive files",
    "libassuan": "IPC library used by GnuPG",
    "libcbor": "C implementation of the CBOR serialization format",
    "libconfig": "C and C++ library for processing configuration files",
    "libde265": "open H.265/HEVC video codec implementation",
    "libdeflate": "fast DEFLATE, zlib, and gzip compression library",
    "libedit": "command-line editing library",
    "libev": "high-performance event loop library",
    "libevent": "asynchronous event notification library",
    "libffi": "foreign function interface library",
    "libfido2": "library for FIDO2 and WebAuthn authentication",
    "libgcrypt": "cryptographic library used by GnuPG",
    "libgeotiff": "library for georeferenced TIFF files",
    "libgit2": "portable C library implementing Git core",
    "libgpg-error": "common error codes library for GnuPG components",
    "libheif": "HEIF and HEVC image format library",
    "libiconv": "character set conversion library",
    "libidn": "internationalized domain names library",
    "libjpeg-turbo": "SIMD-accelerated JPEG encoding and decoding library",
    "libksba": "library for X.509 and CMS structures used by GnuPG",
    "liblinear": "library for large linear classification",
    "libluv": "async I/O bindings for Lua used by Neovim",
    "libpcap": "portable C library for network traffic capture",
    "libpipeline": "pipeline manipulation library",
    "libpng": "official PNG reference library",
    "libsolv": "dependency solver library",
    "libssh2": "C library implementing the SSH2 protocol",
    "libtasn1": "ASN.1 parsing library",
    "libtermkey": "library for processing keyboard input in terminals",
    "libtiff": "library for reading and writing TIFF files",
    "libtool": "generic shared library support scripts",
    "libunistring": "Unicode string processing library",
    "libuv": "multi-platform async I/O library used by Node.js",
    "libvterm": "VT220/xterm/256-color terminal emulator library",
    "libxcrypt": "extended crypt library for password hashing",
    "libxml2": "XML parsing library",
    "libxslt": "XSLT transformation library",
    "libyaml": "YAML parser and emitter in C",
    "libzip": "library for reading, creating, and modifying ZIP files",
    "llama": "large language model inference engine",
    "llvm": "LLVM compiler infrastructure",
    "lmod": "Lua-based environment modules system",
    "lsd": "colorized ls replacement with icons",
    "lua": "lightweight embeddable scripting language",
    "luajit": "just-in-time compiler for Lua",
    "luarocks": "package manager for Lua modules",
    "luigi": "Python workflow manager by Spotify",
    "lz4": "extremely fast lossless compression algorithm",
    "lzip": "lossless data compressor based on LZMA",
    "lzo": "fast lossless data compression library",
    # m
    "m4": "GNU macro processor",
    "make": "GNU build automation tool",
    "mamba": "fast conda-compatible package manager",
    "man-db": "utilities for reading Unix manual pages",
    "marimo": "reactive Python notebook environment",
    "markdownlint-cli": "linter for Markdown files",
    "mcfly": "smart shell history search with neural networks",
    "mdcat": "cat clone for Markdown with terminal rendering",
    "meson": "fast, user-friendly build system",
    "miller": "like awk/sed/cut/join for name-indexed data formats",
    "mimalloc": "compact general-purpose memory allocator by Microsoft",
    "minimap2": "versatile pairwise sequence aligner",
    "misopy": "mixture-of-isoforms model for alternative splicing analysis",
    "mold": "high-speed linker for ELF binaries",
    "mosaicml-cli": "MosaicML training platform CLI",
    "mpc": "C library for arbitrary-precision complex arithmetic",
    "mpdecimal": "C library for correct decimal floating point",
    "mpfr": "C library for multiple-precision floating-point arithmetic",
    "msgpack": "efficient binary serialization format library",
    "multiqc": "aggregate QC reports from bioinformatics tools",
    "mutagen": "Python library for reading and writing audio metadata",
    "mypy": "static type checker for Python",
    # n
    "nano": "simple, user-friendly terminal text editor",
    "nanopolish": "signal-level analysis of Oxford Nanopore sequencing data",
    "ncbi-sra-tools": "tools for the NCBI Sequence Read Archive",
    "ncbi-vdb": "database engine for the NCBI Sequence Read Archive",
    "ncurses": "terminal-independent text UI library",
    "neofetch": "fast system information display tool",
    "neovim": "hyperextensible Vim-based text editor",
    "nettle": "low-level cryptographic library",
    "nextflow": "scalable and reproducible scientific workflow framework",
    "nghttp2": "HTTP/2 C library",
    "nim": "statically typed compiled systems programming language",
    "ninja": "small, fast build system",
    "nlohmann-json": "modern JSON library for C++",
    "nmap": "network exploration and security auditing tool",
    "node": "JavaScript runtime built on V8 (Node.js)",
    "npth": "New GNU Portable Threads library",
    "nushell": "modern shell using structured data pipelines",
    # o
    "oniguruma": "regular expressions library",
    "ont-bonito": "Oxford Nanopore basecaller",
    "ont-dorado": "Oxford Nanopore high-accuracy basecaller",
    "ont-guppy": "Oxford Nanopore production basecaller",
    "ont-vbz-compression": "VBZ compression plugin for Oxford Nanopore data",
    "openbb": "open-source investment research platform",
    "openblas": "optimized BLAS (Basic Linear Algebra Subprograms) library",
    "openjpeg": "open-source JPEG 2000 codec",
    "openldap": "open-source LDAP directory service",
    "openssh": "OpenBSD SSH connectivity tools",
    "openssl": "toolkit for TLS and general-purpose cryptography (v1)",
    "openssl3": "toolkit for TLS and general-purpose cryptography (v3)",
    "oracle-instant-client": "Oracle Database client libraries",
    # p
    "p7zip": "port of 7-zip for POSIX systems",
    "pandoc": "universal document format converter",
    "parallel": "GNU shell tool for executing jobs in parallel",
    "password-store": "simple password manager using GPG and Git",
    "patch": "GNU patch for applying unified diff files",
    "pbzip2": "parallel implementation of bzip2",
    "pcre": "Perl-compatible regular expressions library (v1)",
    "pcre2": "Perl-compatible regular expressions library (v2)",
    "perl": "Practical Extraction and Report Language",
    "picard": "Java tools for high-throughput sequencing data",
    "pigz": "parallel gzip for fast multi-threaded compression",
    "pinentry": "collection of dialog programs for GnuPG passphrase entry",
    "pipx": "install and run Python CLI apps in isolated environments",
    "pixman": "pixel manipulation library",
    "pkg-config": "helper tool for querying installed library info",
    "pkgconf": "drop-in replacement for pkg-config",
    "poetry": "Python dependency management and packaging tool",
    "postgresql": "powerful open-source relational database",
    "powershell": "cross-platform task automation shell by Microsoft",
    "prelude-emacs": "community-maintained Emacs configuration",
    "prettier": "opinionated code formatter for JS, CSS, HTML, and more",
    "procs": "modern replacement for ps with color output",
    "proj": "cartographic projections and coordinate transformations library",
    "pup": "command-line HTML parsing tool",
    "py-spy": "sampling profiler for Python programs",
    "pybind11": "C++11 header-only bindings between C++ and Python",
    "pycodestyle": "Python style guide checker (PEP 8)",
    "pyenv": "manage multiple Python versions",
    "pyflakes": "passive checker for Python programs",
    "pygments": "syntax highlighter for many programming languages",
    "pylint": "source code analyzer and linter for Python",
    "pymol": "molecular visualization system",
    "pyrefly": "fast Python type checker",
    "pyright": "static type checker for Python by Microsoft",
    "pytaglib": "Python bindings for the taglib audio metadata library",
    "pytest": "feature-rich Python testing framework",
    "python": "generic Python shim (resolved at runtime)",
    "python3.10": "Python 3.10 interpreter",
    "python3.11": "Python 3.11 interpreter",
    "python3.12": "Python 3.12 interpreter",
    "python3.13": "Python 3.13 interpreter",
    "python3.14": "Python 3.14 interpreter",
    # q
    "quarto": "scientific and technical publishing system",
    # r
    "r": "R statistical computing language and environment",
    "r-devel": "R development version (SVN build)",
    "r-gfortran": "gfortran toolchain for building R packages on macOS",
    "r-xcode-openmp": "OpenMP support for R packages on macOS",
    "radian": "modern R console with syntax highlighting and completion",
    "ranger-fm": "vim-inspired terminal file manager",
    "rbenv": "Ruby version manager",
    "rclone": "sync files to and from cloud storage providers",
    "readline": "library for editing command-line input",
    "rename": "Perl-based file renaming tool",
    "reproc": "cross-platform child process library",
    "ripgrep": "recursively search directories with regex patterns",
    "ripgrep-all": "ripgrep with support for searching many file formats",
    "rmate": "TextMate remote file editing tool",
    "rmats": "rMATS splicing analysis from RNA-seq data",
    "ronn": "builds man pages from Markdown",
    "ronn-ng": "actively maintained fork of ronn",
    "rsem": "accurate quantification of gene and isoform expression",
    "rstudio-server": "web-based RStudio IDE server",
    "rsync": "fast, versatile remote and local file-copying tool",
    "ruby": "dynamic, open-source programming language",
    "ruff": "extremely fast Python linter and formatter",
    "ruff-lsp": "LSP server for ruff",
    "rust": "systems programming language focused on safety and speed",
    # s
    "s5cmd": "very fast S3 and object storage CLI tool",
    "salmon": "fast, accurate RNA-seq quantification tool",
    "sambamba": "fast parallel tools for working with SAM/BAM files",
    "samtools": "tools for manipulating alignments in SAM and BAM format",
    "scalene": "high-performance CPU, GPU, and memory profiler for Python",
    "scanpy": "single-cell analysis in Python",
    "scons": "Python-based software construction tool",
    "screen": "terminal multiplexer with detachable sessions",
    "sd": "intuitive find and replace CLI tool",
    "sed": "GNU stream editor for filtering and transforming text",
    "seqkit": "cross-platform and ultrafast FASTQ/FASTA toolkit",
    "serf": "high-performance C-based HTTP client library",
    "shellcheck": "static analysis tool for shell scripts",
    "shiny-server": "server for deploying R Shiny web applications",
    "shunit2": "xUnit-based unit test framework for shell scripts",
    "shyaml": "YAML parsing tool for the command line",
    "simdjson": "JSON parser using SIMD instructions for high throughput",
    "snakefmt": "formatter for Snakemake workflow files",
    "snakemake": "scalable bioinformatics workflow manager",
    "sox": "Swiss army knife of audio manipulation tools",
    "spacemacs": "Emacs configuration centered around evil-mode",
    "spacevim": "modular Vim and Neovim configuration",
    "spdlog": "fast C++ logging library",
    "sphinx": "Python documentation generator",
    "sqlfluff": "SQL linter and auto-formatter",
    "sqlite": "self-contained, serverless SQL database engine",
    "staden-io-lib": "library for reading and writing sequencing data formats",
    "star": "ultrafast universal RNA-seq aligner",
    "star-fusion": "detects gene fusions using STAR alignments",
    "starship": "fast, customizable cross-shell prompt",
    "stow": "symlink farm manager for managing dotfiles",
    "streamlit": "build and share data web apps in Python",
    "subread": "toolkit including featureCounts for RNA-seq counting",
    "subversion": "centralized version control system",
    "swig": "interface compiler connecting C/C++ to scripting languages",
    # t
    "taglib": "library for reading and editing audio file metadata",
    "tar": "GNU archiving utility",
    "tbb": "Intel oneAPI Threading Building Blocks for parallel C++",
    "tcl-tk": "Tcl/Tk scripting language and GUI toolkit",
    "tealdeer": "fast tldr client for concise command examples",
    "temurin": "Eclipse Temurin OpenJDK distribution",
    "termcolor": "Python library for ANSI color output",
    "texinfo": "GNU documentation system",
    "tl-expected": "C++ implementation of std::expected",
    "tmux": "terminal multiplexer with persistent sessions",
    "tokei": "count lines of code quickly",
    "tqdm": "fast, extensible progress bar for Python",
    "tree": "display directory contents in a tree structure",
    "tree-sitter": "incremental parsing library for syntax trees",
    "tryceratops": "Python anti-pattern linter",
    "tuc": "cut text by fields, bytes, or characters",
    "ty": "extremely fast Python type checker",
    # u
    "udunits": "library and utilities for units of physical quantities",
    "umis": "tools for processing reads with UMI barcodes",
    "unibilium": "terminfo parser and utility library",
    "units": "GNU units conversion and calculation utility",
    "unzip": "extraction utility for ZIP archives",
    "utf8proc": "C library for Unicode and UTF-8 processing",
    "uv": "extremely fast Python package and project manager",
    # v
    "vim": "highly configurable text editor",
    "visidata": "terminal spreadsheet multitool for tabular data",
    "vulture": "find dead Python code",
    # w
    "walk": "terminal file manager for navigating directories",
    "wget": "non-interactive command-line file downloader",
    "wget2": "successor to wget with HTTP/2 support",
    "which": "shows the full path of shell commands",
    "woff2": "encode and decode WOFF2 web font format",
    # x
    "xorg-libice": "Inter-Client Exchange library",
    "xorg-libpthread-stubs": "pthread stubs used by X.org build system",
    "xorg-libsm": "X Session Management library",
    "xorg-libx11": "core X11 protocol client library",
    "xorg-libxau": "X authority file management library",
    "xorg-libxcb": "X protocol C-language binding library",
    "xorg-libxdmcp": "X Display Manager Control Protocol library",
    "xorg-libxext": "X11 miscellaneous extension library",
    "xorg-libxrandr": "X resize and rotate extension library",
    "xorg-libxrender": "X render extension library",
    "xorg-libxt": "X toolkit intrinsics library",
    "xorg-xcb-proto": "XCB protocol descriptions",
    "xorg-xorgproto": "X.Org X11 protocol headers",
    "xorg-xtrans": "X transport library",
    "xsra": "extended SRA download and processing tools",
    "xsv": "fast CSV command-line toolkit",
    "xxhash": "extremely fast non-cryptographic hash algorithm library",
    "xz": "general-purpose lossless data compressor using LZMA",
    # y
    "yaml-cpp": "YAML parser and emitter for C++",
    "yamllint": "linter for YAML files",
    "yapf": "Python code formatter by Google",
    "yq": "YAML, JSON, and XML command-line processor",
    "yt-dlp": "download videos from YouTube and many other sites",
    # z
    "zellij": "terminal workspace with layouts and plugins",
    "zenith": "graphical terminal process monitor",
    "zip": "create and manage ZIP archives",
    "zlib": "lossless data compression library",
    "zopfli": "high-quality but slow zlib/gzip/zip compressor by Google",
    "zoxide": "smarter cd command that learns your habits",
    "zsh": "Z shell, extended Bourne-compatible shell",
    "zstd": "fast lossless compression algorithm by Facebook",
}


def main() -> None:
    """Inject descriptions into app.json."""
    path = Path(__file__).parent / "etc/koopa/app.json"
    with path.open() as f:
        data = json.load(f)

    missing = sorted(k for k in DESCRIPTIONS if k not in data)
    if missing:
        print(f"WARNING: keys in DESCRIPTIONS not found in app.json: {missing}")

    no_desc = sorted(k for k in data if k not in DESCRIPTIONS)
    if no_desc:
        print(f"WARNING: apps without descriptions ({len(no_desc)}): {no_desc}")

    count = 0
    for app, desc in DESCRIPTIONS.items():
        if app in data:
            data[app]["description"] = desc
            count += 1

    with path.open("w") as f:
        json.dump(data, f, indent=2, sort_keys=True)
        f.write("\n")

    print(f"Wrote descriptions for {count} apps to {path}")


if __name__ == "__main__":
    main()
