#!/usr/bin/env bash
set -Eeu -o pipefail

# Install koopa shared for all users.
# Modified 2019-06-17.

koopa_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"



# Install koopa                                                             {{{1
# ==============================================================================

shared=1 . "${koopa_dir}/install"



# Shared profile configuration                                              {{{1
# ==============================================================================

echo "Adding 'koopa.sh' to '/etc/profile.d/'."
sudo -n ln -fs \
    "${koopa_dir}/config/etc/profile.d/koopa.sh" \
    /etc/profile.d/koopa.sh

