#!/usr/bin/env bash

# Install koopa.
# Modified 2019-06-20.

# Set `dev=1` to enable some additional developer configuration tweaks.
# Namely, this currently changes submodule remotes from HTTPS to git.

KOOPA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"

# shellcheck source=/dev/null
source "${KOOPA_DIR}/system/include/functions.sh"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
    cat << EOF
usage: install [-h]

Install koopa.

This script performs the following steps:

  1. Initialize top-level submodules (e.g. dotfiles).
  2. Recurse into dotfiles repo and initialize additional submodules.
  3. Configure profile for current user (default; e.g. '~/.bashrc'), or shared
     profile (use '--shared' flag) via '/etc/profile.d/'.

optional arguments:
  -h, --help
        Show this help message and exit.
  --devel
        Enable developer mode. This changes the repository URLs from HTTPS
        to SSH, for easier code commits.
  --dotfiles
        Automatically generate dot file symlinks.
  --mike
        Install Mike-specific configuration.
        This flag automatically enables '--devel' and '--dotfiles'.
  --shared
        Configure shared installation using '/etc/profile.d'.
        Automatically enabled when installed in '/usr/local' or '/opt'.
EOF
}



# Flags                                                                     {{{1
# ==============================================================================

while (("$#"))
do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        --devel)
            devel=1
            shift 1
            ;;
        --mike)
            mike=1
            shift 1
            ;;
        --dotfiles)
            dotfiles=1
            shift 1
            ;;
        --shared)
            shared=1
            shift 1
            ;;
        --) # End argument parsing.
            shift
            break
            ;;
        --*|-*) # Unsupported flags.
            >&2 printf "Error: Invalid flag %s\n" "$1"
            exit 1
            ;;
    esac
done

[[ "${mike:-0}" -eq 1 ]] && devel=1 && dotfiles=1



# Remove legacy cruft                                                       {{{1
# ==============================================================================

rm -rf "${KOOPA_DIR}/bin/"{host,os,sudo}
rm -rf "${KOOPA_DIR}/"{config,dotfiles,include}



# Shared user configuration                                                 {{{1
# ==============================================================================

# Checking for '/usr/local' installation automatically.
if echo "$KOOPA_DIR" | grep -qE "^/(opt|usr/local)/"
then
    printf "\nShared installation detected at '%s'.\n" "$KOOPA_DIR"
    shared=1
fi

if [[ "${shared:-0}" -eq 1 ]]
then
    _koopa_update_profile
    # > _koopa_update_r_config
fi



# Initialize submodules                                                     {{{1
# ==============================================================================

if [[ "${dotfiles:-0}" -eq 1 ]]
then
    (
        printf "\nInitializing submodules.\n"
        # shellcheck source=/dev/null
        cd "$KOOPA_DIR" || exit 1
        git submodule init
        git submodule update --init --recursive
        git submodule sync --recursive
        # Change remote from HTTPS to git for easier commits.
        if [[ -n "${devel:-}" ]]
        then
            git remote set-url origin git@github.com:acidgenomics/koopa.git
        fi
    )

    (
        printf "\nInitializing dotfiles submodules.\n"
        # shellcheck source=/dev/null
        cd "${KOOPA_DIR}/system/config/dotfiles" || exit 1
        git submodule init
        git submodule update --init --recursive
        git submodule sync --recursive
        # Change remote from HTTPS to git for easier commits.
        if [[ -n "${devel:-}" ]]
        then
            git remote set-url origin git@github.com:mjsteinbaugh/dotfiles.git
        fi
    )
fi



# Activate koopa                                                            {{{1
# ==============================================================================

printf "\nActivating koopa.\n"
# shellcheck source=/dev/null
source "${KOOPA_DIR}/activate"



# Dot files                                                                 {{{1
# ==============================================================================

# Never attempt to configure dotfiles for root.
[[ "$(id -u)" -eq 0 ]] && dotfiles=0

if [[ "${dotfiles:-0}" -eq 1 ]]
then
    printf "\nConfiguring dotfiles.\n"

    # Always create these dotfiles, even on a shared installation.
    # shellcheck source=/dev/null
    source "${KOOPA_DIR}/system/install/dotfiles-shared.sh"

    # Create local config files.
    # shellcheck source=/dev/null
    [[ -z "${shared:-}" ]] &&
        source "${KOOPA_DIR}/system/install/dotfiles-local.sh"

    # Configure Mike-only dotfiles.
    # shellcheck source=/dev/null
    [[ "${mike:-}" -eq 1 ]] &&
        source "${KOOPA_DIR}/system/install/dotfiles-mike.sh"

    # Remove legacy dotfile cruft.
    # shellcheck source=/dev/null
    source "${KOOPA_DIR}/system/uninstall/dotfiles-legacy.sh"
fi
