** TODO We're now hitting this with `git pull` on another machine. I want to make sure we avoid this situation and that it doesn't cause issues with `koopa update`:
/opt/koopa develop 📦 0.18.0 <python 3.12.13: .venv>
$ git pull
remote: Enumerating objects: 213350, done.
remote: Counting objects: 100% (213271/213271), done.
remote: Compressing objects: 100% (74841/74841), done.
remote: Total 211737 (delta 135735), reused 207583 (delta 132832), pack-reused 0 (from 0)
Receiving objects: 100% (211737/211737), 31.52 MiB | 20.90 MiB/s, done.
Resolving deltas: 100% (135735/135735), completed with 862 local objects.
From github.com:acidgenomics/koopa
 + e07667690667...d9dba7e98fc3 develop    -> origin/develop  (forced update)
 + 20c9fbfb81f9...6dd656274d62 main       -> origin/main  (forced update)
Auto-merging .claude/rules/lessons.md
CONFLICT (add/add): Merge conflict in .claude/rules/lessons.md
Auto-merging bin/koopa
CONFLICT (add/add): Merge conflict in bin/koopa
Auto-merging etc/koopa/app.json
CONFLICT (add/add): Merge conflict in etc/koopa/app.json
Auto-merging lang/python/src/koopa/install_info.py
CONFLICT (add/add): Merge conflict in lang/python/src/koopa/install_info.py
Auto-merging uninstall.sh
CONFLICT (add/add): Merge conflict in uninstall.sh
Automatic merge failed; fix conflicts and then commit the result.
