** TODO What are some newly released shell tools that are gaining popularity on Homebrew?
Can we identify any additional useful shell tools that are also newly popular on conda (conda-forge)?
** TODO Conversely, are there any apps currently supported in koopa that are poorly maintained and should be removed? Focus on shell tools and bioinformatics tools. We want to make sure koopa doesn't maintain unnecessary legacy support for poorly maintained tools. Aggressively prune things that aren't maintained. We likely need to enable `deep-research` to perform this review by checking Homebrew, conda-forge, Debian, and other public source repos for software.
** TODO Are there any other modern database technologies we're missing here? We have support for duckdb, parquet, apache-arrow. Do we need to improve support for Apache Spark? Can we add better support for TileDB?
** TODO We need to add install support for Snowflake CLI. Are there other lakehouse providers like Databricks where we need to suport CLI tools here?
** TODO Do we need to install any additional tools to support Google Cloud? Is the Google Cloud SDK the only thing we need?
** TODO Rework our app installer logic for soft dependencies like aws-cli for aws-azure-login. Technically aws-azure-login doesn't require aws to build, but it's basically useless unless we have aws-cli installed. Similar concept for git plugins like git-filter-repo. Some git tools don't actually require git to be installed, but they're useless without git being installed. Can we review our app dependency logic for this situations? Basically I don't want an aws-cli version bump to trigger aws-azure-login reinstall. That doesn't make sense.
** TODO Review that we provide comprehensive support for new AI agentic coding tools. Are we missing anything?
    We tried to cover support for Anthropic Claude Code, OpenAI Codex, Google Gemini CLI, and GitHub Copilot CLI.
    Are there other popular agentic tools optimized for a shell environment that we should consider?
    I don't want to include VS Code skins like Cursor in this type of review.
    Should we consider Google Antigravity CLI?
