** TODO Review next generation shell tools written in Rust to see if we're missing anything. Focus on popular new tools like ripgrep, fd-find, git plugins like git-delta, difftastic. We just added atuin instead of mcfly which is a great example. Activate deep-research and look for new shell tools that are newly popular on GitHub. Also review blog posts like this for new recommendations:
- https://medium.com/the-software-journal/5-rust-based-cli-tools-that-are-stupidly-fast-4cfcc9c5ce7c
- https://www.repotoire.com/blog/rust-cli-tools-2026
- https://dashen-tech.com/en/dev-tools/10-rust-cli-tools-2026/
- https://www.linuxteck.com/modern-linux-tools/
- https://dev.to/dev_tips/15-rust-tools-to-level-up-your-linux-terminal-2ecf

What are some newly released shell tools that are gaining popularity on Homebrew?
Can we identify any additional useful shell tools that are also newly popular on conda (conda-forge)?
** TODO Conversely, are there any apps currently supported in koopa that are poorly maintained and should be removed? Focus on shell tools and bioinformatics tools. We want to make sure koopa doesn't maintain unnecessary legacy support for poorly maintained tools. Aggressively prune things that aren't maintained. We likely need to enable `deep-research` to perform this review by checking Homebrew, conda-forge, Debian, and other public source repos for software.
** TODO Are there any other modern database technologies we're missing here? We have support for duckdb, parquet, apache-arrow. Do we need to improve support for Apache Spark? Can we add better support for TileDB?
** TODO We need to add install support for Snowflake CLI. Are there other lakehouse providers like Databricks where we need to suport CLI tools here?
** TODO Do we need to install any additional tools to support Google Cloud? Is the Google Cloud SDK the only thing we need?
** TODO Rework our app installer logic for soft dependencies like aws-cli for aws-azure-login. Technically aws-azure-login doesn't require aws to build, but it's basically useless unless we have aws-cli installed. Similar concept for git plugins like git-filter-repo. Some git tools don't actually require git to be installed, but they're useless without git being installed. Can we review our app dependency logic for this situations? Basically I don't want an aws-cli version bump to trigger aws-azure-login reinstall. That doesn't make sense.
