#!/usr/bin/env bash
set -Eeu -o pipefail

KOOPA_PREFIX="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
. "${KOOPA_PREFIX}/shell/posix/include/functions.sh"

if _koopa_is_shared_install
then
    rm -fv "/etc/profile.d/zzz-koopa.sh"
fi

if [[ -f "$(_koopa_dotfiles_config_link)/UNINSTALL.sh" ]]
then
    "$(_koopa_dotfiles_config_link)/UNINSTALL.sh"
fi

rm -frv "$(_koopa_config_prefix)"
rm -frv "$KOOPA_PREFIX"

echo "Uninstallation of koopa was successful."
echo "Restart the shell to complete deactivation."
