#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

bcbio_prefix="/usr/local/bcbio"
version="development"

while (("$#"))
do
    case "$1" in
        --bcbio-prefix=*)
            bcbio_prefix="${1#*=}"
            shift 1
            ;;
        --bcbio-prefix)
            bcbio_prefix="$2"
            shift 2
            ;;
        --version=*)
            version="${1#*=}"
            shift 1
            ;;
        --version)
            version="$2"
            shift 2
            ;;
        *)
            _acid_invalid_arg "$1"
            ;;
    esac
done

_acid_assert_is_dir "$bcbio_prefix"

conda_dir="${bcbio_prefix}/${version}/install/anaconda"
_acid_assert_is_dir "$conda_dir"

conda_exe="${conda_dir}/bin/conda"
_acid_assert_is_executable "$conda_exe"

_acid_message "Conda: '${conda_exe}'."
_acid_message "Removing extracted Conda packages."
_acid_note "Package tarballs will be preserved."

"$conda_exe" clean --yes --packages
