#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"


bcbio_prefix="/usr/local/bcbio"
version="development"

while (("$#"))
do
    case "$1" in
        --bcbio-prefix=*)
            bcbio_prefix="${1#*=}"
            shift 1
            ;;
        --bcbio-prefix)
            bcbio_prefix="$2"
            shift 2
            ;;
        --version=*)
            version="${1#*=}"
            shift 1
            ;;
        --version)
            version="$2"
            shift 2
            ;;
        *)
            _acid_invalid_arg "$1"
            ;;
    esac
done

_acid_assert_is_dir "$bcbio_prefix"

bin_dir="${bcbio_prefix}/${version}/tools/bin"
_acid_assert_is_dir "$bin_dir"

git_dir="${bcbio_prefix}/git"
_acid_assert_is_dir "$git_dir"

tests_dir="${git_dir}/tests"
_acid_assert_is_dir "$tests_dir"

(
    export PATH="${bin_dir}:${PATH}"
    cd "$tests_dir" || exit 1
    rm -frv test_automated_output
    ./run_tests.sh hisat2
    rm -frv test_automated_output
    ./run_tests.sh star
    rm -frv test_automated_output
    ./run_tests.sh fastrnaseq
    rm -frv test_automated_output
    ./run_tests.sh stranded
    rm -frv test_automated_output
    ./run_tests.sh rnaseq
    rm -frv test_automated_output
    ./run_tests.sh chipseq
    rm -frv test_automated_output
    ./run_tests.sh scrnaseq
    rm -frv test_automated_output
)
