#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_acid_assert_has_no_args "$@"

sudo find "/tmp" -mindepth 1 -maxdepth 1 -ctime +30 -exec rm -frv {} \;

if [[ "${TMPDIR:-}" != "/tmp" ]]
then
    sudo find "$TMPDIR" -mindepth 1 -maxdepth 1 -ctime +30 -exec rm -frv {} \;
fi
