#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# FIXME CONSOLIDATE BIOCONDUCTOR AND COMPACT MODES...TOO CONFUSING.

_koopa_configure_vm() { # {{{1
    # """
    # Configure virtual machine.
    # @note Updated 2020-07-02.
    # """
    _koopa_assert_has_no_envs
    local bioconductor check compact data_disk minimal pos r_version source_ip

    # Argument parsing {{{1
    # ==========================================================================

    # Assume we're not building inside Docker by default.
    docker=0
    # Minimal config used for lightweight Docker images. This mode skips all
    # program installation.
    minimal=0
    # Compact mode skips installation of GNU utils and other dependencies that
    # can take a long time to build from source.
    compact=0
    # Bioconductor mode, for continuous integration (CI) checks.
    bioconductor=0
    # Perform version checks at end of install.
    check=1
    # Used for app configuration.
    data_disk=
    # Skip rsync mode by default.
    rsync=0
    # Used for rsync mode.
    source_ip=
    # Set the desired R version automatically.
    r_version="$(_koopa_variable "r")"
    pos=()
    while (("$#"))
    do
        case "$1" in
            --bioconductor)
                bioconductor=1
                shift 1
                ;;
            --compact)
                compact=1
                shift 1
                ;;
            --data-disk=*)
                data_disk="${1#*=}"
                shift 1
                ;;
            --data-disk)
                data_disk="$2"
                shift 2
                ;;
            --minimal)
                minimal=1
                shift 1
                ;;
            --no-check)
                check=0
                shift 1
                ;;
            --r-version=*)
                r_version="${1#*=}"
                shift 1
                ;;
            --r-version)
                r_version="$2"
                shift 2
                ;;
            --source-ip=*)
                source_ip="${1#*=}"
                shift 1
                ;;
            --source-ip)
                source_ip="$2"
                shift 2
                ;;
            "")
                shift 1
                ;;
            --)
                shift 1
                break
                ;;
            --*|-*)
                _koopa_invalid_arg "$1"
                ;;
            *)
                pos+=("$1")
                shift 1
                ;;
        esac
    done
    [[ "${#pos[@]}" -gt 0 ]] && set -- "${pos[@]}"
    _koopa_assert_has_no_args "$@"
    _koopa_is_docker && docker=1
    [[ "$bioconductor" -eq 1 ]] && compact=1
    [[ -n "$source_ip" ]] && rsync=1
    if [[ "$compact" -eq 1 ]] || [[ "$minimal" -eq 1 ]]
    then
        check=0
    fi

    # Initial configuration {{{1
    # ==========================================================================

    _koopa_h1 "Configuring virtual machine."
    # Enable useful global variables that make configuration easier.
    # > export GPG_TTY=/dev/null
    export FORCE_UNSAFE_CONFIGURE=1
    export KOOPA_FORCE=1
    export PYTHONDONTWRITEBYTECODE=true

    # Root user and sudo fixes {{{2
    # --------------------------------------------------------------------------

    _koopa_enable_passwordless_sudo
    _koopa_fix_sudo_setrlimit_error

    # Remove skeleton files {{{2
    # --------------------------------------------------------------------------

    # Remove default user-specific skeleton configuration files. This in
    # particular helps keep shell configuration consistent, especialy for
    # Ubuntu, which sets a lot of config in bashrc.
    sudo rm -frv /etc/skel
    # > sudo mkdir -pv /etc/skel
    # > sudo chmod 0755 /etc/skel

    # Early return in minimal mode {{{2
    # --------------------------------------------------------------------------

    if [[ "$minimal" -eq 1 ]]
    then
        _koopa_success "Configuration completed successfully."
        exit 0
    fi

    # Koopa paths {{{2
    # --------------------------------------------------------------------------

    # e.g. '/usr/local'.
    make_prefix="$(_koopa_make_prefix)"
    # For data disk, linked to '/mnt/data01/n/opt' (see below).
    # e.g. '/usr/local/opt'.
    app_prefix="$(_koopa_app_prefix)"

    # Local disk configuration {{{1
    # ==========================================================================

    if [[ "$docker" -eq 0 ]]
    then
        _koopa_info "Checking available local disk space."
        df -h "/"
        gb_total="$(_koopa_disk_gb_total)"
        [ "$gb_total" -lt 16 ] && compact=1
        # > gb_free="$(_koopa_disk_gb_free)"
        # > [ "$gb_free" -lt 10 ] && compact=1
        # Attempt to detect an attached disk automatically.
        if [[ ! -e "$data_disk" ]]
        then
            # Our current standard configuration on AWS EC2 VMs.
            [[ -e "/mnt/data01" ]] && data_disk="/mnt/data01"
        fi
        if [[ -e "$data_disk" ]]
        then
            _koopa_info "Data disk detected at '${data_disk}'."
        fi
    fi
    # Prepare app prefix on external disk for write access (e.g. '/n').
    data_disk_link="$(_koopa_data_disk_link_prefix)"
    if [[ -e "$data_disk" ]] && \
        { [[ ! -L "$data_disk_link" ]] || [[ ! -L "$app_prefix" ]]; }
    then
        _koopa_h2 "Symlinking '${data_disk_link}' on '${data_disk}'."
        _koopa_rm "$data_disk_link" "$app_prefix"
        # e.g. '/mnt/data01/n'.
        data_disk_real="${data_disk}${data_disk_link}"
        _koopa_ln "$data_disk_real" "$data_disk_link"
        # e.g. 'opt'.
        app_prefix_bn="$(basename "$app_prefix")"
        # e.g. '/mnt/data01/n/opt'
        app_prefix_real="${data_disk_real}/${app_prefix_bn}"
        _koopa_mkdir "$app_prefix_real"
        # e.g. '/mnt/data01/n/opt' to '/usr/local/opt'.
        _koopa_ln "$app_prefix_real" "$app_prefix"
    else
        _koopa_mkdir "$app_prefix"
    fi

    # Base system {{{1
    # ==========================================================================

    _koopa_h2 "Installing base system."
    _koopa_update_etc_profile_d
    _koopa_install_dotfiles
    _koopa_mkdir "$make_prefix"
    _koopa_assert_is_installed install-base
    install_base_flags=()
    [[ "$compact" -eq 1 ]] && install_base_flags+=("--compact")
    install-base "${install_base_flags[@]:-}"
    # Maybe include: tclsh
    _koopa_assert_is_installed \
        autoconf \
        bc \
        bzip2 \
        g++ \
        gcc \
        gfortran \
        gzip \
        make \
        man \
        msgfmt \
        tar \
        unzip \
        xml2-config \
        xz
    _koopa_assert_is_file \
        /usr/bin/gcc \
        /usr/bin/g++
    sudo ldconfig

    # rsync mode {{{1
    # ==========================================================================

    [[ "$rsync" -eq 1 ]] && rsync-vm --source-ip="$source_ip"

    # Programs {{{1
    # ==========================================================================

    _koopa_run_if_installed install-llvm
    install-conda
    install-openjdk
    if [[ "$compact" -eq 0 ]]
    then
        install-cmake
        install-make
        install-autoconf
        install-automake
        install-libtool
        install-texinfo
        install-binutils
        install-coreutils
        install-findutils
        install-patch
        install-ncurses
        install-gnupg
        install-grep
        install-gawk
        install-parallel
        install-rsync
        install-sed
        install-zsh
        install-bash
        install-fish
        install-curl
        install-wget
        install-git
        install-openssh
        install-python
        install-perl
        install-geos
        install-sqlite
        install-proj
        install-gdal
        install-hdf5
        install-gsl
        install-udunits
        install-subversion
        install-go
        install-ruby
        install-rust
        install-password-store
        install-neofetch
        install-fzf
        install-the-silver-searcher
    fi
    install-tmux
    install-vim
    install-shellcheck
    install-shunit2
    _koopa_run_if_installed install-aws-cli
    if [[ "$compact" -eq 0 ]] && [[ "$docker" -eq 0 ]]
    then
        _koopa_run_if_installed \
            install-azure-cli \
            install-docker \
            install-google-cloud-sdk
        install-docker-credential-pass
        install-neovim
        install-emacs
        install-julia
        install-lua
        install-luarocks
        install-lmod
        install-htop
        install-autojump
        install-gcc --cellar-only
    fi
    if [[ "$r_version" == "devel" ]]
    then
        install-r-devel
    elif _koopa_is_installed install-r-cran-binary
    then
        install-r-cran-binary --version="$r_version"
    else
        install-r --version="$r_version"
    fi
    _koopa_run_if_installed install-rstudio-server install-shiny-server
    _koopa_update_r_config
    _koopa_update_lmod_config

    # Language-specific packages {{{1
    # ==========================================================================

    sudo ldconfig
    if [[ "$rsync" -eq 0 ]]
    then
        install-python-packages
        venv-create-r-reticulate
        install-r-packages
        if [[ "$compact" -eq 0 ]]
        then
            install-ruby-gems
            install-rust-packages
        fi
    fi

    # Bioinformatics tools {{{1
    # ==========================================================================

    if [[ "$compact" -eq 0 ]] && [[ "$docker" -eq 0 ]] && [[ "$rsync" -eq 0 ]]
    then
        # > install-aspera-connect
        # > install-bcbio
        conda-create-bioinfo-envs
    fi

    # Final steps and clean up {{{1
    # ==========================================================================

    # Generate SSH key {{{2
    # --------------------------------------------------------------------------

    [[ "$docker" -eq 0 ]] && generate-ssh-key

    # Remove legacy packages {{{2
    # --------------------------------------------------------------------------

    # Ensure that perlbrew, pyenv, and rbenv are no longer installed by default.
    _koopa_rm \
        "${app_prefix}/perl" \
        "${app_prefix}/python/pyenv" \
        "${app_prefix}/perl"
    # Otherwise, ensure permissions are correct:
    # > _koopa_fix_pyenv_permissions
    # > _koopa_fix_rbenv_permissions

    # Fix permissions {{{2
    # --------------------------------------------------------------------------

    _koopa_set_permissions --recursive "$make_prefix"
    _koopa_set_permissions --recursive "$app_prefix"
    _koopa_fix_zsh_permissions

    # Remove symlinks and dirs {{{2
    # --------------------------------------------------------------------------

    _koopa_remove_broken_symlinks "$make_prefix"
    _koopa_remove_broken_symlinks "$app_prefix"
    _koopa_remove_empty_dirs "$make_prefix"
    _koopa_remove_empty_dirs "$app_prefix"

    # Remove temporary files {{{2
    # --------------------------------------------------------------------------

    if [[ "$compact" -eq 1 ]] || [[ "$docker" -eq 1 ]]
    then
        _koopa_h2 "Removing caches, logs, and temporary files."
        # Don't clear '/var/log/' here, as this can mess with 'sshd'.
        sudo rm -frv \
            /root/.cache \
            /tmp/* \
            /var/backups/* \
            /var/cache/*
        if _koopa_is_debian
        then
            sudo rm -fr /var/lib/apt/lists/*
        fi
    fi

    # Run system check and return {{{1
    # --------------------------------------------------------------------------

    [[ "$check" -eq 1 ]] && koopa check
    _koopa_success "Configuration completed successfully."
    return 0
}

_koopa_configure_vm "$@"
