#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

user="$USER"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)
    [user="${user}"]

Enable passwordless sudo access.

required positional arguments with defaults:
    1.  User name.
        Defaults to '${user}'.

$(_koopa_help_args)

details:
    User configuration file is saved in '/etc/sudoers.d/'.

note:
    Bash script.
    Updated 2019-10-01.
EOF
}

_koopa_help "$@"



# Arguments                                                                 {{{1
# ==============================================================================

user="${1:-$user}"



# Script                                                                    {{{1
# ==============================================================================

sudo mkdir -pv "/etc/sudoers.d"
echo "${user} ALL=(ALL) NOPASSWD: ALL" | \
    sudo tee "/etc/sudoers.d/${user}"
