#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_sudo



# Arguments                                                                 {{{1
# ==============================================================================

user="${1:-$USER}"



# Script                                                                    {{{1
# ==============================================================================

sudo mkdir -pv "/etc/sudoers.d"
echo "${user} ALL=(ALL) NOPASSWD: ALL" | \
    sudo tee "/etc/sudoers.d/${user}"
