#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_sudo
_koopa_assert_is_installed go

name="singularity"
version="$(_koopa_variable "$name")"
prefix="$(_koopa_cellar_prefix)/${name}/${version}"
tmp_dir="$(_koopa_tmp_dir)"
exe_file="${prefix}/bin/singularity"

_koopa_message "Installing ${name} ${version}."

(
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="singularity-${version}.tar.gz"
    url_stem="https://github.com/sylabs/singularity/releases/download"
    wget "${url_stem}/v${version}/${file}"
    _koopa_extract "$file"
    cd "singularity" || exit 1
    ./mconfig --prefix="$prefix"
    make -C builddir
    # Singularity must be installed as root to function correctly.
    sudo make -C builddir installi
    rm -fr "$tmp_dir"
)

_koopa_link_cellar "$name" "$version"

"$exe_file" version
command -v "$exe_file"
