#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

koopa::assert_has_no_envs
koopa::assert_is_installed docker

name="bcbio-vm"
prefix="$(koopa::app_prefix)/${name}"

koopa::exit_if_dir "$prefix"

koopa::install_start "$name" "$prefix"

bin_dir="${prefix}/anaconda/bin"
tmp_dir="$(koopa::tmp_dir)"

# Docker {{{1
# ==============================================================================

if ! groups | grep -q "docker"
then
    sudo groupadd docker
    sudo service docker restart
    sudo gpasswd -a "$(whoami)" docker
    newgrp docker
fi

# conda {{{1
# ==============================================================================

(
    koopa::cd_tmp_dir "$tmp_dir"
    file="Miniconda3-latest-Linux-x86_64.sh"
    url="https://repo.continuum.io/miniconda/${file}"
    koopa::download "$url"
    bash "$file" -b -p "${prefix}/anaconda"
)

rm -fr "$tmp_dir"

# bcbio-vm {{{1
# ==============================================================================

"${bin_dir}/conda" install --yes \
    --channel="conda-forge" \
    --channel=bioconda \
    bcbio-nextgen \
    bcbio-nextgen-vm

sudo rm -fv /usr/local/bin/bcbio_vm.py
sudo ln -fnsv "${bin_dir}/bcbio_vm.py" /usr/local/bin/bcbio_vm.py

sudo rm -fv /usr/local/bin/bcbiovm_conda
sudo ln -fnsv "${bin_dir}/conda" /usr/local/bin/bcbiovm_conda

sudo chgrp docker /usr/local/bin/bcbio_vm.py
sudo chmod g+s /usr/local/bin/bcbio_vm.py

# v1.1.3
# > data_dir="${prefix}/v1.1.3"
# > image="quay.io/bcbio/bcbio-vc:1.1.3-v1.1.3"

# latest
data_dir="${prefix}/latest"
# > image="quay.io/bcbio/bcbio-vc"

"${bin_dir}/bcbio_vm.py" --datadir="$data_dir" saveconfig
# > "${bin_dir}/bcbio_vm.py" install --tools --image "$image"

koopa::install_success "$name"
