#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_sudo
_koopa_assert_is_installed lua luarocks

name="lmod"
version="$(_koopa_variable "$name")"
prefix="/opt/apps"
_koopa_assert_is_not_dir "$prefix"
data_dir="/opt/moduleData"
_koopa_assert_is_not_dir "$data_dir"
tmp_dir="$(_koopa_tmp_dir)/${name}"

_koopa_message "Installing ${name} ${version}."

(
    rm -fr "$tmp_dir"
    mkdir -pv "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="${version}.tar.gz"
    url="https://github.com/TACC/Lmod/archive/${file}"
    _koopa_download "$url"
    _koopa_extract "$file"
    cd "Lmod-${version}" || exit 1
    ./configure \
        --prefix="${prefix}" \
        --with-spiderCacheDir="${data_dir}/cacheDir" \
        --with-updateSystemFn="${data_dir}/system.txt"
    sudo make install
    rm -fr "$tmp_dir"
)

# bash, zsh:
sudo ln -fnsv "/opt/apps/lmod/lmod/init/profile" \
    "/etc/profile.d/z00_lmod.sh"

# csh, tcsh:
# > sudo ln -fnsv /opt/apps/lmod/lmod/init/cshrc \
# >     /etc/profile.d/z00_lmod.csh

# fish:
# > sudo ln -fnsv /opt/apps/lmod/lmod/init/profile.fish \
# >     /etc/fish/conf.d/z00_lmod.fish

module --version
# > module spider
