#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_koopa_assert_is_installed bcbio_nextgen.py

genomes="${1:-"BDGP6,canFam3,hg38,mm10,rn6"}"
IFS=', ' read -r -a genomes <<< "$genomes"

timestamp="$(date "+%Y%m%d_%H%M%S")"
version="$(bcbio_nextgen.py --version)"
log_dir="${HOME}/logs/${HOSTNAME}/bcbio"
log_file="${log_dir}/${timestamp}-install-bcbio-genomes-${version}.log"
mkdir -pv "$log_dir"

tmp_dir="$(_koopa_tmp_dir)/bcbio"
cores="$(_koopa_cpu_count)"

bcbio_exe="$(_koopa_which_realpath "bcbio_nextgen.py")"
bcbio_dir="$(cd "$(dirname "$bcbio_exe")/../.." && pwd -P)"
genomes_dir="${bcbio_dir}/genomes"

_koopa_message "Installing bcbio genomes '${genomes[*]}' into '${genomes_dir}'."

genome_flags=()
for genome in "${genomes[@]}"
do
    genome_flags+=("--genomes=${genome}")
done

flags=(
    "--upgrade=skip"
    "--cores=${cores}"
    "${genome_flags[@]}"
)

(
    _koopa_cd_tmp_dir "$tmp_dir"
    bcbio_nextgen.py upgrade "${flags[@]}" 2>&1 | tee "$log_file"
    rm -fr "$tmp_dir"
)
