#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_acid_assert_has_sudo
_acid_assert_is_installed go

name="singularity"
version="$(_acid_variable "$name")"
prefix="$(_acid_cellar_prefix)/${name}/${version}"
tmp_dir="$(_acid_tmp_dir)"
exe_file="${prefix}/bin/singularity"

_acid_message "Installing ${name} ${version}."

file="singularity-${version}.tar.gz"
url="https://github.com/sylabs/singularity/releases/download/\
v${version}/${file}"

(
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    _acid_download "$url"
    _acid_extract "$file"
    cd "singularity" || exit 1
    ./mconfig --prefix="$prefix"
    make -C builddir
    # Singularity must be installed as root to function correctly.
    sudo make -C builddir installi
    rm -fr "$tmp_dir"
)

_acid_link_cellar "$name" "$version"

"$exe_file" version
command -v "$exe_file"
