#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_sudo

jdk_dir="${1:-"/opt/jdk"}"
version="13"
jdk_version_dir="${jdk_dir}/jdk-${version}"

_koopa_prefix_mkdir "$jdk_dir"

# Download and extract the JDK, if necessary.
if [[ ! -d "$jdk_version_dir" ]]
then
    (
        cd "${jdk_dir}" || exit 1
        file="openjdk-13_linux-x64_bin.tar.gz"
        hash="5b8a42f3905b406298b72d750b6919f6"
        url="https://download.java.net/java/GA/jdk13/${hash}/33/GPL/${file}"
        _koopa_download "$url"
        _koopa_message "Extracting '${file}' to '${jdk_dir}'."
        tar -xzvf "$file" -C "$jdk_dir"
    )
fi

_koopa_set_permissions "$jdk_dir"

priority="100"
sudo update-alternatives --install \
    "/usr/bin/java" \
    "java" \
    "${jdk_dir}/jdk-${version}/bin/java" \
    "$priority"
sudo update-alternatives --install \
    "/usr/bin/javac" \
    "javac" \
    "${jdk_dir}/jdk-${version}/bin/javac" \
    "$priority"
sudo update-alternatives --install \
    "/usr/bin/jar" \
    "jar" \
    "${jdk_dir}/jdk-${version}/bin/jar" \
    "$priority"

sudo update-alternatives --config java
sudo update-alternatives --config javac
sudo update-alternatives --config jar

update-alternatives --display java
update-alternatives --display javac
update-alternatives --display jar

java --version

# Update rJava configuration.
if _koopa_is_installed R
then
    r-javareconf
fi
