#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

jdk_dir="/opt/jdk"
version="13"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)
    [dir="${jdk_dir}"]

Install Java Development Kit (JDK) 13.

required positional arguments with defaults:
    1.  JDK installation directory.
        Defaults to '${jdk_dir}'.

$(_koopa_help_args)

details:
    Check that other Java versions are not installed before continuing.
    > sudo yum list installed | grep java

    Clean up on RHEL 7:
    > sudo yum remove R R-devel R-java R-java-devel
    > sudo yum remove java-1.8.0-ibm java-1.8.0-openjdk-headless
    > sudo yum remove java-latest-openjdk java-latest-openjdk-devel
    > sudo yum remove java-latest-openjdk-headless

    Note that yum installs to '/usr/lib/jvm/' on Fedora.
    Symlinks are defined in '/etc/alternatives/'.

see also:
    - https://jdk.java.net/
    - https://stackoverflow.com/questions/12787757/
          how-to-use-the-command-update-alternatives-config-java
    - https://www.digitalocean.com/community/tutorials/
          how-to-manually-install-oracle-java-on-a-debian-or-ubuntu-vps

note:
    Bash script.
    Updated 2019-10-02.
EOF
}

_koopa_help "$@"



# Arguments                                                                 {{{1
# ==============================================================================

jdk_dir="${1:-$jdk_dir}"



# Script                                                                    {{{1
# ==============================================================================

sudo mkdir -pv "${jdk_dir}"
_koopa_prefix_chgrp "${jdk_dir}"
sudo chmod g+s "${jdk_dir}"

(
    cd "${jdk_dir}" || exit 1
    file="openjdk-13_linux-x64_bin.tar.gz"
    _koopa_assert_is_not_file "$file"
    wget "https://download.java.net/java/GA/jdk13/5b8a42f3905b406298b72d750b6919f6/33/GPL/${file}"
    tar -xzvf "$file" -C "$jdk_dir"
)

_koopa_build_set_permissions "${jdk_dir}"

sudo update-alternatives --install \
    "/usr/bin/java" \
    "java" \
    "${jdk_dir}/jdk-${version}/bin/java" \
    "100"
sudo update-alternatives --install \
    "/usr/bin/javac" \
    "javac" \
    "${jdk_dir}/jdk-${version}/bin/javac" \
    "100"

sudo update-alternatives --config java
sudo update-alternatives --config javac

update-alternatives --display java
update-alternatives --display javac

java --version

