#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

name="singularity"
version="$(_koopa_variable "$name")"
prefix="$(_koopa_cellar_prefix)/${name}/${version}"

_koopa_exit_if_dir "$prefix"

_koopa_h1 "Installing ${name} ${version}."

_koopa_assert_is_installed go

exe_file="${prefix}/bin/singularity"
tmp_dir="$(_koopa_tmp_dir)"

(
    _koopa_cd_tmp_dir "$tmp_dir"
    file="singularity-${version}.tar.gz"
    url="https://github.com/sylabs/singularity/releases/download/\
v${version}/${file}"
    _koopa_download "$url"
    _koopa_extract "$file"
    cd "singularity" || exit 1
    ./mconfig --prefix="$prefix"
    make -C builddir
    sudo make -C builddir install
)

rm -fr "$tmp_dir"

_koopa_link_cellar "$name" "$version"

"$exe_file" version
command -v "$exe_file"
