#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

name="bcl2fastq"
version="$(_koopa_variable "$name")"
tmp_dir="$(_koopa_tmp_dir)/${name}"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install Illumina BCL to FASTQ converter.

$(_koopa_help_args)

details:
    Installs to '/usr/local/bin/bcl2fastq'.

see also:
    https://support.illumina.com/content/dam/illumina-support/documents/
        downloads/software/bcl2fastq/bcl2fastq2-v2-20-0-linux-x86-64.zip

note:
    Bash script.
    Updated 2019-10-08.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

printf "Installing %s %s.\n" "$name" "$version"

_koopa_assert_is_installed rpm

file="bcl2fastq2-v2-20-0-linux-x86-64.zip"
url="https://support.illumina.com/content/dam/illumina-support/documents/\
downloads/software/bcl2fastq/${file}"

if _koopa_is_installed bcl2fastq
then
    flags=("--reinstall")
else
    flags=("--install")
fi

(
    rm -fr "$tmp_dir"
    mkdir -pv "$tmp_dir"
    cd "$tmp_dir" || exit 1
    wget "$url"
    unzip "$file"
    sudo rpm $"${flags[@]}" "bcl2fastq2-v${version}-Linux-x86_64.rpm"
    rm -fr "$tmp_dir"
)
