#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

prefix="$(_koopa_build_prefix)/bcbio-vm"
bin_dir="${prefix}/anaconda/bin"
tmp_dir="$(_koopa_tmp_dir)/bcbio-vm"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install bcbio-vm.

$(_koopa_help_args)

details:
    Note that configuration is saved in:
    '~/.config/bcbio-nextgen/bcbio-docker-config.yaml'.
    This sets the location of 'datadir', for example.

see also:
    https://quay.io/repository/bcbio/bcbio-vc?tab=tags

note:
    Bash script.
    Updated 2019-10-01.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

_koopa_assert_has_no_environments
_koopa_assert_is_installed docker

# Docker                                                                    {{{2
# ------------------------------------------------------------------------------

sudo groupadd docker
sudo service docker restart
sudo gpasswd -a "$(whoami)" docker
newgrp docker

# conda                                                                     {{{2
# ------------------------------------------------------------------------------

(
    rm -fr "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    bash Miniconda3-latest-Linux-x86_64.sh -b -p "${prefix}/anaconda"
    rm -fr "$tmp_dir"
)

# bcbio-vm                                                                  {{{2
# ------------------------------------------------------------------------------

"${bin_dir}/conda" install --yes -c conda-forge -c bioconda bcbio-nextgen
"${bin_dir}/conda" install --yes -c conda-forge -c bioconda bcbio-nextgen-vm

sudo rm -fv /usr/local/bin/bcbio_vm.py
sudo ln -fnsv "${bin_dir}/bcbio_vm.py" /usr/local/bin/bcbio_vm.py

sudo rm -fv /usr/local/bin/bcbiovm_conda
sudo ln -fnsv "${bin_dir}/conda" /usr/local/bin/bcbiovm_conda

sudo chgrp docker /usr/local/bin/bcbio_vm.py
sudo chmod g+s /usr/local/bin/bcbio_vm.py

# v1.1.3
# > data_dir="${prefix}/v1.1.3"
# > image="quay.io/bcbio/bcbio-vc:1.1.3-v1.1.3"

# latest
data_dir="${prefix}/latest"
image="quay.io/bcbio/bcbio-vc"

bcbio_vm.py --datadir="$data_dir" saveconfig
bcbio_vm.py install --tools --image "$image"
