#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_acid_assert_has_sudo
_acid_assert_is_installed rpm

name="bcl2fastq"
version="$(_acid_variable "$name")"
tmp_dir="$(_acid_tmp_dir)/${name}"
prefix="$(_acid_build_prefix)/${name}"

_acid_message "Installing ${name} ${version}."

file="bcl2fastq2-v2-20-0-linux-x86-64.zip"
url="https://support.illumina.com/content/dam/illumina-support/documents/\
downloads/software/bcl2fastq/${file}"

(
    rm -fr "$tmp_dir"
    mkdir -pv "$tmp_dir"
    cd "$tmp_dir" || exit 1
    _acid_download "$url"
    unzip "$file"
    sudo rpm -v \
        --force \
        --install \
        --prefix="${prefix}" \
        "bcl2fastq2-v${version}-Linux-x86_64.rpm"
    rm -fr "$tmp_dir"
)

# Remove redundant nested 'bcl2fastq' directory.
sudo rm -frv "${prefix}/bcl2fastq"
