#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_acid_assert_has_no_envs

prefix="$(_acid_build_prefix)/bcbio"
version="stable"

tmp_dir="$(_acid_tmp_dir)/bcbio"

timestamp="$(date "+%Y%m%d-%H%M%S")"
log_dir="${HOME}/logs/${HOSTNAME}/bcbio"
log_file="${log_dir}/${timestamp}-install-bcbio.log"

while (("$#"))
do
    case "$1" in
        --prefix=*)
            prefix="${1#*=}"
            shift 1
            ;;
        --prefix)
            prefix="$2"
            shift 2
            ;;
        --version=*)
            version="${1#*=}"
            shift 1
            ;;
        --version)
            version="$2"
            shift 2
            ;;
        *)
            _acid_invalid_arg "$1"
            ;;
    esac
done

prefix="$(_acid_strip_trailing_slash "$prefix")"

if [[ "$version" == "stable" ]]
then
    # > current="$(_acid_github_latest_release "bcbio/bcbio-nextgen")"
    _acid_bcbio_version() {
        curl --silent "https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/requirements-conda.txt" \
            | grep 'bcbio-nextgen=' \
            | cut -d '=' -f 2
    }
    current="$(_acid_bcbio_version)"
    prefix="${prefix}/${current}"
else
    prefix="${prefix}/${version}"
fi

_acid_assert_is_not_dir "$prefix"

_acid_message "Installing bcbio into '${prefix}'."

_acid_message "Saving install log at '${log_file}'."
mkdir -pv "$log_dir"

_acid_prefix_mkdir "$prefix"
install_dir="${prefix}/install"
tools_dir="${prefix}/tools"

(
    rm -fr "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="bcbio_nextgen_install.py"
    url="https://raw.github.com/bcbio/bcbio-nextgen/master/scripts/${file}"
    _acid_download "$url"
    python "$file" \
        "$install_dir" \
        --tooldir="$tools_dir" \
        --upgrade="$version" \
        --datatarget="rnaseq" \
        --nodata \
        --isolate \
        2>&1 | tee "$log_file"
)

_acid_message "Fixing MACS2/numpy issue."
_acid_note "https://github.com/bcbio/bcbio-nextgen/issues/2853"
"${tools_dir}/bin/bcbio_conda" install -y --name python2 numpy

# Keep install owned by current user, so we can install genomes easily.
_acid_prefix_chgrp "$prefix"

# Here's how to set to root, otherwise:
# > _acid_set_permissions "$prefix"

# Disable group write access to install.
# > chmod -R g-w "$install_dir" "$tools_dir"

