#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# https://openjdk.java.net/
# https://jdk.java.net/13/

version="$(_koopa_variable "java")"
jdk_dir="$(_koopa_app_prefix)/jdk"
prefix="${jdk_dir}/${version}"
# > _koopa_assert_is_not_dir "$jdk_version_dir"

_koopa_message "Installing JDK ${version} at '${prefix}'."

# Download and extract the JDK, if necessary.
if [[ ! -d "$prefix" ]]
then
    _koopa_prefix_mkdir "$jdk_dir"
    (
        cd "${jdk_dir}" || exit 1
        file="openjdk-${version}_linux-x64_bin.tar.gz"
        case "$version" in
            13.0.1)
                unique="cec27d702aa74d5a8630c65ae61e4305/9"
                ;;
            13)
                unique="5b8a42f3905b406298b72d750b6919f6/33"
                ;;
        esac
        url="https://download.java.net/java/GA/jdk${version}/${unique}/GPL/${file}"
        _koopa_download "$url"
        _koopa_extract "$file"
        mv -v "jdk-${version}" "$version"
    )
fi

_koopa_set_permissions "$jdk_dir"

priority="100"

sudo rm -fv /var/lib/alternatives/java
sudo update-alternatives --install \
    "/usr/bin/java" \
    "java" \
    "${prefix}/bin/java" \
    "$priority"
sudo update-alternatives --set \
    "java" \
    "${prefix}/bin/java"

sudo rm -fv /var/lib/alternatives/javac
sudo update-alternatives --install \
    "/usr/bin/javac" \
    "javac" \
    "${prefix}/bin/javac" \
    "$priority"
sudo update-alternatives --set \
    "javac" \
    "${prefix}/bin/javac"

sudo rm -fv /var/lib/alternatives/jar
sudo update-alternatives --install \
    "/usr/bin/jar" \
    "jar" \
    "${prefix}/bin/jar" \
    "$priority"
sudo update-alternatives --set \
    "jar" \
    "${prefix}/bin/jar"

update-alternatives --display java
update-alternatives --display javac
update-alternatives --display jar

java --version

# Update rJava configuration.
# > if _koopa_is_installed R
# > then
# >     r-javareconf
# > fi
