#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

jdk_dir="/opt/jdk"
version="13"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)
    [dir="${jdk_dir}"]

Install Java Development Kit (JDK) 13.

required positional arguments with defaults:
    1.  JDK installation directory.
        Defaults to '${jdk_dir}'.

$(_koopa_help_args)

details:
    Check that other Java versions are not installed before continuing:
    """sh
    sudo yum list installed | grep java
    """

    Clean up on RHEL 7:
    remove-rhel7-rpm-cruft

    Note that yum installs to '/usr/lib/jvm/' on Fedora.
    Symlinks are defined in '/etc/alternatives/'.

see also:
    - https://jdk.java.net/
    - https://stackoverflow.com/questions/12787757/
          how-to-use-the-command-update-alternatives-config-java
    - https://www.digitalocean.com/community/tutorials/
          how-to-manually-install-oracle-java-on-a-debian-or-ubuntu-vps

note:
    Bash script.
    Updated 2019-10-22.
EOF
}

_koopa_help "$@"



# Arguments                                                                 {{{1
# ==============================================================================

jdk_dir="${1:-$jdk_dir}"
jdk_version_dir="${jdk_dir}/jdk-${version}"



# Script                                                                    {{{1
# ==============================================================================

# Download and extract the JDK, if necessary.
if [[ ! -d "$jdk_version_dir" ]]
then
    sudo mkdir -pv "${jdk_dir}"
    _koopa_prefix_chgrp "${jdk_dir}"
    sudo chmod g+s "${jdk_dir}"
    (
        cd "${jdk_dir}" || exit 1
        file="openjdk-13_linux-x64_bin.tar.gz"
        hash="5b8a42f3905b406298b72d750b6919f6"
        url="https://download.java.net/java/GA/jdk13/${hash}/33/GPL/${file}"
        wget "$url"
        _koopa_message "Extracting '${file}' to '${jdk_dir}'."
        tar -xzvf "$file" -C "$jdk_dir"
    )
fi

_koopa_set_permissions "${jdk_dir}"

priority="100"
sudo update-alternatives --install \
    "/usr/bin/java" \
    "java" \
    "${jdk_dir}/jdk-${version}/bin/java" \
    "$priority"
sudo update-alternatives --install \
    "/usr/bin/javac" \
    "javac" \
    "${jdk_dir}/jdk-${version}/bin/javac" \
    "$priority"
sudo update-alternatives --install \
    "/usr/bin/jar" \
    "jar" \
    "${jdk_dir}/jdk-${version}/bin/jar" \
    "$priority"

sudo update-alternatives --config java
sudo update-alternatives --config javac
sudo update-alternatives --config jar

update-alternatives --display java
update-alternatives --display javac
update-alternatives --display jar

java --version

# Update rJava configuration.
if _koopa_is_installed R
then
    r-javareconf
fi
