#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

name="aws-cli"
install_dir="$(_koopa_cellar_prefix)/${name}"
bin_dir="$(_koopa_make_prefix)/bin"

_koopa_exit_if_dir "$install_dir"

name_fancy="AWS CLI 2"

_koopa_install_start "$name_fancy"
_koopa_dl "install_dir" "$install_dir"
_koopa_dl "bin_dir" "$bin_dir"

tmp_dir="$(_koopa_tmp_dir)"

(
    _koopa_cd_tmp_dir "$tmp_dir"
    file="awscli-exe-linux-x86_64.zip"
    url="https://awscli.amazonaws.com/${file}"
    _koopa_download "$url"
    _koopa_extract "$file"
    sudo ./aws/install \
        --install-dir "$install_dir" \
        --bin-dir "$bin_dir"
)

rm -fr "$tmp_dir"

_koopa_install_success "$name_fancy"
