#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
usage: link-coreutils-env [--help|-h]

Link coreutils env.

optional arguments:
    --help, -h
        Show this help message and exit.

details:
    This may be necessary to re-run after yum update on RHEL 7.

note:
    Bash script.
    Updated 2019-10-01.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

build_prefix="$(_koopa_build_prefix)"
printf "Replacing '/usr/bin/env' with '/usr/local/bin/env'.\n"

if [[ ! -L "/usr/bin/env" ]]
then
    printf "System version will be renamed to 'env.bak'.\n"
    sudo rm -fv "/usr/bin/env.bak"
    sudo mv -fv "/usr/bin/env" "/usr/bin/env.bak"
else
    sudo rm -fv "/usr/bin/env"
fi

sudo ln -fnsv "${build_prefix}/bin/env" "/usr/bin/env"
