#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_args "$#"

# Argument parsing {{{1
# ==============================================================================

pos=()
while (("$#"))
do
    case "$1" in
        --source-ip=*)
            source_ip="${1#*=}"
            shift 1
            ;;
        --source-ip)
            source_ip="$2"
            shift 2
            ;;
        --)
            shift 1
            break
            ;;
        --*|-*)
            _koopa_invalid_arg "$1"
            ;;
        *)
            pos+=("$1")
            shift 1
            ;;
    esac
done
[[ "${#pos[@]}" -gt 0 ]] && set -- "${pos[@]}"

if [[ -z "${source_ip:-}" ]]
then
    _koopa_missing_arg
fi

# Source check {{{1
# ==============================================================================

# Ensure that source and local (host) IP addresses are not identical. If they
# are, early exit without error, as this script is called inside 'configure-vm'.
host_ip="$(_koopa_local_ip_address)"
if [[ "$source_ip" == "$host_ip" ]]
then
    _koopa_exit "Skipping rsync because '${host_ip}' is source machine."
fi

# Custom paths {{{1
# ==============================================================================

if [[ "$#" -gt 0 ]]
then
    for prefix in "$@"
    do
        _koopa_rsync_vm \
            --prefix="$prefix" \
            --source-ip="$source_ip"
    done
    exit 0
fi

# Default paths {{{1
# ==============================================================================

# app prefix {{{2
# ------------------------------------------------------------------------------

# Need to sync this before make prefix step, otherwise some symlinks won't
# resolve as expected, and chmod will error.

app_prefix="$(_koopa_app_prefix)"

if [[ -d "$app_prefix" ]]
then
    # Skipping programs that are specific to powerful multi-core VMs.
    readarray -t app_flags <<< "$(_koopa_rsync_flags)"
    if ! _koopa_is_powerful
    then
        app_flags+=(
            "--exclude=bcbio"
            "--exclude=cellranger"
            "--exclude=cellranger-atac"
            "--exclude=omicsoft"
        )
    fi
    _koopa_rsync_vm \
        --flags="${app_flags[*]}" \
        --prefix="$app_prefix" \
        --source-ip="$source_ip"
else
    _koopa_note "Skipping '${app_prefix}'."
fi

# make prefix {{{2
# ------------------------------------------------------------------------------

make_prefix="$(_koopa_make_prefix)"

if [[ -d "$make_prefix" ]]
then
    _koopa_rsync_vm \
        --prefix="$make_prefix" \
        --source-ip="$source_ip"
else
    _koopa_note "Skipping '${make_prefix}'."
fi

# refdata prefix {{{2
# ------------------------------------------------------------------------------

refdata_prefix="$(_koopa_refdata_prefix)"

if [[ -d "$refdata_prefix" ]]
then
    # Skipping references that are specific to powerful multi-core VMs.
    readarray -t refdata_flags <<< "$(_koopa_rsync_flags)"
    if ! _koopa_is_powerful
    then
        refdata_flags+=(
            "--exclude=bcbio"
            "--exclude=cellranger"
            "--exclude=cellranger-atac"
            "--exclude=gtex"
        )
    fi
    _koopa_rsync_vm \
        --flags="${refdata_flags[*]}" \
        --prefix="$refdata_prefix" \
        --source-ip="$source_ip"
else
    _koopa_note "Skipping '${refdata_prefix}'."
fi

_koopa_success "rsync from ${source_ip} was successful."
