#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_args "$@"
_koopa_assert_is_installed rsync

while (("$#"))
do
    case "$1" in
        --data-disk=*)
            data_disk="${1#*=}"
            shift 1
            ;;
        --data-disk)
            data_disk="$2"
            shift 2
            ;;
        --source-ip=*)
            source_ip="${1#*=}"
            shift 1
            ;;
        --source-ip)
            source_ip="$2"
            shift 2
            ;;
        *)
            _koopa_invalid_arg "$1"
            ;;
    esac
done

if [[ -z "${data_disk:-}" ]] || [[ -z "${source_ip:-}" ]]
then
    _koopa_missing_arg
fi

source_user="$USER"
host_ip="$(ip-address)"

_koopa_h1 "Syncing configuration from '${source_ip}'."

# Check for accidental sync from source machine.
if [[ "$source_ip" == "$host_ip" ]]
then
    _koopa_note "On source machine: '${source_ip}'."
    exit 0
fi

mapfile -t flags < <(_koopa_rsync_flags)
# > flags+=("--omit-dir-times")
flags_bak=("${flags[@]}")

# /n/app  {{{1
# ==============================================================================

# Create the '/n' symlink, if necessary.
n_source="${data_disk}/n"
sudo mkdir -pv "${data_disk}/n"
sudo chown root:root "$n_source"
sudo chmod 0755 "$n_source"
sudo ln -fnsfv "$n_source" /n

dir="/n/app"

_koopa_h2 "Updating '${dir}' from '${source_ip}'."

sudo mkdir -pv "$dir"
sudo chown -Rh "$USER" "$dir"

# Skip programs that are specific to powerful multi-core VMs.
if ! _koopa_is_powerful
then
    flags+=("--exclude=bcbio")
    flags+=("--exclude=cellranger")
    flags+=("--exclude=cellranger-atac")
    flags+=("--exclude=omicsoft")
    flags+=("--exclude=rnaeditingindexer")
fi

_koopa_note "Using flags: ${flags[*]}"

# shellcheck disable=SC2068
rsync ${flags[@]} \
    --rsync-path="sudo /usr/bin/rsync" \
    "${source_user}@${source_ip}:${dir}/" \
    "${dir}/"

_koopa_h2 "Setting permissions on '${dir}'."
_koopa_set_permissions "$dir"

# /usr/local  {{{1
# ==============================================================================

dir="/usr/local"

_koopa_h2 "Updating '${dir}' from '${source_ip}'."

sudo mkdir -pv "$dir"
sudo chown -Rh "$USER" "$dir"

flags=("${flags_bak[@]}")

_koopa_note "Using flags: ${flags[*]}"

# shellcheck disable=SC2068
rsync ${flags[@]} \
    --rsync-path="sudo /usr/bin/rsync" \
    "${source_user}@${source_ip}:${dir}/" \
    "${dir}/"

_koopa_h2 "Setting permissions on '${dir}'."
_koopa_set_permissions "$dir"

