#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# Potentially useful flags:
# > apk add --no-cache --virtual .build-dependencies
# """

name_fancy="Alpine base system"

_koopa_install_start "$name_fancy"

sudo apk update
sudo apk upgrade

packages=(
    .build-dependencies
    R
    R-dev
    R-doc
    autoconf
    bash
    build-base
    ca-certificates
    curl
    dpkg
    fish
    git
    sudo
    tcl
    wget
    zsh
)
sudo apk add \
    --no-cache \
    --virtual \
    "${packages[@]}"

# This is required for conda, but v4.8+ errors out for 'linux-musl' anyway.
# > install-glibc

_koopa_install_success "$name_fancy"
