#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_h1 "Installing CentOS base system."

# Install RHEL (and Fedora) base.
"${script_dir}/../../rhel/sbin/install-base" "$@"

# GDAL is currently failing to install from source.
# Note that gdal-devel isn't yet available on EPEL 8.
# > sudo dnf -y install gdal-devel
