#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_no_args "$@"

# https://wiki.debian.org/UnattendedUpgrades
# https://blog.confirm.ch/unattended-upgrades-in-debian/

# Default config:
# /etc/apt/apt.conf.d/50unattended-upgrades
# /etc/apt/apt.conf.d/20auto-upgrades

# Logs:
# /var/log/dpkg.log
# /var/log/unattended-upgrades/

_koopa_apt_install apt-listchanges unattended-upgrades

# The file '/etc/apt/apt.conf.d/20auto-upgrades' can be created manually or by
# running the following command as root:
sudo dpkg-reconfigure -plow unattended-upgrades

# Check status.
sudo unattended-upgrades -d
