#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
koopa::assert_has_no_args "$@"

# """
# https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt
#
# Required packages:
# - apt-transport-https
# - ca-certificates
# - curl
# - gnupg
# - lsb-release
#
# Automated script:
# > curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
# """

koopa::exit_if_installed az

name_fancy="Azure CLI"

koopa::install_start "$name_fancy"

koopa::apt_add_azure_cli_repo
koopa::apt_install azure-cli

koopa::install_success "$name_fancy"
