#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header debian)"

# Install Tmux terminal multiplexer.
# Modified 2019-06-18.

# > apt-cache search libevent

sudo apt-get -y install libevent-dev

source "${KOOPA_HOME}/system/include/install/tmux.sh"
