#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# LLVM (clang)
# https://apt.llvm.org/
#
# Note that regular llvm recipe currently installs version 6.
#
# The 'llvm.sh' install script contains the GPG signing keys.
# """

if [[ -n "${LLVM_CONFIG:-}" ]]
then
    _koopa_note "llvm-config detected: '${LLVM_CONFIG}'."
    exit 0
fi

_koopa_h1 "Installing LLVM via 'apt.llvm.org'."

_koopa_assert_has_no_args "$@"
_koopa_assert_has_no_envs
# Note that the 'llvm.sh' script will fail unless wget is installed.
_koopa_assert_is_installed wget

name="llvm"
tmp_dir="$(_koopa_tmp_dir)/${name}"

version="$(_koopa_variable "$name")"
major_version="$(_koopa_major_version "$version")"

# FIXME Download this script and break out the essential parts.
(
    _koopa_cd_tmp_dir "$tmp_dir"
    file="llvm.sh"
    url="https://apt.llvm.org/${file}"
    _koopa_download "$url"
    chmod +x "$file"
    sudo "./${file}" "$major_version"
)

rm -fr "$tmp_dir"

_koopa_success "Installation of ${name} ${version} was successful."
