#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# Set up using automated script.
url="https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh"
curl -s "$url" | sudo bash

sudo DEBIAN_FRONTEND=noninteractive \
    apt-get --no-install-recommends --yes install \
        git git-lfs

git lfs install
