#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# Install latest version of R from CRAN.
# - https://cran.r-project.org/bin/linux/debian/
# - https://cran.r-project.org/bin/linux/ubuntu/README.html
# """

r_exe="/usr/bin/R"
_koopa_exit_if_installed "$r_exe"

while (("$#"))
do
    case "$1" in
        --version=*)
            version="${1#*=}"
            shift 1
            ;;
        --version)
            version="$2"
            shift 2
            ;;
        *)
            _koopa_invalid_arg "$1"
            ;;
    esac
done

if [[ -z "${version:-}" ]]
then
    version="$(_koopa_variable r)"
fi

name_fancy="R CRAN ${version} binary package"
_koopa_install_start "$name_fancy"

# This ensures we're starting fresh with the correct apt repo.
sudo rm -frv \
    /etc/R \
    /etc/apt/sources.list.d/r.list \
    /usr/lib/R/etc

_koopa_apt_import_r_key
_koopa_apt_add_r_repo "$version"

# This is lighter than using 'r-base'.
pkgs=(
    r-base-core
    r-base-dev
)

_koopa_apt_install "${pkgs[@]}"
_koopa_update_r_config "$r_exe"

_koopa_install_success "$name_fancy"
