#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# https://wiki.winehq.org/Debian
#
# See also:
# - https://github.com/baztian/docker-wine/blob/master/Dockerfile
# - https://gist.github.com/cschiewek/246a244ba23da8b9f0e7b11a68bf3285
# - https://gist.github.com/paul-krohn/e45f96181b1cf5e536325d1bdee6c949
# """

_koopa_exit_if_installed wine

name_fancy="Wine"

_koopa_install_start "$name_fancy"

# Import WineHQ key and repo, required to install latest version.
_koopa_apt_import_wine_key
_koopa_apt_add_wine_repo

# Enable 32-bit packages.
sudo dpkg --add-architecture i386

# Old stable version: Use wine, wine32 here.
_koopa_apt_get install \
    winbind \
    x11-apps \
    xauth \
    xvfb

# Install latest stable version of Wine.
sudo DEBIAN_FRONTEND=noninteractive \
    apt-get --yes install \
        --install-recommends \
        winehq-stable

_koopa_install_success "$name_fancy"
