#!/usr/bin/env bash
set -Eeu -o pipefail

# Install Emacs text editor.
# Modified 2019-06-19.

# See also:
# - https://www.gnu.org/software/emacs/
# - https://github.com/emacs-mirror/emacs

# shellcheck source=/dev/null
source "${KOOPA_DIR}/system/include/os/debian/sudo.sh"

name="emacs"
version="$(koopa variable "$name")"
prefix="${KOOPA_CELLAR_PREFIX}/${name}/${version}"
tmp_dir="${KOOPA_TMP_DIR}/${name}"
exe_file="${prefix}/bin/${name}"

printf "Installing %s %s.\n" "$name" "$version"

# Bioconductor AMI is missing these dependencies:
# > apt-cache search libgif
# > apt-cache search gnutls
# > apt-cache search 'libgnutls.*-dev'

sudo apt-get -y install gnutls-bin libgnutls28-dev
sudo apt-get -y install libgif-dev

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    wget "http://ftp.gnu.org/gnu/emacs/emacs-${version}.tar.xz"
    tar -xJvf "emacs-${version}.tar.xz"
    cd "emacs-${version}" || exit 1
    ./configure --prefix="$prefix"
    make
    sudo make install
    rm -rf "$tmp_dir"
)

sudo ldconfig

command -v "$exe_file"
"$exe_file" --version
