#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

name="pandoc"
version="$(_koopa_variable "$name")"
tmp_dir="$(_koopa_tmp_dir)/${name}"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install Pandoc.

$(_koopa_help_args)

see also:
    - https://pandoc.org/installing.html
    - https://github.com/jgm/pandoc/releases

note:
    Bash script.
    Updated 2019-09-26.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="pandoc-${version}-1-amd64.deb"
    url="https://github.com/jgm/pandoc/releases/download/${version}/${file}"
    wget "$url"
    sudo dpkg -i "$file"
    rm -rf "$file"
)

"$name" --version
command -v "$name"
