#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
koopa::assert_has_no_args "$#"

name="pandoc"
version="$(koopa::variable "$name")"
tmp_dir="$(koopa::tmp_dir)"

(
    koopa::cd_tmp_dir "$tmp_dir"
    file="pandoc-${version}-1-amd64.deb"
    url="https://github.com/jgm/pandoc/releases/download/${version}/${file}"
    koopa::download "$url"
    sudo dpkg -i "$file"
    rm -rf "$file"
)

"$name" --version
command -v "$name"
