#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# Check package source:
# https://packages.ubuntu.com/
#
#
# How to replicate installed packages across machines:
# https://serverfault.com/questions/56848
#
# To backup:
# > sudo dpkg --get-selections > /tmp/dpkglist.txt
#
# To Restore:
# > sudo dpkg --set-selections < /tmp/dpkglist.txt
# > sudo apt-get -y update
# > sudo apt-get dselect-upgrade
#
#
# Installing R using 'install-r' script instead, which sets up apt to support
# newer official release from CRAN.
#
#
# Enable Debian sources.
# To use 'build-dep', you must uncomment deb-src lines:
# > sudo vim /etc/apt/sources.list
#
# Otherwise you'll hit this error:
# You must put some 'source' URIs in your sources.list
#
# See also:
# https://askubuntu.com/questions/496549
#
#
# Clean up previous packages:
# - openjdk-12-jdk
# - openjdk-12-jre
# - python
#
#
# Bioconductor AMI is missing these dependencies:
# > apt-cache search 'libgnutls.*-dev'
# > apt-cache search gnutls
# > apt-cache search libgif
#
#
# libcurl4-dev madness:
# Package libcurl-dev is a virtual package provided by:
#   libcurl4-openssl-dev 7.58.0-2ubuntu3.8
#   libcurl4-nss-dev 7.58.0-2ubuntu3.8
#   libcurl4-gnutls-dev 7.58.0-2ubuntu3.8
# You should explicitly select one to install.
#
#
# Note that 'golang-go' is not officially supported.
# """

all=0
dev=0
dist_upgrade=0
extra=0

while (("$#"))
do
    case "$1" in
        --all)
            all=1
            shift 1
            ;;
        --dev)
            dev=1
            shift 1
            ;;
        --dist_upgrade)
            dist_upgrade=1
            shift 1
            ;;
        --extra)
            extra=1
            shift 1
            ;;
        *)
            _koopa_invalid_arg "$1"
            ;;
    esac
done

if [[ "$all" -eq 1 ]]
then
    dev=1
    dist_upgrade=1
    extra=1
fi

_koopa_h1 "Installing Debian base system."

_koopa_assert_is_installed sed sudo

export DEBIAN_FRONTEND="noninteractive"

# Debian symlinks '/usr/local/man' to '/usr/local/share/man' by default, which
# is non-standard and can cause cellar link script to break.
if [[ -L /usr/local/man ]]
then
    sudo rm -v /usr/local/man
fi

# GPG keys are required for signed repos in '/etc/apt/sources.list.d'.
_koopa_apt_import_keys

# Note that this function calls 'apt-get update'.
_koopa_apt_link_sources
enabled_repos="$(_koopa_apt_enabled_repos)"

# dist-upgrade                                                           #  {{{1
# ==============================================================================

if [[ "$dist_upgrade" -eq 1 ]]
then
    _koopa_h2 "Upgrading install via 'apt-get dist-upgrade'."
    sudo DEBIAN_FRONTEND=noninteractive \
        apt-get \
            --fix-missing \
            --no-install-recommends \
            --quiet \
            --yes \
            dist-upgrade
fi

# default                                                                 # {{{1
# ==============================================================================

_koopa_h2 "Installing default packages."

# Clean up previous installs first, if applicable.
apt_installed="$(sudo apt list --installed 2> /dev/null)"
legacy_pkgs=(
    containerd          # docker-legacy
    docker              # docker-legacy
    docker-engine       # docker-legacy
    docker.io           # docker-legacy
    runc                # docker-legacy
    cargo               # universe; use 'install-rust'
    fish                # universe; use 'install-fish'
    libgdal-dev         # universe; use 'install-gdal'
    libgeos-dev         # universe; use 'install-geos'
    libgsl-dev          # universe; use 'install-gsl'
    libhdf5-dev         # universe; use 'install-hdf5'
)
for pkg in "${legacy_pkgs[@]}"
do
    echo "$apt_installed" | grep -Eq "^${pkg}/" || continue
    sudo apt-get --yes remove "${pkg[@]}"
done

                                          # |   w/o deps |    w/ deps | n deps |
pkgs=(                                    # | ---------- | ---------- | ------ |
    apt-listchanges                       # |         NA |         NA |     NA |
    apt-utils                             # |         NA |         NA |     NA |
    autoconf                              # |         NA |         NA |     NA |
    automake                              # |         NA |         NA |     NA |
    bc                                    # |         NA |         NA |     NA |
    ca-certificates                       # |         NA |         NA |     NA |
    cmake                                 # |         NA |         NA |     NA |
    coreutils                             # |         NA |         NA |     NA |
    curl                                  # |     < 1 MB |     < 1 MB |      3 |
    dirmngr                               # |     < 1 MB |       4 MB |     10 |
    findutils                             # |         NA |         NA |     NA |
    gcc                                   # |         NA |         NA |     NA |
    gdb                                   # |       9 MB |      51 MB |      5 |
    gfortran                              # |     < 1 MB |     < 1 MB |      2 |
    git                                   # |      32 MB |      34 MB |      3 |
    gnupg                                 # |     < 1 MB |       2 MB |      8 |
    gpg-agent                             # |     < 1 MB |       4 MB |     12 |
    htop                                  # |     < 1 MB |     < 1 MB |      2 |
    less                                  # |     < 1 MB |     < 1 MB |      2 |
    lsb-release                           # |         NA |         NA |     NA |
    nano                                  # |     < 1 MB |     < 1 MB |      1 |
    pkg-config                            # |         NA |         NA |     NA |
    software-properties-common            # |         NA |         NA |     NA |
    sudo                                  # |         NA |         NA |     NA |
    tmux                                  # |     < 1 MB |       2 MB |      6 |
    tzdata                                # |         NA |         NA |     NA |
    vim                                   # |       3 MB |      32 MB |      3 |
    wget                                  # |     < 1 MB |       1 MB |      3 |
)

if _koopa_is_matching_fixed "universe" "$enabled_repos"
then
    pkgs+=(
        apt-transport-https
        gdebi-core
        parallel
        tree
    )
fi

# developer                                                                 {{{1
# ==============================================================================

# Note that we want these on our Bioconductor Docker images.
if [[ "$dev" -eq 1 ]]
then
    _koopa_h2 "Installing developer libraries."
                                          # |   w/o deps |    w/ deps | n deps |
    pkgs+=(                               # | ---------- | ---------- | ------ |
        gettext
        libacl1-dev                       # |     < 1 MB |     < 1 MB |      1 |
        libbz2-dev                        # |     < 1 MB |      36 MB |     22 |
        libcairo2-dev                     # |       3 MB |      94 MB |     61 |
        libcurl4-gnutls-dev
        libevent-dev                      # |       2 MB |       2 MB |      5 |
        libffi-dev                        # |     < 1 MB |     227 MB |     10 |
        libfreetype6-dev                  # |       7 MB |      97 MB |     62 |
        libgif-dev                        # |     < 1 MB |     287 MB |     69 |
        libglu1-mesa-dev                  # |     < 1 MB |       1 MB |      2 |
        libgnutls28-dev                   # |       4 MB |       8 MB |      9 |
        libharfbuzz-dev                   # |       2 MB |     436 MB |    140 |
        liblzma-dev                       # |     < 1 MB |     337 MB |     96 |
        libmagick++-dev                   # |     < 1 MB |      36 MB |     20 |
        libncurses-dev # libncurses5-dev  # |       1 MB |       1 MB |      2 |
        libpng-dev                        # |     < 1 MB |     400 MB |    138 |
        libssl-dev                        # |       8 MB |     294 MB |     69 |
        libtool                           # |       1 MB |      21 MB |     22 |
        libtool-bin                       # |     < 1 MB |     < 1 MB |      1 |
        libx11-dev                        # |       2 MB |     109 MB |    107 |
        libxml2-dev                       # |       4 MB |     330 MB |     93 |
        libz-dev # zlib1g-dev             # |     < 1 MB |         NA |    174 |
    )

    if _koopa_is_matching_fixed "universe" "$enabled_repos"
    then
        pkgs+=(
            tcl-dev
        )
    fi
fi

# extra                                                                     {{{1
# ==============================================================================

if [[ "$extra" -eq 1 ]]
then
    _koopa_h2 "Installing extra recommended packages."
                                          # |   w/o deps |    w/ deps | n deps |
    pkgs+=(                               # | ---------- | ---------- | ------ |
        emacs                             # |       8 MB |     112 MB |     11 |
        firefox                           # |     202 MB |     203 MB |      9 |
        keyboard-configuration            # |       3 MB |      35 MB |     44 |
        perl                              # |     < 1 MB |     987 MB |    281 |
        sqlite3                           # |       2 MB |       2 MB |      1 |
        systemd                           # |         NA |         NA |     NA |
        unattended-upgrades               # |     < 1 MB |     < 1 MB |      1 |
        xorg                              # |     < 1 MB |      30 MB |     39 |
        zsh                               # |       2 MB |      15 MB |      2 |
    )

    if _koopa_is_matching_fixed "universe" "$enabled_repos"
    then
        pkgs+=(
            alien
            gnutls-bin
            gtk-doc-tools
            libgtk-3-0
            libgtk-3-dev
            libgtk2.0-0
            libgtk2.0-dev
            libmariadb-dev
            libopenblas-base
            libopenblas-dev
            libssh2-1-dev
            libudunits2-dev
            libv8-dev
            pandoc
            pandoc-citeproc
            pass
            texlive
        )
    fi
fi

sudo DEBIAN_FRONTEND=noninteractive \
    apt-get \
        --fix-missing \
        --no-install-recommends \
        --quiet \
        --yes \
        install "${pkgs[@]}"

# clean up                                                                  {{{1
# ==============================================================================

_koopa_h2 "Removing unused packages via 'apt-get autoremove'."
sudo apt-get --yes autoremove

_koopa_h2 "Removing caches."
sudo rm -fr /root/.cache/*
sudo rm -fr /var/lib/apt/lists/*
