#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header debian)"

# Install Tmux terminal multiplexer.
# Modified 2019-06-18.

# > apt-cache search libevent

if _koopa_has_sudo
then
    sudo apt-get -y install libevent-dev
fi

source "$(koopa cellar-script tmux)"

