#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_koopa_assert_has_no_args "$@"


if ! _koopa_is_installed cpanm
then
    sudo apt-get -y install cpanminus
fi

sudo cpanm File::Rename

# Alternate method:
# > perl -MCPAN -e 'install File::Rename'

command -v rename
rename --version
