#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(_koopa_header debian)"

# Install Oracle Java 12.
# Updated 2019-06-25.

_koopa_assert_has_sudo

sudo add-apt-repository ppa:linuxuprising/java
sudo apt-get update

# This step prompts like crazy.
sudo apt-get -y install oracle-java12-installer

sudo apt-get install oracle-java12-set-default

# Uninstall Java 12.
# > sudo apt-get remove oracle-java12-installer

# Delete repository in `etc/apt/sources.list.d`.

java --version
command -v java
