#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# LLVM (clang)
# https://apt.llvm.org/
#
# Automatic script:
# https://apt.llvm.org/llvm.sh
# The 'llvm.sh' install script contains the GPG signing keys.
#
# Note that default llvm recipe currently installs version 6.
# """

reinstall=0

pos=()
while (("$#"))
do
    case "$1" in
        --reinstall)
            reinstall=1
            shift 1
            ;;
        --)
            shift 1
            break
            ;;
        --*|-*)
            _koopa_invalid_arg "$1"
            ;;
        *)
            pos+=("$1")
            shift 1
            ;;
    esac
done
if [[ "${#pos[@]}" -gt 0 ]]
then
    set -- "${pos[@]}"
fi

if [[ "$reinstall" -eq 1 ]]
then
    uninstall-llvm
fi

name="llvm"
version="$(_koopa_variable "$name")"
major_version="$(_koopa_major_version "$version")"

name_fancy="LLVM ${major_version}"

# Check if LLVM installation is current, or whether we need to update.
if [[ -n "${LLVM_CONFIG:-}" ]]
then
    current_version="$(_koopa_get_version "$LLVM_CONFIG")"
    current_major_version="$(_koopa_major_version "$current_version")"
    if [[ "$current_major_version" == "$major_version" ]]
    then
        _koopa_note "${name_fancy} is installed."
        exit 0
    else
        _koopa_dl "LLVM config" "$LLVM_CONFIG"
        uninstall-llvm
    fi
fi

_koopa_install_start "$name_fancy"

_koopa_assert_has_no_args "$@"
_koopa_assert_has_no_envs

_koopa_apt_add_llvm_repo

pkgs=(
    "clang-${major_version}"
    "clangd-${major_version}"
    "lld-${major_version}"
    "lldb-${major_version}"
)
_koopa_apt_install "${pkgs[@]}"

_koopa_install_success "$name_fancy"
