#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install Oracle Java 12.

$(_koopa_help_args)

note:
    Bash script.
    Updated 2019-09-26.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

sudo add-apt-repository ppa:linuxuprising/java
sudo apt-get update

# This step prompts like crazy.
sudo apt-get -y install oracle-java12-installer

sudo apt-get install oracle-java12-set-default

# Uninstall Java 12.
# > sudo apt-get remove oracle-java12-installer

# Delete repository in '/etc/apt/sources.list.d'.

java --version
command -v java
