#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt
#
# Required packages:
# - apt-transport-https
# - ca-certificates
# - curl
# - gnupg
# - lsb-release
#
# Automated script:
# > curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
# """

_koopa_exit_if_installed az

_koopa_h1 "Installing Microsoft Azure CLI."

_koopa_apt_import_azure_cli_key
_koopa_apt_add_azure_cli_repo

sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive \
    apt-get \
        --fix-missing \
        --no-install-recommends \
        --quiet \
        --yes \
        install azure-cli

# > az login

_koopa_success "Installation of Azure CLI was successful."
