#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

name="rstudio-server"
version="$(_koopa_variable "$name")"
tmp_dir="$(_koopa_tmp_dir)/${name}"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install RStudio Server.

$(_koopa_help_args)

see also:
    https://www.rstudio.com/products/rstudio/download-server/

note:
    Bash script.
    Updated 2019-09-26.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

printf "Installing %s %s.\n" "$name" "$version"

# Note that R is already configured on Bioconductor image.
sudo apt-get -y install r-base

# Ubuntu 18+ instructions.
sudo apt-get -y install gdebi-core

file="rstudio-server-${version}-amd64.deb"
url="https://download2.rstudio.org/server/bionic/amd64/${file}"

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    wget "$url"
    sudo gdebi --non-interactive "$file"
    rm -rf "$tmp_dir"
)

command -v "$name"
"$name" version
"$name" status
