#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# Install latest version of R.
# - https://cran.r-project.org/bin/linux/debian/
# - https://cran.r-project.org/bin/linux/ubuntu/README.html
# """

_koopa_exit_if_installed R
_koopa_assert_is_file "/etc/apt/sources.list.d/r.list"

# Import key used to sign R release.
# Refer to 'Secure apt' section for details.
if _koopa_is_ubuntu
then
    # Release is signed by Michael Rutter <marutter@gmail.com>.
    sudo apt-key adv \
        --keyserver keyserver.ubuntu.com \
        --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
else
    # Release is signed by Johannes Ranke <jranke@uni-bremen.de>.
    sudo apt-key adv \
        --keyserver keys.gnupg.net \
        --recv-key E19F5F87128899B192B1A2C2AD5F960A256A04AF
fi

sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive \
    apt-get \
        --no-install-recommends \
        --quiet \
        --yes \
        install \
            r-base \
            r-base-dev

_koopa_link_r_etc
_koopa_link_r_site_library

# Avoid write failure to 'doc/' here upon package update.
_koopa_set_permissions /usr/share/R
