#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_koopa_assert_has_no_args "$@"

# Clean up previous:
# - openjdk-12-jdk
# - openjdk-12-jre
# - python

# Bioconductor AMI is missing these dependencies:
# > apt-cache search 'libgnutls.*-dev'
# > apt-cache search gnutls
# > apt-cache search libgif

sudo apt update
sudo apt -y dist-upgrade
sudo apt -y install \
    autoconf \
    automake \
    cargo \
    cmake \
    emacs \
    fish \
    git \
    gnupg2 \
    gnutls-bin \
    gtk-doc-tools \
    htop \
    libacl1 \
    libacl1-dev \
    libbz2-dev \
    libcairo2-dev \
    libcurl4-openssl-dev \
    libevent-dev \
    libfreetype6-dev \
    libgdal-dev \
    libgif-dev \
    libglu1-mesa-dev \
    libgnutls28-dev \
    libgsl-dev \
    libharfbuzz-dev \
    libhdf5-dev \
    liblzma-dev \
    libmagick++-dev \
    libmariadb-client-lgpl-dev \
    libpng-dev \
    libssh2-1-dev \
    libssl-dev \
    libtool \
    libudunits2-dev \
    libv8-dev \
    libx11-dev \
    libxml2-dev \
    libz-dev \
    pandoc \
    pandoc-citeproc \
    perl \
    pkg-config \
    python3 \
    python3-pip \
    r-base \
    r-base-dev \
    texlive \
    tmux \
    vim \
    xorg \
    zsh

# To use 'build-dep', you must uncomment deb-src lines:
# > sudo vim /etc/apt/sources.list
# Otherwise you'll hit this error:
# You must put some 'source' URIs in your sources.list
# https://askubuntu.com/questions/496549

# > sudo apt -y build-dep \
# >     bash \
# >     coreutils \
# >     emacs \
# >     fish \
# >     htop \
# >     tmux \
# >     vim \
# >     zsh

