#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

url="https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh"
curl -s "$url" | sudo bash
sudo apt-get -y install git git-lfs
git lfs install
