#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# Currently supports overlay2, aufs and btrfs storage drivers.
#
# See also:
# - https://docs.docker.com/install/linux/docker-ce/debian/
# - https://docs.docker.com/install/linux/docker-ce/ubuntu/
#
# Configures at '/var/lib/docker/'.
# """

_koopa_exit_if_docker
_koopa_exit_if_installed docker
_koopa_assert_has_no_args "$@"
_koopa_assert_is_file "/etc/apt/sources.list.d/docker.list"

# Expecting "debian" or "ubuntu" here.
os_id="$(_koopa_os_id)"

# Remove legacy versions, if necessary.
sudo apt-get --yes remove \
    containerd \
    docker \
    docker-engine \
    docker.io \
    runc

# Install packages to allow apt to use a repository over HTTPS.
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive \
    apt-get \
        --no-install-recommends \
        --quiet \
        --yes \
        install \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common

# Add Docker's official GPG key.
curl -fsSL "https://download.docker.com/linux/${os_id}/gpg" \
    | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88

# Ready to install Docker.
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive \
    apt-get \
        --no-install-recommends \
        --quiet \
        --yes \
        install \
            containerd.io \
            docker-ce \
            docker-ce-cli

# Ensure current user is added to Docker group.
sudo usermod -aG docker "$USER"

_koopa_link_docker

_koopa_success "Installation of Docker was successful."
