#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# https://rstudio.com/products/rstudio/download-commercial/
# """

reinstall=0
pos=()
while (("$#"))
do
    case "$1" in
        --reinstall)
            reinstall=1
            shift 1
            ;;
        --)
            shift 1
            break
            ;;
        --*|-*)
            koopa::invalid_arg "$1"
            ;;
        *)
            pos+=("$1")
            shift 1
            ;;
    esac
done
[[ "${#pos[@]}" -gt 0 ]] && set -- "${pos[@]}"

name="rstudio-server-pro"
version="$(koopa::variable "$name")"
name_fancy="RStudio Server Pro ${version}"

if ! koopa::is_current_version rstudio-server
then
    reinstall=1
fi

if [[ "$reinstall" -eq 0 ]]
then
    koopa::exit_if_installed rstudio-server
fi

koopa::install_start "$name_fancy"

koopa::assert_has_no_args "$#"
koopa::assert_is_installed R gdebi

os_codename="$(koopa::os_codename)"

case "$os_codename" in
    # Debian 10
    buster)
        os_codename="bionic"
        ;;
    # Ubuntu 20.04 LTS
    focal)
        os_codename="bionic"
        ;;
    # Ubuntu 18.04 LTS
    bionic)
        ;;
    *)
        koopa::stop "Unsupported OS version: '${os_codename}'."
        ;;
esac

tmp_dir="$(koopa::tmp_dir)"

(
    koopa::cd "$tmp_dir"
    file="rstudio-server-pro-${version}-amd64.deb"
    url="https://download2.rstudio.org/server/${os_codename}/amd64/${file}"
    koopa::download "$url"
    sudo gdebi --non-interactive "$file"
) 2>&1 | tee "$(koopa::tmp_log_file)"

rm -fr "$tmp_dir"

koopa::install_success "$name_fancy"

cat << END
Activate product license key (if necessary):
> sudo rstudio-server license-manager activate <product-key>

If you want to move your license of RStudio Server to another system you should
first deactivate it on the old system with the command:
> sudo rstudio-server license-manager deactivate
END
