#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# LLVM (clang)
# https://apt.llvm.org/
#
# Automatic script:
# https://apt.llvm.org/llvm.sh
# The 'llvm.sh' install script contains the GPG signing keys.
#
# Note that default llvm recipe currently installs version 6.
# """

if [[ -n "${LLVM_CONFIG:-}" ]]
then
    _koopa_note "llvm-config detected: '${LLVM_CONFIG}'."
    exit 0
fi

_koopa_h1 "Installing LLVM."

_koopa_assert_has_no_args "$@"
_koopa_assert_has_no_envs

_koopa_apt_import_llvm_key
_koopa_apt_add_llvm_repo

name="llvm"
version="$(_koopa_variable "$name")"
major_version="$(_koopa_major_version "$version")"

sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive \
    apt-get \
        --fix-missing \
        --no-install-recommends \
        --quiet \
        --yes \
        install \
            "clang-${major_version}" \
            "clangd-${major_version}" \
            "lld-${major_version}" \
            "lldb-${major_version}"

_koopa_success "Installation of ${name} ${version} was successful."
