#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# https://rstudio.com/products/rstudio/download-commercial/
# """

reinstall=0
pos=()
while (("$#"))
do
    case "$1" in
        --reinstall)
            reinstall=1
            shift 1
            ;;
        --)
            shift 1
            break
            ;;
        --*|-*)
            _koopa_invalid_arg "$1"
            ;;
        *)
            pos+=("$1")
            shift 1
            ;;
    esac
done
if [[ "${#pos[@]}" -gt 0 ]]
then
    set -- "${pos[@]}"
fi

name="rstudio-server-pro"
version="$(_koopa_variable "$name")"
name_fancy="RStudio Server Pro ${version}"

if ! _koopa_is_current_version rstudio-server
then
    reinstall=1
fi

if [[ "$reinstall" -eq 0 ]]
then
    _koopa_exit_if_installed rstudio-server
fi

_koopa_install_start "$name_fancy"

_koopa_assert_has_no_args "$@"
_koopa_assert_is_installed R gdebi

os_codename="$(_koopa_os_codename)"

case "$os_codename" in
    # Debian 10
    buster)
        os_codename="bionic"
        ;;
    # Ubuntu 20.04 LTS
    focal)
        os_codename="bionic"
        ;;
    # Ubuntu 18.04 LTS
    bionic)
        ;;
    *)
        _koopa_stop "Unsupported OS version: '${os_codename}'."
        ;;
esac

tmp_dir="$(_koopa_tmp_dir)"

(
    _koopa_cd_tmp_dir "$tmp_dir"
    file="rstudio-server-pro-${version}-amd64.deb"
    url="https://download2.rstudio.org/server/${os_codename}/amd64/${file}"
    _koopa_download "$url"
    sudo gdebi --non-interactive "$file"
) 2>&1 | tee "$(_koopa_tmp_log_file)"

rm -fr "$tmp_dir"

_koopa_install_success "$name_fancy"

cat << EOF
Activate product license key (if necessary):
> sudo rstudio-server license-manager activate <product-key>

If you want to move your license of RStudio Server to another system you should
first deactivate it on the old system with the command:
> sudo rstudio-server license-manager deactivate
EOF
