#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header debian)"

# Install Vim.
# Modified 2019-06-23.

sudo apt-get -y install vim
sudo apt-get -y build-dep vim

source "$(koopa cellar-script vim)"
