#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_no_args "$@"
_koopa_assert_is_installed R gdebi
_koopa_assert_is_not_installed rstudio-server

name="rstudio-server"
version="$(_koopa_variable "$name")"
tmp_dir="$(_koopa_tmp_dir)/${name}"
os_codename="$(_koopa_os_codename)"

if ! _koopa_is_ubuntu
then
    case "$os_codename" in
        buster)
            os_codename="bionic"
            ;;
    esac
fi

if [[ "$os_codename" != "bionic" ]]
then
    _koopa_stop "Unsupported OS version: '${os_codename}'."
fi

_koopa_message "Installing ${name} ${version}."

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="rstudio-server-${version}-amd64.deb"
    url="https://download2.rstudio.org/server/bionic/amd64/${file}"
    _koopa_download "$url"
    sudo gdebi --non-interactive "$file"
    rm -rf "$tmp_dir"
)

command -v "$name"
"$name" version
"$name" status
