#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# RStudio Server on Fedora / Ubuntu.
# https://rstudio.com/products/rstudio/download-server/debian-ubuntu/
#
# System config:
# /etc/rstudio
#
# Verify install:
# > sudo rstudio-server stop
# > sudo rstudio-server verify-installation
# > sudo rstudio-server start
# > sudo rstudio-server status
# """

name="rstudio-server"

# > _koopa_exit_if_docker
_koopa_exit_if_installed "$name"
_koopa_assert_has_no_args "$@"
_koopa_assert_is_installed R gdebi

version="$(_koopa_variable "$name")"
os_codename="$(_koopa_os_codename)"

if ! _koopa_is_ubuntu
then
    case "$os_codename" in
        buster)
            os_codename="bionic"
            ;;
    esac
fi

if [[ "$os_codename" != "bionic" ]]
then
    _koopa_stop "Unsupported OS version: '${os_codename}'."
fi

name_fancy="RStudio Server"

_koopa_install_start "$name_fancy"

tmp_dir="$(_koopa_tmp_dir)"

(
    _koopa_cd_tmp_dir "$tmp_dir"
    file="rstudio-server-${version}-amd64.deb"
    url="https://download2.rstudio.org/server/bionic/amd64/${file}"
    _koopa_download "$url"
    sudo gdebi --non-interactive "$file"
) 2>&1 | tee "$(_koopa_tmp_log_file)"

rm -fr "$tmp_dir"

_koopa_install_success "$name_fancy"
