#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header debian)"

# Install Emacs text editor.
# Modified 2019-06-23.

# Bioconductor AMI is missing these dependencies:
# > apt-cache search libgif
# > apt-cache search gnutls
# > apt-cache search 'libgnutls.*-dev'

sudo apt-get -y install gnutls-bin libgnutls28-dev
sudo apt-get -y install libgif-dev

source "${KOOPA_HOME}/system/include/install/emacs.sh"
