#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header debian)"

# Install Oracle Java 12.
# Modified 2019-06-23.

sudo add-apt-repository ppa:linuxuprising/java
sudo apt-get update

# This step prompts like crazy.
sudo apt-get -y install oracle-java12-installer

sudo apt-get install oracle-java12-set-default

# Uninstall Java 12.
# > sudo apt-get remove oracle-java12-installer

java --version
command -v java
