#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

name_fancy="LLVM"

koopa::uninstall_start "$name_fancy"

koopa::assert_has_no_args "$#"
koopa::assert_has_no_envs

unset -v LLVM_CONFIG

sudo apt-get --yes remove '^clang-[0-9]+.*' '^llvm-[0-9]+.*'
sudo apt-get --yes autoremove

sudo rm -f /etc/apt/sources.list.d/llvm.list

koopa::uninstall_success "$name_fancy"
