#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

name_fancy="R CRAN binary"

koopa::uninstall_start "$name_fancy"

koopa::assert_has_no_args "$@"
koopa::assert_has_no_envs

sudo rm -frv \
    /etc/R \
    /usr/lib/R/etc

koopa::apt_remove 'r-*'

koopa::uninstall_success "$name_fancy"
