#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(koopa header debian)"

# Update Debian.
# Updated 2019-06-23.

_koopa_assert_has_sudo

sudo apt-get update
sudo apt-get -y dist-upgrade
