#!/usr/bin/env bash
set -Eeu -o pipefail

# Enable EPEL repository.
# Modified 2019-06-18.

# See also:
# - https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/

# shellcheck source=/dev/null
source "${KOOPA_DIR}/os/fedora/include/sudo.sh"

sudo yum reinstall -y \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo yum-config-manager --enable epel
sudo yum repolist
