#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header fedora)"

# Enable EPEL repository.
# Modified 2019-06-23.

# See also:
# - https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/

sudo yum reinstall -y \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo yum-config-manager --enable epel
sudo yum repolist
