#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header fedora)"

# Enable EPEL repository.
# Modified 2019-07-09.

# See also:
# - https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/

_koopa_assert_has_sudo

sudo yum install -y \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

sudo yum-config-manager --enable epel
# > sudo yum-config-manager --disable epel

sudo yum repolist
