#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# https://cloud.google.com/sdk/docs/downloads-yum
# """

_koopa_exit_if_installed gcloud

name_fancy="Google Cloud SDK"

_koopa_install_start "$name_fancy"

_koopa_yum_add_google_cloud_sdk_repo
sudo yum -y install google-cloud-sdk

_koopa_install_success "$name_fancy"
