#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header fedora)"

# Install Docker Community Edition.
# Modified 2019-07-11.

# See also:
# - https://docs.docker.com/install/linux/docker-ce/centos/

_koopa_assert_has_sudo
os_type="$(koopa os-type)"

sudo yum -y remove \
    docker \
    docker-client \
    docker-client-latest \
    docker-common \
    docker-engine \
    docker-latest \
    docker-latest-logrotate \
    docker-logrotate

sudo yum -y install \
    device-mapper-persistent-data \
    lvm2 \
    yum-utils

sudo yum-config-manager \
    --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum repolist

sudo yum install -y containerd.io

if [[ "os_type" == "rhel8" ]]
then
    # RHEL8 requires `--nobest` flag to ignore containerd.io conflict.
    sudo yum -y install --nobest docker-ce docker-ce-cli
else
    sudo yum -y install docker-ce docker-ce-cli
fi

sudo groupadd docker
sudo service docker restart
sudo gpasswd -a "$USER" docker
newgrp docker

docker --version
command -v docker
