#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header fedora)"

# Install Perl rename.
# Modified 2019-06-23.

# This variant is superior to util-linux rename.

sudo yum install -y perl-App-cpanminus
sudo cpanm File::Rename

# Alternate method:
# perl -MCPAN -e 'install File::Rename'

command -v rename
rename --version
