#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum
# """

_koopa_exit_if_installed az

name_fancy="Azure CLI"

_koopa_install_start "$name_fancy"

_koopa_yum_import_azure_cli_key
_koopa_yum_add_azure_cli_repo

sudo yum -y install azure-cli

_koopa_install_success "$name_fancy"
