#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(koopa header fedora)"
_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

name="rstudio-server"
tmp_dir="$(_koopa_tmp_dir)/${name}-pro"
version="$(_koopa_variable "${name}-pro")"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install RStudio Server Pro.

$(_koopa_help_args)

details:
    Note that this is also referred to as "Commercial RStudio".

see also:
    https://www.rstudio.com/products/rstudio/download-commercial/

note:
    Bash script.
    Updated 2019-09-26.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

printf "Installing %s %s.\n" "$name" "$version"

# Remove existing config files.
# > sudo rm -frv /etc/rstudio

(
    rm -fr "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="${name}-rhel-${version}-x86_64.rpm"
    url="https://download2.rstudio.org/server/centos6/x86_64/${file}"
    wget "$url"
    sudo yum -y install "$file"
    rm -fr "$tmp_dir"
)

sudo "$name" stop
sudo "$name" verify-installation
sudo "$name" start
sudo "$name" status
sudo "$name" license-manager status

command -v "$name"
"$name" version

# Activate product license key:
# > sudo rstudio-server license-manager activate <product-key>

# If you want to move your license of RStudio Server to another system you
# should first deactivate it on the old system with the command:
# > sudo rstudio-server license-manager deactivate
