#!/usr/bin/env bash
set -Eeu -o pipefail

# Install Git SCM.
# Modified 2019-06-20.

# See also:
# - https://git-scm.com/
# - https://github.com/git/git
# - https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
# - https://github.com/git/git/blob/master/INSTALL
# - https://github.com/progit/progit2/blob/master/book/01-introduction/sections/installing.asc

# This currently fails if OpenSSL v1.1.1+ is installed to `/usr/local`.
# Instead, compile Git to use the system OpenSSL in `/bin/`.

# shellcheck source=/dev/null
source "${KOOPA_DIR}/os/fedora/include/sudo.sh"

name="git"
version="$(koopa variable "$name")"
prefix="${KOOPA_CELLAR_PREFIX}/${name}/${version}"
tmp_dir="${KOOPA_TMP_DIR}/${name}"
build_name="$KOOPA_OS_BUILD_STRING"
exe_file="${prefix}/bin/${name}"

printf "Installing %s %s.\n" "$name" "$version"

# Install build dependencies.
sudo yum install -y "$name"
sudo yum-builddep -y "$name"

# This is required for git to make doc cleanly.
#
# Otherwise, you'll see this error:
# /bin/sh: line 1: docbook2x-texi: command not found
#
# This issue is reference here:
# https://github.com/progit/progit2/issues/425
#
# Note the capital "X" here. This differs depending on the Linux distro.
# We're assuming Red Hat here.
#
# EPEL7 must be enabled for this to install (e.g. on Amazon Linux 2).
sudo yum install -y docbook2X

# This step is required to fix a binary name difference.
if [[ ! -f /usr/bin/docbook2x-texi ]]
then
    sudo ln -s /usr/bin/db2x_docbook2texi /usr/bin/docbook2x-texi
fi

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    wget "https://github.com/git/git/archive/v${version}.tar.gz"
    tar -zxf "v${version}.tar.gz"
    cd "git-${version}" || exit 1
    # The compilation settings here are from the Git SCM book website.
    # Refer also to INSTALL file for details.
    make configure
    ./configure \
        --build="$build_name" \
        --prefix="$prefix" \
        --with-openssl="/bin/openssl"
    make all doc info
    sudo make install install-doc install-html install-info
    rm -rf "$tmp_dir"
)

link_cellar "$name" "$version"
sudo ldconfig

command -v "$exe_file"
"$exe_file" --version
