#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header fedora)"

# Install R.
# Modified 2019-06-23.

# See also:
# - https://www.r-project.org/
# - https://cran.r-project.org/doc/manuals/r-release/R-admin.html
# - https://community.rstudio.com/t/compiling-r-from-source-in-opt-r/14666
# - https://superuser.com/questions/841270/installing-r-on-rhel-7
# - https://github.com/rstudio/rmarkdown/issues/359
# - http://pj.freefaculty.org/blog/?p=315

name="R"
version="$(koopa variable "$name")"
prefix="$(koopa cellar-prefix)/${name}/${version}"
tmp_dir="$(koopa tmp-dir)/${name}"
build_os_string="$(koopa build-os-string)"
exe_file="${prefix}/bin/${name}"

major_version="$(echo "$version" | cut -d "." -f 1)"
# > minor_version="$(echo "$version" | cut -d "." -f 2-)"



# Java                                                                      {{{1
# ==============================================================================

printf "Updating Java.\n"

# yum currently installs java-1.8.0-openjdk-headless.x86_64.
# This breaks with `R CMD javareconf`.

sudo yum install -y java-latest-openjdk-devel
sudo yum list installed | grep -E '^java-'

command -v java
java -version

command -v javac
javac -version



# TeX                                                                       {{{1
# ==============================================================================

printf "Updating TeX.\n"

# Missing recommendations:
# - texlive-csvsimple
# - texlive-fonts-extra
# - texlive-inconsolata
# - texlive-marginfix
# - texlive-mathtools
# - texlive-nowidow
# - texlive-parnotes

sudo yum install -y \
    texlive \
    texlive-bera \
    texlive-collection-fontsrecommended \
    texlive-collection-latexrecommended \
    texlive-caption \
    texlive-changepage \
    texlive-enumitem \
    texlive-etoolbox \
    texlive-fancyhdr \
    texlive-footmisc \
    texlive-framed \
    texlive-geometry \
    texlive-hyperref \
    texlive-latex-fonts \
    texlive-natbib \
    texlive-parskip \
    texlive-pdftex \
    texlive-placeins \
    texlive-preprint \
    texlive-sectsty \
    texlive-soul \
    texlive-titlesec \
    texlive-titling \
    texlive-xstring

# Using TeX Live 2013, we'll see this warning:
#
#     configure: WARNING: neither inconsolata.sty nor zi4.sty found: PDF
#     vignettes and package manuals will not be rendered optimally
#
# There doesn't appear to be an easy way to fix this on RHEL 7.



# R                                                                         {{{1
# ==============================================================================

printf "Installing %s %s.\n" "$name" "$version"

sudo yum install -y "$name"
sudo yum-builddep -y "$name"

(
    # R will warn if R_HOME environment variable is set.
    unset -v R_HOME
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    wget "https://cran.r-project.org/src/base/R-${major_version}/R-${version}.tar.gz"
    tar -xzvf "R-${version}.tar.gz"
    cd "R-${version}" || exit 1
    ./configure \
        --build="$build_os_string" \
        --prefix="$prefix" \
        --enable-BLAS-shlib \
        --enable-R-profiling \
        --enable-R-shlib \
        --enable-memory-profiling \
        --with-blas \
        --with-cairo \
        --with-jpeglib \
        --with-lapack \
        --with-readline \
        --with-tcltk
    make
    # > make check
    sudo make install
    rm -rf "$tmp_dir"
)

link-cellar "$name" "$version"
_koopa_update_r_config

command -v "$exe_file"
"$exe_file" --version

"${prefix}/bin/Rscript" -e 'capabilities()'
