#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header fedora)"

# Install Git SCM.
# Modified 2019-06-23.

if _koopa_has_sudo
then
    sudo yum install -y git
    sudo yum-builddep -y git
fi

# This is required for `make doc` to run cleanly.
#
# Otherwise, you'll see this error:
# /bin/sh: line 1: docbook2x-texi: command not found
#
# This issue is reference here:
# https://github.com/progit/progit2/issues/425
#
# Note the capital "X" here. This differs depending on the Linux distro.
# We're assuming Red Hat here.
#
# EPEL7 must be enabled for this to install (e.g. on Amazon Linux 2).

if _koopa_has_sudo
then
    sudo yum install -y docbook2X
    if [[ ! -f /usr/bin/docbook2x-texi ]]
    then
        sudo ln -s /usr/bin/db2x_docbook2texi /usr/bin/docbook2x-texi
    fi
fi

source "$(koopa cellar-script git)"
