#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header fedora)"

# Install Vim.
# Modified 2019-06-23.

sudo yum install -y vim
sudo yum-builddep -y vim

source "${KOOPA_HOME}/system/include/install/vim.sh"
