#!/usr/bin/env bash
set -Eeu -o pipefail

# Install GNU Scientific Library (GSL).
# Modified 2019-06-18.

# See also:
# - https://www.gnu.org/software/gsl/

# shellcheck source=/dev/null
source "${KOOPA_DIR}/system/include/os/fedora/sudo.sh"

prefix="${KOOPA_BUILD_PREFIX}/gsl"
tmp_dir="${KOOPA_TMP_DIR}/gsl"
version="$(koopa variable gsl)"

printf "Installing GSL %s.\n" "$version"

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    wget "http://mirror.keystealth.org/gnu/gsl/gsl-${version}.tar.gz"
    tar xzvf "gsl-${version}.tar.gz"
    cd "gsl-${version}" || exit 1
    ./configure --prefix="$prefix"
    make
    make check
    sudo make install
    rm -rf "$tmp_dir"
)

sudo ldconfig

command -v gsl-config
gsl-config --version
