#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

name="rstudio-server"
tmp_dir="$(_koopa_tmp_dir)/${name}"
version="$(_koopa_variable "$name")"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install RStudio Server.

$(_koopa_help_args)

see also:
    https://www.rstudio.com/products/rstudio/download-server/

note:
    Bash script.
    Updated 2019-10-01.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

printf "Installing %s %s.\n" "$name" "$version"

# Remove existing config files.
# > sudo rm -frv /etc/rstudio

(
    rm -fr "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="${name}-rhel-${version}-x86_64.rpm"
    url="https://download2.rstudio.org/server/centos6/x86_64/${file}"
    wget "$url"
    sudo yum -y install "$file"
    rm -fr "$tmp_dir"
)

# > sudo "$name" stop
# > sudo "$name" verify-installation
# > sudo "$name" start
# > sudo "$name" status

command -v "$name"
"$name" version
