#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header fedora)"

# Install RStudio Server.
# Modified 2019-06-23.

# See also:
# - https://www.rstudio.com/products/rstudio/download-server/

name="rstudio-server"
tmp_dir="$(koopa tmp-dir)/${name}"
version="$(koopa variable "$name")"

printf "Installing %s %s.\n" "$name" "$version"

file="rstudio-server-rhel-${version}-x86_64.rpm"
url="https://download2.rstudio.org/server/centos6/x86_64/${file}"

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"
    wget "$url"
    sudo yum install -y "$file"
    rm -rf "$tmp_dir"
)

command -v "$name"
"$name" version
"$name" status
