#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(_koopa_header fedora)"

# Install Shiny Server.
# Updated 2019-06-25.

# See also:
# - https://www.rstudio.com/products/rstudio/download-server/

_koopa_assert_has_sudo

name="shiny-server"
tmp_dir="$(_koopa_tmp_dir)/${name}"
version="$(_koopa_variable "$name")"

printf "Installing %s %s.\n" "$name" "$version"

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    sudo su - -c "R -e \"install.packages('shiny', repos='https://cran.rstudio.com/')\""
    file="shiny-server-${version}-x86_64.rpm"
    url="https://download3.rstudio.org/centos6.3/x86_64/${file}"
    wget "$url"
    sudo yum install -y --nogpgcheck "$file"
    rm -rf "$tmp_dir"
)

command -v "$name"
"$name" --version
