#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# CentOS 8 conflict:
# Problem: problem with installed package coreutils-single-8.30-6.el8.x86_64
#   - package coreutils-8.30-6.el8.x86_64 conflicts with coreutils-single
#     provided by coreutils-single-8.30-6.el8.x86_64
#   - conflicting requests
# """

dev=1
extra=1
upgrade=1

_koopa_is_docker && extra=0

_koopa_h1 "Installing Fedora base system."

_koopa_assert_is_installed sudo

# Upgrade  {{{1
# ==============================================================================

if [[ "$upgrade" -eq 1 ]]
then
    _koopa_h2 "Upgrading install via 'yum update'."
    sudo yum -y update
fi

# Default  {{{1
# ==============================================================================

_koopa_h2 "Installing default packages."
pkgs=(
    autoconf
    bash
    bzip2
    cmake
    convmv
    cryptsetup
    curl
    findutils
    gcc
    gcc-c++
    gcc-gfortran
    git
    gnupg2
    gnutls
    libtool
    lua
    make
    man-db
    ncurses
    openssl
    qpdf
    readline
    squashfs-tools
    systemd
    tmux
    tree
    util-linux
    vim
    wget
    xmlto
    xz
    yum-utils
    zip
)
sudo yum -y install "${pkgs[@]}"

# Developer  {{{1
# ==============================================================================

if [[ "$dev" -eq 1 ]]
then
    _koopa_h2 "Installing developer libraries."
    sudo yum -y groupinstall "Development Tools"
    pkgs=(
        bzip2-devel
        gnutls-devel
        gsl-devel
        libcurl-devel
        libevent-devel
        libffi-devel
        libseccomp-devel
        libuuid-devel
        libxml2-devel
        llvm-devel
        mariadb-devel
        mpfr-devel
        openssl-devel
        pcre-devel
        postgresql-devel
        readline-devel
        unixODBC-devel
        xz-devel
    )
    sudo yum -y install "${pkgs[@]}"
fi

# Extra  {{{1
# ==============================================================================

if [[ "$extra" -eq 1 ]]
then
    _koopa_h2 "Installing extra recommended packages."
    pkgs=(
        # emacs
        # golang
        # zsh
        llvm
        texlive
        texlive-bera
        texlive-caption
        texlive-changepage
        texlive-collection-fontsrecommended
        texlive-collection-latexrecommended
        texlive-enumitem
        texlive-etoolbox
        texlive-fancyhdr
        texlive-footmisc
        texlive-framed
        texlive-geometry
        texlive-hyperref
        texlive-latex-fonts
        texlive-natbib
        texlive-parskip
        texlive-pdftex
        texlive-placeins
        texlive-preprint
        texlive-sectsty
        texlive-soul
        texlive-titlesec
        texlive-titling
        texlive-xstring
    )
    sudo yum -y install "${pkgs[@]}"
fi
