#!/usr/bin/env bash
set -Eeu -o pipefail

# Install Z shell.
# Modified 2019-06-20.

# See also:
# - http://www.zsh.org/
# - http://zsh.sourceforge.net/Arc/source.html
# - https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH

# shellcheck source=/dev/null
source "${KOOPA_DIR}/os/fedora/include/sudo.sh"

name="zsh"
version="$(koopa variable "$name")"
prefix="${KOOPA_CELLAR_PREFIX}/${name}/${version}"
tmp_dir="${KOOPA_TMP_DIR}/zsh"
exe_file="${prefix}/bin/${name}"

printf "Installing %s %s.\n" "$name" "$version"

# Install build dependencies.
sudo yum install -y "$name"
sudo yum-builddep -y "$name"

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    wget "https://sourceforge.net/projects/zsh/files/zsh/${version}/zsh-${version}.tar.xz/download"
    tar -xJvf "download"
    cd "zsh-${version}" || exit 1
    ./configure \
        --build="$KOOPA_OS_BUILD_STRING" \
        --prefix="$prefix"
    make
    make check
    # > make test
    sudo make install
    rm -rf "$tmp_dir"
)

link-cellar "$name" "$version"
_koopa_update_shells "$name"

command -v "$exe_file"
"$exe_file" --version
