#!/usr/bin/env bash
set -Eeu -o pipefail

# Install GNU core utilities.
# Modified 2019-06-20.

# See also:
# - https://ftp.gnu.org/gnu/coreutils/

# shellcheck source=/dev/null
source "${KOOPA_DIR}/os/fedora/include/sudo.sh"

name="coreutils"
version="$(koopa variable "$name")"
prefix="${KOOPA_CELLAR_PREFIX}/${name}/${version}"
tmp_dir="${KOOPA_TMP_DIR}/${name}"
build_name="$KOOPA_OS_BUILD_STRING"
exe_file="${prefix}/bin/env"

printf "Installing %s %s.\n" "$name" "$version"

# Install build dependencies.
sudo yum-builddep -y "$name"

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    wget "https://ftp.gnu.org/gnu/coreutils/coreutils-${version}.tar.xz"
    tar -xJvf "coreutils-${version}.tar.xz"
    cd "coreutils-${version}" || exit 1
    ./configure \
        --build="$build_name" \
        --prefix="$prefix"
    make
    # > make check
    sudo make install
    rm -rf "$tmp_dir"
)

link_cellar "$name" "$version"
sudo ldconfig

if [[ -f "/usr/bin/env" ]]
then
    printf "Replacing '/usr/bin/env' with '/usr/local/bin/env'.\n"
    printf "System version will be renamed to 'env.bak'.\n"
    sudo mv "/usr/bin/env" "/usr/bin/env.bak"
    sudo ln -s "${KOOPA_BUILD_PREFIX}/bin/env" "/usr/bin/env"
fi

command -v "$exe_file"
"$exe_file" --version
