#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(_koopa_header fedora)"

# Install Docker Community Edition.
# Updated 2019-07-11.

# See also:
# - https://docs.docker.com/install/linux/docker-ce/fedora/
# - https://docs.docker.com/install/linux/docker-ce/centos/

# Note that Fedora 28+ is required to use recommended new `dnf` approach.

_koopa_assert_has_sudo
os_type="$(_koopa_os_type)"

# Remove legacy versions, if necessary.
sudo yum -y remove \
    docker \
    docker-client \
    docker-client-latest \
    docker-common \
    docker-engine \
    docker-latest \
    docker-latest-logrotate \
    docker-logrotate

sudo yum -y install \
    device-mapper-persistent-data \
    lvm2 \
    yum-utils

sudo yum-config-manager \
    --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum repolist

sudo yum install -y containerd.io

if [[ "$os_type" == "rhel8" ]]
then
    # RHEL8 requires `--nobest` flag to ignore containerd.io conflict.
    sudo yum -y install --nobest docker-ce docker-ce-cli
else
    sudo yum -y install docker-ce docker-ce-cli
fi

# Note that the docker group is created automatically.
sudo gpasswd -a "$USER" docker

# Ready to start Docker.
sudo systemctl start docker

docker --version
command -v docker
