#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(koopa header fedora)"

# Install RStudio Server Pro.
# Updated 2019-09-19.

# Note that this is also referred to as "Commercial RStudio".

# See also:
# - https://www.rstudio.com/products/rstudio/download-commercial/

_koopa_assert_has_sudo

name="rstudio-server"
tmp_dir="$(_koopa_tmp_dir)/${name}"
version="$(_koopa_variable "$name")"

printf "Installing %s %s.\n" "$name" "$version"

# Remove existing config files.
# > sudo rm -frv /etc/rstudio

(
    rm -fr "$tmp_dir"
    mkdir -pv "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="rstudio-server-rhel-${version}-x86_64.rpm"
    url="https://download2.rstudio.org/server/centos6/x86_64/${file}"
    wget "$url"
    sudo yum -y install "$file"
    rm -fr "$tmp_dir"
)

command -v "$name"
"$name" version

# Activate product license key:
# > sudo rstudio-server license-manager activate <product-key>

# If you want to move your license of RStudio Server to another system you
# should first deactivate it on the old system with the command:
# > sudo rstudio-server license-manager deactivate

sudo "$name" stop
sudo "$name" verify-installation
sudo "$name" start
sudo "$name" status
sudo "$name" license-manager status
