#!/usr/bin/env bash
set -Eeu -o pipefail

# Install Tmux terminal multiplexer.
# Modified 2019-06-21.

# See also:
# - https://github.com/tmux/tmux

# shellcheck source=/dev/null
source "${KOOPA_DIR}/os/fedora/include/sudo.sh"

name="tmux"
version="$(koopa variable "$name")"
prefix="${KOOPA_CELLAR_PREFIX}/${name}/${version}"
tmp_dir="${KOOPA_TMP_DIR}/${name}"
exe_file="${prefix}/bin/${name}"

printf "Installing %s %s.\n" "$name" "$version"

# Install build dependencies.
sudo yum install -y "$name"
sudo yum-builddep -y "$name"

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    wget "https://github.com/tmux/tmux/releases/download/${version}/tmux-${version}.tar.gz"
    tar -xzvf "tmux-${version}.tar.gz"
    cd "tmux-${version}" || exit 1
    ./configure \
        --build="$KOOPA_OS_BUILD_STRING" \
        --prefix="$prefix"
    make
    sudo make install
    rm -rf "$tmp_dir"
)

link-cellar "$name" "$version"

"$exe_file" -V
command -v "$exe_file"
