#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header fedora)"

# Install RStudio Server.
# Modified 2019-06-23.

# See also:
# - https://www.rstudio.com/products/rstudio/download-server/

_koopa_assert_has_sudo

name="rstudio-server"
tmp_dir="$(koopa tmp-dir)/${name}"
version="$(koopa variable "$name")"

printf "Installing %s %s.\n" "$name" "$version"

sudo rm -rf /etc/rstudio

# R 3.6.0 fix for missing libRblas.so file.
if [[ ! -f "/usr/lib64/R/lib/libRblas.so" ]]
then
    if [[ -f "/usr/local/lib64/R/lib/libRblas.so" ]]
    then
        sudo cp /usr/local/lib64/R/lib/libRblas.so /usr/lib64/R/lib/.
    else
        >&2 printf "Error: Missing '%s'.\n" "/usr/lib64/R/lib/libRblas.so"
    fi
fi

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="rstudio-server-rhel-${version}-x86_64.rpm"
    url="https://download2.rstudio.org/server/centos6/x86_64/${file}"
    wget "$url"
    sudo yum -y reinstall "$file"
    rm -rf "$tmp_dir"
)

command -v "$name"
"$name" version

sudo "$name" stop
sudo "$name" verify-installation
sudo "$name" start
sudo "$name" status
