#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(koopa header fedora)"
_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

name="shiny-server"
tmp_dir="$(_koopa_tmp_dir)/${name}"
version="$(_koopa_variable "$name")"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install Shiny Server.

$(_koopa_help_args)

see also:
    https://www.rstudio.com/products/rstudio/download-server/

note:
    Bash script.
    Updated 2019-09-26.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

printf "Installing %s %s.\n" "$name" "$version"

(
    rm -fr "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    sudo su - -c "R -e \"install.packages('shiny', repos='https://cran.rstudio.com/')\""
    file="shiny-server-${version}-x86_64.rpm"
    url="https://download3.rstudio.org/centos6.3/x86_64/${file}"
    wget "$url"
    sudo yum install -y --nogpgcheck "$file"
    rm -fr "$tmp_dir"
)

command -v "$name"
"$name" --version
