#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_no_args "$@"
_koopa_assert_has_sudo

if ! _koopa_is_installed cpanm
then
    sudo yum -y install perl-App-cpanminus
fi

sudo cpanm -f File::Rename

# Alternate method:
# > perl -MCPAN -e 'install File::Rename'

command -v rename
rename --version
