#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header fedora)"

# Install Emacs.
# Modified 2019-06-23.

sudo yum install -y emacs
sudo yum-builddep -y emacs

source "${KOOPA_HOME}/system/include/install/emacs.sh"
