#!/usr/bin/env bash
set -Eeu -o pipefail

# Install Emacs.
# Modified 2019-06-20.

# See also:
# - https://www.gnu.org/software/emacs/
# - https://github.com/emacs-mirror/emacs

# shellcheck source=/dev/null
source "${KOOPA_DIR}/os/fedora/include/sudo.sh"

name="emacs"
version="$(koopa variable "$name")"
prefix="${KOOPA_CELLAR_PREFIX}/${name}/${version}"
tmp_dir="${KOOPA_TMP_DIR}/${name}"
build_name="$KOOPA_OS_BUILD_STRING"
exe_file="${prefix}/bin/${name}"

printf "Installing %s %s.\n" "$name" "$version"

# Install build dependencies.
sudo yum install -y "$name"
sudo yum-builddep -y "$name"

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    wget "http://ftp.gnu.org/gnu/emacs/emacs-${version}.tar.xz"
    tar -xJvf "emacs-${version}.tar.xz"
    cd "emacs-${version}" || exit 1
    ./configure \
        --build="$build_name" \
        --prefix="$prefix"
    make
    sudo make install
    rm -rf "$tmp_dir"
)

link_cellar "$name" "$version"
sudo ldconfig

command -v "$exe_file"
"$exe_file" --version
