#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header fedora)"

# Install Tmux terminal multiplexer.
# Modified 2019-06-23.

sudo yum install -y tmux
sudo yum-builddep -y tmux

source "${KOOPA_HOME}/system/include/install/tmux.sh"
