#!/usr/bin/env bash
set -Eeu -o pipefail

# Update rJava configuration.
# Modified 2019-06-14.

# shellcheck source=/dev/null
source "${KOOPA_DIR}/system/include/os/fedora/sudo.sh"

printf "Updating R Java configuration.\n"

# > R CMD javareconf -h

# Environment variables that can be used to influence the detection:
#   JAVA           path to a Java interpreter executable
#                  By default first 'java' command found on the PATH
#                  is taken (unless JAVA_HOME is also specified).
#   JAVA_HOME      home of the Java environment. If not specified,
#                  it will be detected automatically from the Java
#                  interpreter.
#   JAVAC          path to a Java compiler
#   JAVAH          path to a Java header/stub generator
#   JAR            path to a Java archive tool

# Fix permissions.
sudo chgrp -R wheel /usr/local/lib64/R
sudo chmod -R g+w /usr/local/lib64/R

java_dir="/usr/lib/jvm/java"
java_flags=" \
    JAVA=${java_dir}/bin/java \
    JAVA_HOME=${java_dir} \
    JAVAC=${java_dir}/bin/javac \
    JAR=${java_dir}/bin/jar \
"

# shellcheck disable=SC2086
sudo R --vanilla CMD javareconf $java_flags

# shellcheck disable=SC2086
R --vanilla CMD javareconf $java_flags

yum list installed | grep -E '^java-'

# > Rscript -e 'install.packages("rJava")'
