#!/usr/bin/env bash
set -Eeu -o pipefail

# Install OpenSSL.

# See also:
# - https://www.openssl.org/source/
# - https://wiki.openssl.org/index.php/Compilation_and_Installation
# - https://wiki.openssl.org/index.php/Binary_Compatibility

# shellcheck source=/dev/null
source "${KOOPA_DIR}/system/include/os/fedora/sudo.sh"

name="openssl"
version="$(koopa variable "$name")"
prefix="${KOOPA_CELLAR_PREFIX}/${name}/${version}"
tmp_dir="${KOOPA_TMP_DIR}/${name}"
exe_file="${prefix}/bin/${name}"

printf "Installing %s %s.\n" "$name" "$version"

# Install build dependencies.
sudo yum install -y "$name"
sudo yum-builddep -y "$name"

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    curl -O "https://www.openssl.org/source/openssl-${version}.tar.gz"
    tar -xvzf "openssl-${version}.tar.gz"
    cd "openssl-${version}" || exit 1
    ./config \
        --prefix="$prefix" \
        --openssldir="$prefix" \
        shared
    make
    make test
    sudo make install
    rm -rf "$tmp_dir"
)

sudo ldconfig

command -v "$exe_file"
"$exe_file" version
"$exe_file" ciphers -y
