#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_acid_assert_has_no_args "$@"
_acid_assert_has_sudo

log_dir="${HOME}/logs/${HOSTNAME}/yum"
mkdir -pv "$log_dir"
log_file="${log_dir}/yum-update-$(date +%F).log"

sudo yum update -y 2>&1 | tee "$log_file"
