#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/../lang/shell/bash/include/header.sh"

# FIXME Need to improve error messages here.
koopa::check_bin_man_consistency "$@"
