#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header bash)"

# """
# Conda environment test script.
# @note Updated 2020-07-21.
# """

koopa::h1 "Testing conda environment loading."

koopa::conda_create_env \
    'kallisto=0.46.2' \
    'salmon=1.3.0'

koopa::activate_conda_env kallisto
kallisto version
koopa::deactivate_conda

koopa::activate_conda_env kallisto@0.46.2
kallisto version
koopa::deactivate_conda

koopa::activate_conda_env salmon
salmon --version
koopa::deactivate_conda

koopa::activate_conda_env salmon@1.3.0
salmon --version
koopa::deactivate_conda

koopa::success "Conda environments loaded successfully."
