#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/../lang/shell/bash/include/header.sh"

main() {
    # """
    # Conda environment test script.
    # @note Updated 2022-02-16.
    # """
    local kallisto_version salmon_version
    kallisto_version="$(koopa_variable 'conda-kallisto')"
    salmon_version="$(koopa_variable 'conda-salmon')"
    koopa_h1 'Testing conda environment loading.'
    koopa_conda_create_env \
        "kallisto@${kallisto_version}" \
        "salmon@${salmon_version}"
    koopa_conda_activate_env 'kallisto'
    kallisto version
    koopa_conda_activate_env "kallisto@${kallisto_version}"
    kallisto version
    koopa_conda_activate_env 'salmon'
    salmon --version
    koopa_conda_activate_env "salmon@${salmon_version}"
    salmon --version
    koopa_deactivate_conda
    koopa_alert_success 'Conda environments loaded successfully.'
    return 0
}

main "$@"
