#!/usr/bin/env bash

# shellcheck source=/dev/null
. "$(dirname "${BASH_SOURCE[0]}")/../shell/bash/include/header.sh"

koopa::test_docker() {
    # """
    # Install and test koopa inside Docker.
    # Updated 2020-11-10.
    # """
    local cmd image
    image="${1:-debian}"
    image="acidgenomics/${image}:minimal"
    koopa::h1 "Running Docker install test in '${image}' image."
    cmd="\
            set -Eeu -o pipefail \
         && if [ -d /usr/local/koopa ]; \
            then \
                sudo rm -fr /usr/local/koopa; \
            else if [ -d ~/.local/share/koopa ]; \
            then \
                rm -fr ~/.local/share/koopa;
            fi \
        && curl -sSL https://koopa.acidgenomics.com/install \
            | bash -s -- --non-interactive --test \
    "
    docker pull "$image"
    docker run -it "$image" bash -c "$cmd"
    koopa::success 'Installation test was successful.'
    return 0
}

koopa::test_docker "$@"
