#!/usr/bin/env bash

# """
# Check that scripts do not contain lints.
# Updated 2020-07-07.
# """

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
koopa_prefix="$(cd "${script_dir}/.." &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${koopa_prefix}/shell/bash/include/header.sh"

koopa::h1 'Running linter checks.'

# Check that linter config files are linked correctly.
# This step can error if dotfiles submodule hasn't cloned.
koopa::git_clone_dotfiles >/dev/null
koopa::assert_is_symlink "${koopa_prefix}/."{'lintr','pylintrc'}

linter_dir="${script_dir}/linter.d"
for file in "${linter_dir}/"*'.sh'
do
    # shellcheck source=/dev/null
    [ -f "$file" ] && "$file"
done
