#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/../lang/shell/bash/include/header.sh"

koopa::test_linter() {
    # """
    # Check that scripts do not contain lints.
    # Updated 2020-08-12.
    # """
    local koopa_prefix linter_prefix
    koopa_prefix="$(koopa::koopa_prefix)"
    koopa::h1 'Running linter checks.'
    koopa::assert_is_file "${koopa_prefix}/."{'lintr','pylintrc'}
    linter_prefix="${koopa_prefix}/tests/linter.d"
    koopa::exec_dir "$linter_prefix"
    return 0
}

koopa::test_linter "$@"
