#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/../lang/shell/bash/include/header.sh"

main() { # {{{1
    # """
    # Check that all scripts support '--help' flag.
    # Updated 2022-02-24.
    # """
    local app dict
    local bin_dir bin_dirs bin_file bin_files
    local man_dir man_dirs man_file man_files
    declare -A app=(
        [head]="$(koopa_locate_head)"
    )
    declare -A dict=(
        [koopa_prefix]="$(koopa_koopa_prefix)"
        [status]=0
    )
    koopa_h1 "Running manual file '--help' flag checks."
    # man dirs {{{2
    # --------------------------------------------------------------------------
    # Put all 'man/' dirs into an array and loop.
    readarray -t man_dirs <<< "$( \
        koopa_find \
            --exclude='.git/**' \
            --exclude='app/**' \
            --exclude='opt/**' \
            --min-depth=1 \
            --pattern='man' \
            --prefix="${dict[koopa_prefix]}" \
            --sort \
            --type='d' \
    )"
    if koopa_is_array_empty "${man_dirs[@]}"
    then
        koopa_stop 'Failed to locate any man dirs.'
    fi
    for man_dir in "${man_dirs[@]}"
    do
        koopa_add_to_manpath_start "$man_dir"
    done
    # man file formatting {{{2
    # --------------------------------------------------------------------------
    koopa_h2 'Checking troff man file formatting.'
    for man_dir in "${man_dirs[@]}"
    do
        koopa_h3 "$man_dir"
        readarray -t man_files <<< "$( \
            koopa_find \
                --max-depth=2 \
                --min-depth=2 \
                --prefix="$man_dir" \
                --sort \
                --type 'f' \
        )"
        if koopa_is_array_empty "${man_files[@]:-}"
        then
            koopa_stop "No files: '${man_dir}'."
        fi
        for man_file in "${man_files[@]}"
        do
            if ! koopa_str_detect_regex \
                --string="$("${app[head]}" --lines=1 "$man_file")" \
                --pattern='^\.TH '
            then
                koopa_alert_note "ERROR: '${man_file}'."
                dict[status]=1
            fi
        done
    done
    # '--help' flag support {{{2
    # --------------------------------------------------------------------------
    koopa_h2 "Running exported script '--help' flag checks."
    readarray -t bin_dirs <<< "$( \
        koopa_find \
            --exclude='.git/**' \
            --exclude='app/**' \
            --exclude='opt/**' \
            --min-depth=1 \
            --pattern='{bin,sbin}' \
            --prefix="${dict[koopa_prefix]}" \
            --sort \
            --type='d' \
    )"
    if koopa_is_array_empty "${bin_dirs[@]}"
    then
        koopa_stop 'Failed to locate any bin dirs.'
    fi
    for bin_dir in "${bin_dirs[@]}"
    do
        koopa_h3 "$bin_dir"
        readarray -t bin_files <<< "$( \
            koopa_find \
                --max-depth=1 \
                --min-depth=1 \
                --prefix="$bin_dir" \
                --sort \
                --type='f' \
        )"
        for bin_file in "${bin_files[@]}"
        do
            if ! "$bin_file" --help &>/dev/null
            then
                koopa_alert_note "ERROR: '${bin_file}'."
                dict[status]=1
            fi
        done
    done
    return "${dict[status]}"
}

main "$@"
