#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/../lang/shell/bash/include/header.sh"

koopa::test_shunit2() {
    # """
    # Run shUnit2 tests.
    # @note Updated 2020-07-23.
    # @seealso
    # - https://github.com/kward/shunit2
    # """
    local extra koopa_prefix shunit2_dir
    koopa::assert_is_installed shunit2
    extra=0
    while (("$#"))
    do
        case "$1" in
            --extra)
                extra=1
                shift 1
                ;;
            *)
                koopa::invalid_arg "$1"
                ;;
        esac
    done
    koopa::h1 'Running unit tests with shUnit2.'
    # Don't exit on errors, which are handled by shunit2.
    set +o errexit
    koopa_prefix="$(koopa::koopa_prefix)"
    shunit2_dir="${koopa_prefix}/tests/shunit2.d"
    suite() { # {{{1
        koopa::source_dir "$shunit2_dir"
        if [[ "$extra" -eq 1 ]]
        then
            koopa::source_dir "${shunit2_dir}/extra"
        fi
        readarray -t tests <<< "$( \
            declare -F \
                | cut -d ' ' -f 3 \
                | grep -E '^test_' \
                | sort \
        )"
        for test in "${tests[@]}"
        do
            suite_addTest "$test"
        done
    }
    . shunit2
    return 0
}

koopa::test_shunit2 "$@"
