#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/../lang/shell/bash/include/header.sh"

koopa::run_tests() {
    # """
    # Continuous integration (CI) tests.
    # @note Updated 2020-07-23.
    # """
    local tests_dir
    tests_dir="$(dirname "${BASH_SOURCE[0]}")"
    (
        cd "$tests_dir" || exit 1
        ./bin-man-consistency
        ./linter
        ./shunit2
        # > ./roff
    )
    return 0
}

koopa::run_tests "$@"
