.TH ENABLE-PASSWORDLESS-SUDO 1 2019-11-09 Bash
.SH NAME
enable-passwordless-sudo \- Enable password-less sudo access
.SH SYNOPSIS
.B clean-tmp
.IR [user]
.SH OPTIONS
.TP
.BR user
User to enable. Defaults to current user, defined by 'USER'.
.SH DESCRIPTION
The script writes a user configuration file in '/etc/sudoers.d/'.
