.TH INSTALL-RBENV 1 2019-12-12 Bash
.SH NAME
install-rbenv \-
Install Ruby environment manager (rbenv)
.SH SYNOPSIS
.B install-rbenv
.SH DESCRIPTION
Installs for current user only, into 'XDG_DATA_HOME' at 'rbenv'.
.SH SEE ALSO
.IP
\(bu https://github.com/rbenv/rbenv
.IP
\(bu https://blakewilliams.me/posts/system-wide-rbenv-install
.IP
\(bu https://devhints.io/rbenv
