#!/usr/bin/env zsh

_koopa_zsh_prompt() {
    # """
    # Koopa ZSH prompt.
    # @note Updated 2023-03-09.
    # """
    _koopa_is_root && return 0
    _koopa_activate_starship
    [[ -n "${STARSHIP_SHELL:-}" ]] && return 0
    PROMPT="$(_koopa_zsh_prompt_string)"
    return 0
}

_koopa_zsh_prompt_string() {
    # """
    # Zsh prompt string (PS1).
    # @note Updated 2023-03-09.
    #
    # This is a modified, lighter version of Pure, by Sindre Sorhus.
    #
    # Subshell exec need to be escaped here, so they are evaluated dynamically
    # when the prompt is refreshed.
    #
    # Unicode characters don't work well with some Windows fonts.
    #
    # Conda environment activation is messing up '%m'/'%M' flag on macOS.
    # This seems to be specific to macOS and doesn't happen on Linux.
    #
    # Prompt variables:
    # - %* : time
    # - %F : color dict
    # - %M : machine (host) name (full)
    # - %f : reset color
    # - %m : machine (host) name (up to first '.')
    # - %n : user name
    # - %~ : current path
    # - %(?..) : prompt conditional - %(condition.true.false)
    #
    # See also:
    # - https://github.com/sindresorhus/pure/
    # - https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/
    #       robbyrussell.zsh-theme
    # """
    local dict
    [[ "$#" -eq 0 ]] || return 1
    declare -A dict=(
        [newline]=$'\n'
        [prompt]='❯' # default is '%%'.
        [prompt_color]="${fg[magenta]}"
        [user]='%n@%m'
        [user_color]="${fg[cyan]}"
        [wd]='%~'
        [wd_color]="${fg[blue]}"
    )
    printf '%s%s%s%s%s%s ' \
        "${dict[newline]}" \
        "%F%{${dict[user_color]}%}${dict[user]}%f" \
        "${dict[newline]}" \
        "%F%{${dict[wd_color]}%}${dict[wd]}%f" \
        "${dict[newline]}" \
        "%F%{${dict[prompt_color]}%}${dict[prompt]}%f"
    return 0
}

_koopa_zsh_prompt "$@"
