#!/usr/bin/env zsh

# """
# Koopa ZSH prompt.
# @note Updated 2022-01-21.
# """

_koopa_zsh_prompt_setup() { # {{{1
    if _koopa_is_installed 'starship'
    then
        _koopa_activate_starship
        return 0
    fi
    PROMPT="$(_koopa_zsh_prompt_string)"
}

_koopa_zsh_prompt_setup "$@"
