#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# Install latest version of R.
# https://cran.r-project.org/bin/linux/ubuntu/README.html
# """

_koopa_exit_if_installed R
_koopa_assert_is_installed add-apt-repository

release="$(_koopa_os_codename)"

# Release is signed by Michael Rutter <marutter@gmail.com>.
# Refer to 'Secure apt' section for details.
sudo apt-key adv \
    --keyserver keyserver.ubuntu.com \
    --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9

# Modify '/etc/apt/sources.list' file.
sudo add-apt-repository \
    "deb https://cloud.r-project.org/bin/linux/ubuntu ${release}-cran35/"

sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive \
    apt-get --no-install-recommends --yes install \
        r-base r-base-dev

_koopa_link_r_etc
_koopa_link_r_site_library

# Avoid write failure to 'doc/' here upon package update.
_koopa_set_permissions /usr/share/R
