#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# https://rstudio.com/products/shiny/download-server/ubuntu/

_koopa_assert_has_no_args "$@"
_koopa_assert_is_installed R gdebi
_koopa_assert_is_not_installed shiny-server
_koopa_assert_is_r_package_installed shiny

name="shiny-server"
tmp_dir="$(_koopa_tmp_dir)/${name}"
version="$(_koopa_variable "$name")"

_koopa_message "Installing ${name} ${version}."

(
    rm -fr "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="shiny-server-${version}-amd64.deb"
    url="https://download3.rstudio.org/ubuntu-14.04/x86_64/${file}"
    _koopa_download "$url"
    sudo gdebi --non-interactive "$file"
    rm -fr "$tmp_dir"
)

command -v "$name"
"$name" --version
