#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(koopa header ubuntu)"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install R from CRAN.

$(_koopa_help_args)

see also:
    - https://cran.r-project.org/bin/linux/ubuntu/README.html
    - https://askubuntu.com/questions/197564

note:
    Bash script.
    Updated 2019-09-26.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

release="$(lsb_release -s -c)"

sudo apt-key adv \
    --keyserver keyserver.ubuntu.com \
    --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9

# Modify `/etc/apt/sources.list` file.
sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu ${release}-cran35/"

sudo apt-get update
sudo apt-get -y install r-base r-base-dev
