#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# https://rstudio.com/products/shiny/download-server/ubuntu/

name="shiny-server"

_koopa_exit_if_docker
_koopa_exit_if_installed "$name"
_koopa_assert_has_no_args "$@"
_koopa_assert_is_installed R gdebi

tmp_dir="$(_koopa_tmp_dir)/${name}"
version="$(_koopa_variable "$name")"

_koopa_h1 "Installing ${name} ${version}."


if ! _koopa_is_r_package_installed shiny
then
    _koopa_h2 "Installing 'shiny' R package."
    (
        set -o xtrace
        Rscript -e 'install.packages("shiny")'
    ) &> "$(_koopa_tmp_log_file)"
fi

(
    set -o xtrace
    _koopa_cd_tmp_dir "$tmp_dir"
    file="shiny-server-${version}-amd64.deb"
    url="https://download3.rstudio.org/ubuntu-14.04/x86_64/${file}"
    _koopa_download "$url"
    sudo gdebi --non-interactive "$file"
) &> "$(_koopa_tmp_log_file)"

rm -fr "$tmp_dir"

_koopa_success "Installation of $name was successful."
