#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# Currently supports overlay2, aufs and btrfs storage drivers.
# https://docs.docker.com/install/linux/docker-ce/ubuntu/

# Configures at '/var/lib/docker/'.

_koopa_exit_if_installed docker
_koopa_assert_has_no_args "$@"

# Remove legacy versions, if necessary.
sudo apt-get -y remove docker docker-engine docker.io containerd runc

sudo apt-get update

# Install packages to allow apt to use a repository over HTTPS.
sudo DEBIAN_FRONTEND=noninteractive \
    apt-get -y install \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg-agent \
        software-properties-common

# Add Docker's official GPG key.
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88

# Set up the stable repository.
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

sudo apt-get update

# Ready to install Docker.
sudo DEBIAN_FRONTEND=noninteractive \
    apt-get -y install docker-ce docker-ce-cli containerd.io

# Ensure current user is added to Docker group.
sudo usermod -aG docker "$USER"

_koopa_link_docker

_koopa_success "Installation of Docker was successful."
