#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# https://rstudio.com/products/shiny/download-server/ubuntu/
# """

reinstall=0

pos=()
while (("$#"))
do
    case "$1" in
        --reinstall)
            reinstall=1
            shift 1
            ;;
        --)
            shift 1
            break
            ;;
        --*|-*)
            _koopa_invalid_arg "$1"
            ;;
        *)
            pos+=("$1")
            shift 1
            ;;
    esac
done
set -- "${pos[@]}"

name="shiny-server"

# > _koopa_exit_if_docker
[[ "$reinstall" -eq 0 ]] && _koopa_exit_if_installed "$name"

version="$(_koopa_variable "$name")"
name_fancy="Shiny Server ${version}"

_koopa_install_start "$name_fancy"

_koopa_assert_has_no_args "$@"
_koopa_assert_is_installed R gdebi

tmp_dir="$(_koopa_tmp_dir)"

if ! _koopa_is_r_package_installed shiny
then
    _koopa_h2 "Installing 'shiny' R package."
    (
        Rscript -e 'install.packages("shiny")'
    ) 2>&1 | tee "$(_koopa_tmp_log_file)"
fi

(
    _koopa_cd_tmp_dir "$tmp_dir"
    file="shiny-server-${version}-amd64.deb"
    url="https://download3.rstudio.org/ubuntu-14.04/x86_64/${file}"
    _koopa_download "$url"
    sudo gdebi --non-interactive "$file"
) 2>&1 | tee "$(_koopa_tmp_log_file)"

rm -fr "$tmp_dir"

_koopa_install_success "$name_fancy"
