#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# https://help.ubuntu.com/lts/serverguide/installing-upgrading.html
# > sudo do-release-upgrade
# """

sudo apt-get update
sudo apt-get list --upgradable
sudo DEBIAN_FRONTEND=noninteractive \
    apt-get --no-install-recommends --yes dist-upgrade
