* High complexity
* Medium complexity
** TODO Can I improve our VS Code dotfiles config to get Python and R IDE to behave like Positron?
** TODO Need to handle this weird edge case with `koopa update`:
=> Failed to install zstd: App 'cmake' has broken library paths (missing: /opt/koopa/app/cmake/4.3.2/lib). Reinstall with: koopa reinstall cmake
Error: 1 app(s) failed: zstd.
* Low complexity
** TODO Ensure we have reduced bootstrap message spam during `koopa update`:
Bootstrap is out of date (2026.05.05.1404 != 2026.05.09.1333)
=> Updating bootstrap.
Installing bootstrap.
** TODO Interesting edge case with `koopa uninstall` after git pull on repo:
Error: koopa bootstrap Python is invalid.
Run the following to rebuild:
sh '/Users/mike/.local/share/koopa/bootstrap.sh'
Then when you try to run the bootstrap:
Error: Intel Mac (x86_64) is no longer supported.
koopa requires macOS on Apple Silicon (arm64).
There's no way to for an Intel Mac user to safely uninstall koopa currently.
** TODO Improve tqdm progress bar status for `koopa develop check-app-versions`:
koopa develop check-app-versions --reset-cache
Checking automake:   7%|██████▋                                                                                             | 27/404 [00:07<02:24,  2.61app/s]
Put the app name in the right side of the tqdm progress bar
Current approach with "Checking <APP>" on the left side looks crazy, moves the bar around too much
** TODO Need to rename `koopa app brew upgrade-brews`
We primarily use this to update our Homebrew casks, which are different than brews, so this needs a better name. Should we just do `koopa app brew upgrade`?
** TODO Consider installing perl and ruby from conda-forge instead of building from source.
