#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_is_debian
_koopa_assert_has_no_envs

_koopa_enable_passwordless_sudo
_koopa_prepare_make_prefix

# Remove default user shell configuration files.
sudo rm -fv /etc/skel/.{bash_logout,bashrc,profile}
rm -fv ~/.{bash_logout,bashrc,profile}

# Prepare '/n/' share.
sudo mkdir -pv /data01/n/app
sudo ln -fnsv /data01/n /n

install-debian-base
install-openjdk

if _koopa_is_matching_fixed "$HOSTNAME" awslabapp32
then
    install-cellar-coreutils
    install-cellar-bash
    install-cellar-zsh
    install-cellar-fish
    install-cellar-tmux
    install-cellar-git
    install-cellar-gnupg
    install-cellar-lua
    install-cellar-luarocks
    install-cellar-python
    install-cellar-vim
    install-cellar-neovim
    install-cellar-emacs
    install-cellar-sqlite
    install-cellar-proj
    install-cellar-gdal
    install-cellar-hdf5
    install-cellar-gsl
    install-cellar-go
    install-cellar-perl
    install-cellar-ruby
    install-cellar-julia
    install-cellar-htop
    install-cellar-shellcheck
    install-cellar-neofetch
    install-cellar-genrich
    install-cellar-autojump
    install-cellar-fzf
    install-cellar-the-silver-searcher
    install-rust
    install-perlbrew
    install-rbenv
    install-pyenv
    install-rstudio-server-pro
    r-javareconf
else
    install-rstudio-server
fi

# bcbio-nextgen
# 10X Genomics CellRanger, CellRanger ATAC
# conda-create-bioinfo-envs
# install-rust-cargo-crates
# rust crates

install-shiny-server
update-aws-vm
