#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_is_debian
_koopa_assert_has_no_envs

cpi="false"
source="false"

while (("$#"))
do
    case "$1" in
        --cpi=*)
            cpi="${1#*=}"
            shift 1
            ;;
        --cpi)
            cpi="true"
            shift 1
            ;;
        --source=*)
            source="${1#*=}"
            shift 1
            ;;
        --source)
            source="true"
            shift 1
            ;;
        *)
            _koopa_invalid_arg "$1"
            ;;
    esac
done

data_disk="/mnt/data01"

_koopa_enable_passwordless_sudo

# Remove default user shell configuration files.
sudo rm -fv /etc/skel/.{bash_logout,bashrc,profile}

# Prepare '/n/' share.
sudo mkdir -pv "${data_disk}/n/app"
sudo ln -fnsv "${data_disk}/n" /n

_koopa_prepare_make_prefix

install-debian-base

if [[ "$cpi" == "true" ]]
then
    _koopa_message "Updating '/etc/profile.d'."
    _koopa_update_profile
    sudo ln -fnsv \
        "$(_koopa_prefix)/host/aws/etc/profile.d/constellation.sh" \
        "/etc/profile.d/."

    if _koopa_is_matching_fixed "$HOSTNAME" awslabapp32
    then
        install-rstudio-server-pro
    fi

    rsync-vm --data-disk="$data_disk" --source-ip="10.201.20.32"
fi

install-openjdk

if [[ "$source" == "true" ]]
then
    # /usr/local/cellar
    install-cellar-coreutils
    install-cellar-bash
    install-cellar-zsh
    install-cellar-fish
    install-cellar-tmux
    install-cellar-git
    install-cellar-gnupg
    install-cellar-lua
    install-cellar-luarocks
    install-cellar-python
    install-cellar-vim
    install-cellar-neovim
    install-cellar-emacs
    install-cellar-sqlite
    install-cellar-proj
    install-cellar-gdal
    install-cellar-hdf5
    install-cellar-gsl
    install-cellar-go
    install-cellar-perl
    install-cellar-ruby
    install-cellar-julia
    install-cellar-htop
    install-cellar-shellcheck
    install-cellar-neofetch
    install-cellar-genrich
    install-cellar-autojump
    install-cellar-fzf
    install-cellar-the-silver-searcher
    # /n/app
    install-rust
    install-perlbrew
    install-rbenv
    install-pyenv
    r-javareconf
    # conda-create-bioinfo-envs
    # install-rust-cargo-crates
    # bcbio-nextgen
    # 10X Genomics CellRanger, CellRanger ATAC
fi

if ! _koopa_is_installed rstudio-server
then
    install-rstudio-server
fi

if ! _koopa_is_installed shiny-server
then
    install-shiny-server
fi

_koopa_update_lmod_config

_koopa_success "AWS VM is configured correctly."
