#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_is_debian
_koopa_assert_has_no_envs

_koopa_enable_passwordless_sudo
_koopa_prepare_make_prefix

# Remove default user shell configuration files.
sudo rm -fv /etc/skel/.{bash_logout,bashrc,profile}
rm -fv ~/.{bash_logout,bashrc,profile}

# Prepare '/n/' share.
sudo mkdir -pv /data01/n/app
sudo ln -fnsv /data01/n /n

# Note that we're installing R using apt instead of cellar approach.
# Refer to 'install-debian-base' for details.
# Is 'install-debian' handling the Ubuntu installation correctly?
# Check my Dockerfile for details.

install-debian-base
install-openjdk

install-cellar-coreutils
install-cellar-bash
install-cellar-zsh
install-cellar-fish
install-cellar-tmux
install-cellar-git
install-cellar-gnupg
install-cellar-lua
install-cellar-luarocks
# Don't run 'install-cellar-r' here.
install-cellar-python



# Need to automatically configure Rprofile.site, Renviron.site, and site-library
# for Debian and Ubuntu.
