#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

KOOPA_PREFIX="$(_koopa_prefix)"

apt=0
cpi=0

while (("$#"))
do
    case "$1" in
        --apt)
            apt=1
            shift 1
            ;;
        --cpi)
            cpi=1
            shift 1
            ;;
        *)
            _koopa_invalid_arg "$1"
            ;;
    esac
done

_koopa_message "Updating Docker config."
sudo systemctl stop docker
sudo rm -frv "/var/lib/docker"
sudo mkdir -pv "/n/var/lib/docker"
sudo ln -fnsv "/n/var/lib/docker" "/var/lib/docker"
sudo systemctl enable docker
sudo systemctl start docker

if [[ "$apt" -eq 1 ]]
then
    _koopa_message "Updating system packages."
    install-debian-base
fi

if [[ "$cpi" -eq 1 ]]
then
    _koopa_message "Updating '/etc/profile.d'."
    _koopa_update_profile
    sudo ln -fnsv \
        "${KOOPA_PREFIX}/host/aws/etc/profile.d/constellation.sh" \
        "/etc/profile.d/."

    # rsync-aws-vm

    # _koopa_update_lmod_config
    # install-openjdk
fi

_koopa_success "AWS VM updated successfully."
