#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

KOOPA_PREFIX="$(_koopa_prefix)"

all=0
apt=0
rsync=0

while (("$#"))
do
    case "$1" in
        --all)
            all=1
            apt=1
            rsync=1
            shift 1
            ;;
        --apt)
            apt=1
            shift 1
            ;;
        --rsync)
            rsync=1
            shift 1
            ;;
        *)
            _koopa_invalid_arg "$1"
            ;;
    esac
done

_koopa_message "Updating '/etc/profile.d'."
_koopa_update_profile
sudo ln -fnsv \
    "${KOOPA_PREFIX}/host/aws/etc/profile.d/constellation.sh" \
    "/etc/profile.d/."

# Consider making this an internal function.
# Refer to 'https://github.com/acidgenomics/docker' for details.
_koopa_message "Updating Docker config."
sudo systemctl stop docker
# > sudo ln -fnsv \
# >     "${KOOPA_PREFIX}/os/debian/etc/docker/"* \
# >     "/etc/docker/."
sudo rm -frv "/var/lib/docker"
sudo mkdir -pv "/n/var/lib/docker"
sudo ln -fnsv "/n/var/lib/docker" "/var/lib/docker"
sudo systemctl enable docker
sudo systemctl start docker

if [[ "$apt" -eq 1 ]]
then
    _koopa_message "Updating system packages."
    sudo apt update
    sudo apt -y dist-upgrade
    # Consider changing this to 'ubuntu' instead of 'debian'.
    install-debian-base
fi

if [[ "$rsync" -eq 1 ]]
then
    _koopa_note "'rsync' flag support not complete yet."
fi

if [[ "$all" -eq 1 ]]
then
    _koopa_note "'all' flag support not complete yet."
fi
