# Template for fast RNA-seq using Illumina prepared samples.
# Note that this template doesn't perform alignment or quality control.
---
details:
  - analysis: fastrna-seq
    genome_build: hg38
    algorithm: {}
upload:
  dir: ../final
