# Template for fast RNA-seq using Illumina prepared samples.
# Michael Steinbaugh
#
# Homo sapiens
# YYYY-MM-DD
#
# Note that this template doesn't perform alignment or quality control.
#
# Assuming a local run on a 16 core VM. Use n - 2 cores.
# bcbio_nextgen_py ../config/bcbio.yaml -t local -n 14
#
# Genome build is specific to the bcbio install.
# Run `bcbio_setup_genome.py` for list of genome builds.
#
# More template examples:
# https://github.com/bcbio/bcbio-nextgen/tree/master/config/templates
#
# Configuration documentation:
# https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html
---
details:
  - analysis: fastrna-seq
    genome_build: hg38
    algorithm: {}

# Where to upload (save) the final output.
upload:
  dir: ../final

# Recommended run-specific resources.
resources:
  default:
    cores: 14
  tmp:
    dir: ~/scratch
