# Template for fast RNA-seq using Illumina prepared samples
#
# Homo sapiens
# YYYY-MM-DD
#
# NOTE: genome_build is specific to bcbio install
# Run `bcbio_setup_genome.py` for list of genome builds
#
# More template examples:
# https://github.com/bcbio/bcbio-nextgen/tree/master/config/templates
---
details:
  - analysis: fastrna-seq
    genome_build: hg38
    algorithm: {}
upload:
  dir: ../final
