# Template for RNA-seq using Illumina prepared samples
#
# Homo sapiens
# YYYY-MM-DD
#
# NOTE: genome_build is specific to bcbio install
# Run `bcbio_setup_genome.py` for list of genome builds
#
# More template examples:
# https://github.com/bcbio/bcbio-nextgen/tree/master/config/templates
---
details:
  - analysis: RNA-seq
    genome_build: GRCh38_92
    algorithm:
      # Use `star` by default for genomes other than GRCh38
      aligner: hisat2
      expression_caller: salmon
upload:
  dir: ../final
