# Template for fast RNA-seq using Illumina prepared samples.
# Michael Steinbaugh
#
# Homo sapiens
# YYYY-MM-DD
#
# Note that this template doesn't perform alignment or quality control.
#
# Run `bcbio_setup_genome.py` to list available genome builds.
#
# More template examples:
# https://github.com/bcbio/bcbio-nextgen/tree/master/config/templates
#
# Configuration documentation:
# https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html
---
details:
  - analysis: fastrna-seq
    genome_build: hg38
    algorithm: {}
upload:
  dir: ../final
resources:
  tmp:
    dir: ~/scratch
