# Template for single-cell RNA-seq using Illumina prepared samples.
# Michael Steinbaugh
#
# Homo sapiens
# YYYY-MM-DD
#
# Assuming a local run on a 16 core VM.
# bcbio_nextgen_py ../config/bcbio.yaml -t local -n 16
#
# Current FASTA: koopa fasta hsapiens cdna
# Current GTF: koopa gtf hsapiens
#
# Genome build is specific to the bcbio install.
# Run `bcbio_setup_genome.py` for list of genome builds.
#
# Sample barcodes:
# Use the reverse complement (revcomp) with bcbio.
# https://github.com/steinbaugh/koopa/blob/develop/workflows/bcbio/data/umis
#
# More template examples:
# https://github.com/bcbio/bcbio-nextgen/tree/master/config/templates
#
# Configuration documentation:
# https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html
---
details:
  - analysis: scRNA-seq
    genome_build: hg38
    algorithm:
      # Note that bcbio uses "indrop" instead of "indrops" spelling.
      umi_type: harvard-indrop-v3
      
      # Specify sample barcodes for multiplexed FASTQs.
      # Note that you need to define the reverse complement sequences here.
      # inDrops v3: https://github.com/steinbaugh/koopa/blob/master/workflows/indrops/harvard_v3_sample_barcodes.csv
      # For bcbioSingleCell R package, use the forward sequences instead.
      # This is clearer in reports and what NIH prefers for GEO submissions.
      sample_barcodes: sample_barcodes_reverse_complement.txt
      
      # RapMap is the default quantifier.
      # Note that specifying this can cause some older bcbio releases to error.
      singlecell_quantifier: rapmap
      
      # Barcode correction is enabled by default, and is recommended.
      cellular_barcode_correction: 1
      
      # Note that the bcbio documentation suggests using a cutoff of 10,000.
      # This is often too high for inDrops data sets.
      # I recommend setting a lower threshold and filtering instead in R.
      minimum_barcode_depth: 1000
      
      # Uncomment if you want to use a custom FASTA/GTF combo.
      # transcriptome_fasta: Homo_sapiens.GRCh38.cdna.all.fa
      # transcriptome_gtf: Homo_sapiens.GRCh38.95.gtf

# Where to upload (save) the final output.
upload:
  dir: ../final

# Recommended run-specific resources.
# Disable when using IPython/slurm (e.g. HMS O2 cluster).
resources:
  default:
    cores: 16
  tmp:
    dir: ~/scratch
