#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

os_type="$(_koopa_os_type)"

# Only allow install on RHEL 7.
if [[ "$os_type" != "rhel7" ]]
then
    _koopa_stop "RHEL 7 is required."
fi

# Check if EPEL is already enabled.
if sudo yum repolist | grep -q "epel/"
then
    _koopa_note "EPEL 7 is already enabled."
    exit 0
fi

sudo yum install -y \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

sudo yum-config-manager --enable epel

# Here's how to disable, for reference.
# > sudo yum-config-manager --disable epel

sudo yum -y install epel-release
