#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_no_args "$@"
_koopa_assert_has_sudo

# Note that LLVM 7 is required to install llvmlite Python module.
# This is now required to install umap-learn.

enable-epel-7
install-fedora-base
sudo yum -y install \
    'llvm7*' \
    file-devel \
    libgit2-devel \
    libssh2-devel \
    llvm \
    llvm-devel \
    sshpass \
    udunits2-devel

# Now using conda to manage Pandoc instead.
# > sudo yum -y install pandoc pandoc-citeproc
