#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_acid_assert_has_no_args "$@"


name="rstudio-server"
tmp_dir="$(_acid_tmp_dir)/${name}"
version="$(_acid_variable "$name")"

_acid_message "Installing ${name} ${version}."

# Remove existing config files.
# > sudo rm -frv /etc/rstudio

(
    rm -fr "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="${name}-rhel-${version}-x86_64.rpm"
    url="https://download2.rstudio.org/server/centos6/x86_64/${file}"
    _acid_download "$url"
    sudo yum -y install "$file"
    rm -fr "$tmp_dir"
)

# > sudo "$name" stop
# > sudo "$name" verify-installation
# > sudo "$name" start
# > sudo "$name" status

command -v "$name"
"$name" version
