#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install Docker Community Edition.

$(_koopa_help_args)

details:
    Note that Fedora 28+ is required to use recommended new 'dnf' approach.

see also:
    - https://docs.docker.com/install/linux/docker-ce/fedora/
    - https://docs.docker.com/install/linux/docker-ce/centos/

note:
    Bash script.
    Updated 2019-09-26.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

# Remove legacy versions, if necessary.
sudo yum -y remove \
    docker \
    docker-client \
    docker-client-latest \
    docker-common \
    docker-engine \
    docker-latest \
    docker-latest-logrotate \
    docker-logrotate

sudo yum -y install \
    device-mapper-persistent-data \
    lvm2 \
    yum-utils

sudo yum-config-manager \
    --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum repolist

sudo yum install -y containerd.io
sudo yum -y install docker-ce docker-ce-cli

# Note that the docker group is created automatically.
sudo gpasswd -a "$USER" docker

# Ready to start Docker.
sudo systemctl start docker

docker --version
command -v docker
