#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo
_koopa_assert_has_no_args "$@"

# Remove legacy versions, if necessary.
sudo yum -y remove \
    docker \
    docker-client \
    docker-client-latest \
    docker-common \
    docker-engine \
    docker-latest \
    docker-latest-logrotate \
    docker-logrotate

sudo yum -y install \
    device-mapper-persistent-data \
    lvm2 \
    yum-utils

sudo yum-config-manager \
    --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum repolist

sudo yum -y install containerd.io
sudo yum -y install docker-ce docker-ce-cli

# Note that the docker group is created automatically.
sudo gpasswd -a "$USER" docker

# Ready to start Docker.
sudo systemctl start docker

docker --version
command -v docker
