#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_acid_assert_has_sudo

sudo yum -y install gdal gdal-devel
sudo yum-builddep -y gdal

# shellcheck source=/dev/null
source "$(_acid_cellar_script gdal)"
