#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"


sudo yum install -y openssl
sudo yum-builddep -y openssl

# shellcheck source=/dev/null
source "$(_acid_cellar_script openssl)"
