#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_kookpa_assert_has_no_args "$@"
_acid_assert_has_sudo

name="shiny-server"
tmp_dir="$(_acid_tmp_dir)/${name}"
version="$(_acid_variable "$name")"

_acid_message "Installing ${name} ${version}."

(
    rm -fr "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    sudo su - -c \
        "R -e \"install.packages('shiny', repos='https://cran.rstudio.com/')\""
    file="shiny-server-${version}-x86_64.rpm"
    url="https://download3.rstudio.org/centos6.3/x86_64/${file}"
    _acid_download "$url"
    sudo yum install -y --nogpgcheck "$file"
    rm -fr "$tmp_dir"
)

command -v "$name"
"$name" --version
