#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_no_args "$@"
_koopa_assert_has_sudo

name="rstudio-server-pro"
tmp_dir="$(_koopa_tmp_dir)/${name}"
version="$(_koopa_variable "$name")"

_koopa_message "Installing ${name} ${version}."

# Remove existing config files.
# > sudo rm -frv /etc/rstudio

(
    rm -fr "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="rstudio-server-rhel-pro-${version}-x86_64.rpm"
    url="https://download2.rstudio.org/server/centos6/x86_64/${file}"
    _koopa_download "$url"
    sudo yum -y install "$file"
    rm -fr "$tmp_dir"
)

# > sudo "$name" stop
# > sudo "$name" verify-installation
# > sudo "$name" start
# > sudo "$name" status
# > sudo "$name" license-manager status

command -v rstudio-server
rstudio-server version
rstudio-server license-manager verify

cat << EOF
Activate product license key (if necessary):
> sudo rstudio-server license-manager activate <product-key>

If you want to move your license of RStudio Server to another system you should
first deactivate it on the old system with the command:
> sudo rstudio-server license-manager deactivate
EOF

