#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Notes                                                                     {{{1
# ==============================================================================

# Missing on RHEL 7:
# > sudo yum install coin-or-Clp
# https://github.com/coin-or/Clp



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install base programs for Red Hat Enterprise Linux (RHEL) 7.

$(_koopa_help_args)

see also:
    https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/

note:
    Bash script.
    Updated 2019-10-21.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

enable-epel-7
install-fedora-base
sudo yum -y install \
    file-devel \
    libgit2-devel \
    libssh2-devel \
    llvm \
    llvm-devel \
    llvm7.0 \
    pandoc \
    pandoc-citeproc \
    sshpass \
    udunits2-devel
