#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

sudo yum install -y gsl-devel
sudo yum-builddep -y gsl-devel

_acid_cellar_script gsl
