#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo

sudo yum install -y gsl-devel
sudo yum-builddep -y gsl-devel

# shellcheck source=/dev/null
source "$(_koopa_cellar_script gsl)"
