#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

sudo yum install -y gnupg2
sudo yum-builddep -y gnupg2

# shellcheck source=/dev/null
source "$(_acid_cellar_script gnupg)"
