#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_acid_assert_has_no_args "$@"




# R                                                                         {{{1
# ==============================================================================

_acid_message "\
Removing R.
Use the newer R installation at '/usr/local/lib64/R' instead."

sudo yum -y remove \
    'R' \
    'R-*' \
    'libRmath' \
    'libRmath-devel'
sudo rm -frv /usr/lib64/R



# Java                                                                      {{{1
# ==============================================================================

_acid_message "\
Removing Java.
Use the newer JDK installation at '/opt/jdk' instead."

sudo yum -y remove \
    '*-openjdk*' \
    'java-*'
sudo rm -frv /usr/lib/jvm/*



# Pandoc                                                                    {{{1
# ==============================================================================

# > _acid_message "\
# > Removing Pandoc.
# > Use conda version instead."
# >
# > sudo yum -y remove \
# >     '*-pandoc' \
# >     '*-pandoc-*' \
# >     'pandoc' \
# >     'pandoc-*'



# Perl                                                                      {{{1
# ==============================================================================

_acid_message "\
Removing Perl CPAN Minus.
Use Perlbrew approach instead."

sudo yum -y remove \
    'perl-App-cpanminus'



# Python                                                                    {{{1
# ==============================================================================

# Uma installed this on VM44.

_acid_message "\
Removing Python 3 yum install.
Install from source using cellar script instead."

sudo yum -y remove 'python3*'

# Use a newer version of pip in a virtual environment instead.

# Remove system pip, if necessary.
# > /usr/bin/pip uninstall pip

# Uninstalling pip-8.1.2:
#   /usr/bin/pip
#   /usr/bin/pip2
#   /usr/bin/pip2.7
#   /usr/lib/python2.7/site-packages/pip
#   /usr/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg-info

_acid_message "\
Removing Python system pip.
Use venv to manage packages instead."

sudo rm -frv \
    '/usr/bin/pip' \
    '/usr/bin/pip2' \
    '/usr/bin/pip2.7' \
    '/usr/lib/python2.7/site-packages/pip' \
    '/usr/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg-info'



# Rust                                                                      {{{1
# ==============================================================================

_acid_message "\
Removing Rust.
Use rustup installation instead."

sudo yum -y remove 'rust-*'



# Tex Live                                                                  {{{1
# ==============================================================================

# > _acid_message "\
# > Removing TeX Live.
# > Use conda version instead at '/usr/local/miniconda3/envs/texlive-core'."
# >
# > sudo yum -y remove \
# >     '*-tex' \
# >     'latex2html' \
# >     'texi2html' \
# >     'texlive' \
# >     'texlive-*'
