#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Remove legacy RHEL 7 RPM cruft on Azure VMs.

note:
    Bash script.
    Updated 2019-10-23.
EOF
}

_koopa_help "$@"
_koopa_assert_has_no_args "$@"



# Script                                                                    {{{1
# ==============================================================================

# R                                                                         {{{2
# ------------------------------------------------------------------------------

_koopa_message "\
Removing R.
Use the newer R installation at '/usr/local/lib64/R' instead."

sudo yum remove \
    'R' \
    'R-*' \
    'libRmath' \
    'libRmath-devel'
sudo rm -frv /usr/lib64/R

# Java                                                                      {{{2
# ------------------------------------------------------------------------------

_koopa_message "\
Removing Java.
Use the newer JDK installation at '/opt/jdk' instead."

sudo yum remove \
    '*-openjdk*' \
    'java-*'

# Pandoc                                                                    {{{2
# ------------------------------------------------------------------------------

_koopa_message "\
Removing Pandoc.
Use conda version instead at '/usr/local/miniconda3/envs/pandoc'."

sudo yum remove \
    '*-pandoc' \
    '*-pandoc-*' \
    'pandoc' \
    'pandoc-*'

# Perl                                                                      {{{2
# ------------------------------------------------------------------------------

_koopa_message "\
Removing Perl CPAN Minus.
Use Perlbrew approach instead."

sudo yum remove \
    'perl-App-cpanminus'

# Python                                                                    {{{2
# ------------------------------------------------------------------------------

# Use a newer version of pip in a virtual environment instead.

# Remove system pip, if necessary.
# > /usr/bin/pip uninstall pip

# Uninstalling pip-8.1.2:
#   /usr/bin/pip
#   /usr/bin/pip2
#   /usr/bin/pip2.7
#   /usr/lib/python2.7/site-packages/pip
#   /usr/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg-info

_koopa_message "\
Removing Python system pip.
Use venv to manage packages instead."

sudo rm -frv \
    '/usr/bin/pip' \
    '/usr/bin/pip2' \
    '/usr/bin/pip2.7' \
    '/usr/lib/python2.7/site-packages/pip' \
    '/usr/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg-info'

# Rust                                                                      {{{2
# ------------------------------------------------------------------------------

_koopa_message "\
Removing Rust.
Use rustup installation instead."

sudo yum remove 'rust-*'

# Tex Live                                                                  {{{2
# ------------------------------------------------------------------------------

# > _koopa_message "\
# > Removing TeX Live.
# > Use conda version instead at '/usr/local/miniconda3/envs/texlive-core'."
# >
# > sudo yum remove \
# >     '*-tex' \
# >     'latex2html' \
# >     'texi2html' \
# >     'texlive' \
# >     'texlive-*'
