---
# List of custom programs to install that are not packaged. These each require
# a install_name function in the appropriate place in the 'custom' directory to
# define the steps for downloading, building, and installing the package.
bio_general:
 #- bio4j # no easy download for 0.8
 - anaconda
 - emboss
 - pgdspider
bio_nextgen:
  alignment:
    - bowtie
    - gmap
    - lastz
    - mosaik
    # - perm # difficult build process with directory names
    - snap
    #- stampy # no version names on tarballs
  utilities:
    - dwgsim
    - fastq_screen
    - ogap
    - rnaseqc
    - varianttools
    - disambiguate
    - alientrimmer
  analysis:
    # - echo # build problems on ubuntu 12.10
    - picard
    - shrec
    - tophat
    - featurecounts
  assembly:
    - abyss
    - cortex_var
    - ray
    - transabyss
    - trinity
    - velvet
  sv:
    - hydra
    - freec
  variant:
    - bcbio_variation
    - crisp
    - grabix
    - mutect
    - tassel
    - stacks
    - varscan
  chip:
    - macs
  needs_64bit:
    - ucsc_tools
    - bfast
bio_proteomics:
  - transproteomic_pipeline
  - omssa
  - mzmine
  - myrimatch
  - directag
  - tagrecon
  - idpqonvert
  - pepitome
  - percolator
bio_proteomics_wine:
  - proteomics_wine_env
  #- multiplierz
  - proteowizard
  - morpheus
cloudman:
  - cloudman
  - novnc
galaxy:
  - galaxy_webapp
galaxy_tools:
  - cbl_galaxy_tools
galaxyp:
  - galaxy_protk
  - protvis
# Pydoop and seal need update and should only be installed on cloud systems
#distributed:
#  - pydoop
#  - seal
system:
  - homebrew
  - s3fs
python:
  - bx-python
  - netsa-python
  - rpy
java:
  - leiningen
phylogeny:
  - tracer
  - beast
#Viral Cloud Resource (VCR) - JCVI's Viral Genomic Pipelines on the cloud
vcr:
  - galaxy_vcr
  - viralassembly
  - viralassembly_cleanall
  - viralvigor
  - viralvigor_test
  - viralvigor_validate
  - viralvigor_cleanall
  - vicvb
  - vicvb_cleanall
# ToDo -- test on 64bit with bfast
#- dnaa
#- srma
