"""Generate and verify cross-harness agent configuration adapters.

Skills and rules are authored once under ``.agents/``: ``.agents/skills/`` and
``.agents/rules/``. ``.claude/skills`` and ``.claude/rules`` are directory
symlinks onto those two trees, for Claude Code and VS Code Copilot. This
module generates the remaining per-vendor adapters that have no symlink
equivalent -- Copilot's ``.github/instructions/*.instructions.md`` files
(derived from each rule's ``paths:`` frontmatter) and the Claude/Gemini
plugin manifests (derived from the canonical ``plugins/koopa/plugin.json``,
an Agent Plugins 1.0 package identity) -- and checks that the whole layout
matches the conventions documented in AGENTS.md's "Agent configuration"
section.

Backs ``koopa develop generate-agent-config``.
"""

import json
import os
from dataclasses import dataclass
from pathlib import Path

_RULE_PREFIX = "koopa-"
_GENERATED_MARKER_PREFIX = "<!-- Generated by 'koopa develop generate-agent-config'"
_SCHEMA_URL = "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json"


@dataclass(frozen=True)
class Rule:
    """One parsed ``.agents/rules/koopa-*.md`` rule file.

    Parameters
    ----------
    source : Path
        Path to the rule file.
    paths : tuple[str, ...]
        Glob patterns from the ``paths:`` frontmatter key, in file order.
        Empty if the file has no frontmatter (always-loaded rule).
    title : str
        First ``# `` heading in the body, used as the Copilot adapter's
        ``description:`` value.
    body : str
        Rule content after the frontmatter block, with leading blank lines
        stripped and a single trailing newline.
    """

    source: Path
    paths: tuple[str, ...]
    title: str
    body: str


def parse_rule(path: Path) -> Rule:
    """Parse one rule file's ``paths:`` frontmatter, title, and body.

    Parameters
    ----------
    path : Path
        Path to a ``.agents/rules/koopa-*.md`` file.

    Returns
    -------
    Rule
        The parsed rule.

    Raises
    ------
    ValueError
        If the frontmatter block is unterminated, declares a key other than
        ``paths:``, or the file has no body heading to use as a title.
    """
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    paths: list[str] = []
    body_lines = lines

    if lines and lines[0].strip() == "---":
        end = None
        for i, line in enumerate(lines[1:], start=1):
            if line.strip() == "---":
                end = i
                break
        if end is None:
            msg = f"{path}: unterminated frontmatter block."
            raise ValueError(msg)
        frontmatter = lines[1:end]
        body_lines = lines[end + 1 :]

        i = 0
        while i < len(frontmatter):
            stripped = frontmatter[i].strip()
            if not stripped:
                i += 1
                continue
            if stripped != "paths:":
                msg = f"{path}: unsupported frontmatter key {stripped!r}; only 'paths:' is allowed."
                raise ValueError(msg)
            i += 1
            while i < len(frontmatter) and frontmatter[i].strip().startswith("-"):
                item = frontmatter[i].strip()[1:].strip().strip('"')
                paths.append(item)
                i += 1

    body = "\n".join(body_lines).lstrip("\n")
    if body and not body.endswith("\n"):
        body += "\n"

    title = ""
    for line in body.splitlines():
        if line.startswith("# "):
            title = line[2:].strip()
            break
    if not title:
        msg = f"{path}: no '# Title' heading found to use as the Copilot description."
        raise ValueError(msg)

    return Rule(source=path, paths=tuple(paths), title=title, body=body)


def apply_to(paths: tuple[str, ...]) -> str:
    """Join rule globs into a Copilot ``applyTo:`` string.

    Parameters
    ----------
    paths : tuple[str, ...]
        Glob patterns in frontmatter order.

    Returns
    -------
    str
        Comma-joined globs, in order, with no sorting or deduplication.
        ``"**"`` if `paths` is empty (an always-loaded rule).

    Raises
    ------
    ValueError
        If a glob contains a comma or a double quote: ``applyTo`` is one
        comma-separated string, and either character would make the join
        ambiguous or break the YAML frontmatter's quoting.
    """
    if not paths:
        return "**"
    for glob in paths:
        if "," in glob or '"' in glob:
            msg = f"glob {glob!r} cannot be expressed as a comma-separated applyTo string."
            raise ValueError(msg)
    return ",".join(paths)


def build_copilot_instruction(rule: Rule) -> str:
    """Render one rule as a Copilot ``*.instructions.md`` adapter.

    Parameters
    ----------
    rule : Rule
        Parsed rule to render.

    Returns
    -------
    str
        Full file content: YAML frontmatter (``applyTo``, ``description``),
        a generated-file marker, then the rule body verbatim. The YAML
        frontmatter is written first and the marker placed after it, since
        Copilot requires the frontmatter to open the file.
    """
    header = (
        "---\n"
        f"applyTo: {json.dumps(apply_to(rule.paths))}\n"
        f"description: {json.dumps(rule.title)}\n"
        "---\n"
        "\n"
        f"{_GENERATED_MARKER_PREFIX} from .agents/rules/{rule.source.name}. "
        "Do not edit; edit the source and regenerate. -->\n"
        "\n"
    )
    return header + rule.body


def build_claude_plugin(plugin: dict) -> dict:
    """Derive the Claude plugin-manifest adapter from the canonical manifest.

    Parameters
    ----------
    plugin : dict
        Parsed canonical ``plugins/koopa/plugin.json`` (Agent Plugins 1.0).

    Returns
    -------
    dict
        Content for ``plugins/koopa/.claude-plugin/plugin.json``.
    """
    return {
        "name": plugin["name"],
        "displayName": plugin["name"],
        "version": plugin["version"],
        "description": plugin["description"],
        "author": plugin["author"],
        "license": plugin["license"],
        "homepage": plugin["homepage"],
        "repository": plugin["repository"],
        "keywords": plugin["keywords"],
        "skills": "./skills/",
    }


def build_gemini_extension(plugin: dict) -> dict:
    """Derive the Gemini extension manifest from the canonical manifest.

    Parameters
    ----------
    plugin : dict
        Parsed canonical ``plugins/koopa/plugin.json`` (Agent Plugins 1.0).

    Returns
    -------
    dict
        Content for ``plugins/koopa/gemini-extension.json``.
    """
    return {
        "name": plugin["name"],
        "version": plugin["version"],
        "description": plugin["description"],
    }


def render_json(obj: dict) -> str:
    """Render a dict as 2-space-indented JSON with one trailing newline.

    Parameters
    ----------
    obj : dict
        Object to serialize.

    Returns
    -------
    str
        JSON text ending in a single newline.
    """
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def layout_errors(root: Path) -> list[str]:
    """Check the repository's agent-config layout invariants.

    Parameters
    ----------
    root : Path
        Repository root.

    Returns
    -------
    list[str]
        One message per violated invariant; empty if the layout is sound.
    """
    errors: list[str] = []

    def _require_real_dir(rel: str) -> None:
        path = root / rel
        if os.path.islink(path):
            errors.append(f"{rel} must be a real directory, not a symlink.")
        elif not path.is_dir():
            errors.append(f"{rel} is missing.")

    def _require_symlink(rel: str, target: str) -> None:
        path = root / rel
        if not os.path.islink(path):
            errors.append(f"{rel} must be a symlink to {target!r}.")
            return
        actual = os.readlink(path)
        if actual != target:
            errors.append(f"{rel} must point to {target!r}, points to {actual!r}.")

    _require_real_dir(".agents/skills")
    _require_real_dir(".agents/rules")
    if os.path.islink(root / ".claude"):
        errors.append(".claude must be a real directory, not a symlink.")
    _require_symlink(".claude/skills", "../.agents/skills")
    _require_symlink(".claude/rules", "../.agents/rules")

    plugin_dir = root / "plugins" / "koopa"
    if plugin_dir.is_dir():
        for path in plugin_dir.rglob("*"):
            if os.path.islink(path):
                errors.append(f"{path.relative_to(root)} must not be a symlink.")

    for legacy in (
        ".github/copilot-instructions.md",
        "plugins/koopa/.github/plugin/plugin.json",
    ):
        if (root / legacy).exists():
            errors.append(f"{legacy} is a legacy file; delete it.")

    plugin_path = plugin_dir / "plugin.json"
    pyproject_path = root / "pyproject.toml"
    marketplace_path = root / ".claude-plugin" / "marketplace.json"
    if plugin_path.is_file() and pyproject_path.is_file() and marketplace_path.is_file():
        import tomllib

        plugin = json.loads(plugin_path.read_text(encoding="utf-8"))
        with open(pyproject_path, "rb") as fh:
            pyproject = tomllib.load(fh)
        marketplace = json.loads(marketplace_path.read_text(encoding="utf-8"))

        if plugin.get("$schema") != _SCHEMA_URL:
            errors.append(f"plugins/koopa/plugin.json: '$schema' must be {_SCHEMA_URL!r}.")

        plugin_version = plugin.get("version")
        pyproject_version = pyproject.get("project", {}).get("version")
        marketplace_version = marketplace.get("metadata", {}).get("version")
        if plugin_version != pyproject_version:
            errors.append(
                f"plugins/koopa/plugin.json version {plugin_version!r} != "
                f"pyproject.toml project.version {pyproject_version!r}."
            )
        if plugin_version != marketplace_version:
            errors.append(
                f"plugins/koopa/plugin.json version {plugin_version!r} != "
                f".claude-plugin/marketplace.json metadata.version {marketplace_version!r}."
            )

        plugin_name = plugin.get("name", "")
        marketplace_names = [entry.get("name") for entry in marketplace.get("plugins", [])]
        if plugin_name not in marketplace_names:
            errors.append(
                f".claude-plugin/marketplace.json does not list a plugin named {plugin_name!r}."
            )

    rules_dir = root / ".agents" / "rules"
    if rules_dir.is_dir():
        for path in sorted(rules_dir.glob("*.md")):
            if not path.name.startswith(_RULE_PREFIX):
                errors.append(f"{path.relative_to(root)} must start with {_RULE_PREFIX!r}.")

    agents_dir = root / ".agents" / "agents"
    if agents_dir.is_dir() and any(agents_dir.glob("*.md")):
        errors.append(
            ".agents/agents/*.md found, but subagent adapters are not implemented yet; "
            "see AGENTS.md's Agent configuration section before adding the first one."
        )

    return errors


def expected_outputs(root: Path) -> dict[Path, str]:
    """Compute every file this generator should produce or maintain.

    Parameters
    ----------
    root : Path
        Repository root.

    Returns
    -------
    dict[Path, str]
        Mapping of absolute output path to its expected file content.
    """
    outputs: dict[Path, str] = {}

    rules_dir = root / ".agents" / "rules"
    instructions_dir = root / ".github" / "instructions"
    if rules_dir.is_dir():
        for path in sorted(rules_dir.glob("*.md")):
            rule = parse_rule(path)
            out_path = instructions_dir / f"{path.stem}.instructions.md"
            outputs[out_path] = build_copilot_instruction(rule)

    plugin_path = root / "plugins" / "koopa" / "plugin.json"
    if plugin_path.is_file():
        plugin = json.loads(plugin_path.read_text(encoding="utf-8"))
        outputs[root / "plugins" / "koopa" / ".claude-plugin" / "plugin.json"] = render_json(
            build_claude_plugin(plugin)
        )
        outputs[root / "plugins" / "koopa" / "gemini-extension.json"] = render_json(
            build_gemini_extension(plugin)
        )

    return outputs


def orphan_outputs(root: Path, expected: dict[Path, str]) -> list[Path]:
    """Find generator-owned files that no longer have a canonical source.

    Parameters
    ----------
    root : Path
        Repository root.
    expected : dict[Path, str]
        Output of `expected_outputs`.

    Returns
    -------
    list[Path]
        Stale ``.github/instructions/koopa-*.instructions.md`` files to
        remove. Files outside this generator's ``koopa-*`` namespace (a
        hand-written instructions file, say) are never reported.
    """
    instructions_dir = root / ".github" / "instructions"
    if not instructions_dir.is_dir():
        return []
    owned = sorted(instructions_dir.glob(f"{_RULE_PREFIX}*.instructions.md"))
    return [path for path in owned if path not in expected]


def check(root: Path) -> list[str]:
    """Report every way the agent-config layout and generated files are stale.

    Parameters
    ----------
    root : Path
        Repository root.

    Returns
    -------
    list[str]
        One message per problem; empty if everything is current.
    """
    problems = list(layout_errors(root))
    expected = expected_outputs(root)
    for path, content in sorted(expected.items()):
        if not path.is_file():
            problems.append(f"{path.relative_to(root)} is missing.")
        elif path.read_text(encoding="utf-8") != content:
            problems.append(f"{path.relative_to(root)} is stale.")
    for path in orphan_outputs(root, expected):
        problems.append(f"{path.relative_to(root)} is an orphaned generated file.")
    return problems


def write(root: Path) -> tuple[list[Path], list[Path]]:
    """Write every generated file that is missing or stale, and delete orphans.

    Parameters
    ----------
    root : Path
        Repository root.

    Returns
    -------
    tuple[list[Path], list[Path]]
        ``(written, removed)``, both relative to `root`. A file whose
        content already matches is left untouched (no mtime churn).

    Raises
    ------
    ValueError
        If a layout invariant from `layout_errors` is violated; fix the
        layout before generating.
    """
    layout_problems = layout_errors(root)
    if layout_problems:
        msg = "\n".join(layout_problems)
        raise ValueError(msg)

    expected = expected_outputs(root)
    written: list[Path] = []
    for path, content in sorted(expected.items()):
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path.relative_to(root))

    removed: list[Path] = []
    for path in orphan_outputs(root, expected):
        path.unlink()
        removed.append(path.relative_to(root))

    return written, removed
