"""R package repository management for r.acidgenomics.com.

Cloud-native approach: S3 is the source of truth. No local git repo or drat
package required. Tarballs are uploaded directly; PACKAGES manifests are
regenerated by streaming only the DESCRIPTION file from each tarball and using
S3 ETags (== MD5 for single-part uploads) for checksums.
"""

import gzip
import io
import json
import os
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

_BUCKET = "r-REDACTED_ACCOUNT_ID-us-east-1-an"
_S3_URI = f"s3://{_BUCKET}"
_PROFILE = "acidgenomics"
_CLOUDFRONT_DISTRIBUTION_ID = "REDACTED_CF_DIST_ID"
_INDEX_URL = "https://r.acidgenomics.com/"

# CloudFront paths invalidated after every publish (manifests only — tarballs are immutable).
_CLOUDFRONT_PATHS = [
    "/bin/macosx/sonoma-arm64/contrib/*/PACKAGES*",
    "/src/contrib/PACKAGES*",
]

# Binary prefix where we actively publish. Only the latest macOS (Sequoia) on Apple Silicon.
_ACTIVE_BINARY_PREFIX = "bin/macosx/sonoma-arm64/contrib"

# Skeleton binary prefixes — empty PACKAGES manifests so R clients on these platforms
# fall back to source silently instead of warning about a missing index.
# Add a new entry whenever a new R minor is released.
_SKELETON_BINARY_PREFIXES: list[str] = [
    # big-sur-arm64: historical binaries deleted; keep empty index for older macOS arm64 Macs.
    "bin/macosx/big-sur-arm64/contrib/4.3",
    "bin/macosx/big-sur-arm64/contrib/4.4",
    "bin/macosx/big-sur-arm64/contrib/4.5",
    "bin/macosx/big-sur-arm64/contrib/4.6",
]

# DCF fields written to PACKAGES for source packages (in order).
_SOURCE_FIELDS = [
    "Package",
    "Version",
    "Depends",
    "Imports",
    "Suggests",
    "License",
    "MD5sum",
    "NeedsCompilation",
]

# Additional fields for binary PACKAGES.
_BINARY_EXTRA_FIELDS = ["Built", "File"]

# R script to build source + binary tarballs.
# Sentinels PKG_DIR, BUILD_DIR, and INDEX_URL are replaced before eval.
# BUILD_DIR is a Python-managed temp dir so tarballs survive the R session.
_BUILD_R = """\
stopifnot(requireNamespace("desc", quietly = TRUE))
pkg <- PKG_DIR
td <- BUILD_DIR
descFile <- file.path(pkg, "DESCRIPTION")
stopifnot(file.exists(descFile))
name <- desc::desc_get_field("Package", file = descFile)
version <- desc::desc_get_field("Version", file = descFile)
owd <- setwd(td)
on.exit(setwd(owd), add = TRUE)
R <- file.path(R.home(), "bin", "R")
message(sprintf("Building %s %s.", name, version))
build_args <- c("CMD", "build", "--log", "--md5",
    "--no-build-vignettes", "--no-manual", shQuote(pkg))
system2(R, build_args, stderr = TRUE)
src <- file.path(td, paste0(name, "_", version, ".tar.gz"))
stopifnot(file.exists(src))
if (file.size(src) > 2e6) stop(sprintf("Source package too large: %s", src))
system2(R, c("CMD", "INSTALL", "--build", shQuote(src)), stderr = TRUE)
bin <- file.path(td, paste0(name, "_", version, ".tgz"))
stopifnot(file.exists(bin))
if (file.size(bin) > 5e6) stop(sprintf("Binary package too large: %s", bin))
bin_url <- contrib.url(INDEX_URL, type = "binary")
bin_subpath <- sub(paste0("^", gsub("/$", "", INDEX_URL), "/?"), "", bin_url)
cat(src, bin, bin_subpath, sep = "\\n")
"""

# R one-liner to write PACKAGES.rds from a PACKAGES text file in the same dir.
_WRITE_RDS_R = """\
setwd(DIR)
pkgs <- read.dcf("PACKAGES")
saveRDS(pkgs, "PACKAGES.rds", compress = "xz")
"""


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _aws() -> str:
    """Return path to aws CLI, raising if absent."""
    import shutil

    path = shutil.which("aws")
    if path is None:
        msg = "aws CLI is not installed."
        raise RuntimeError(msg)
    return path


def _load_env_file() -> None:
    """Load variables from <koopa-root>/.env into os.environ if not already set."""
    env_path = Path(__file__).parents[4] / ".env"
    if not env_path.is_file():
        return
    with open(env_path) as fh:
        for raw in fh:
            stripped = raw.strip()
            if not stripped or stripped.startswith("#") or "=" not in stripped:
                continue
            key, _, value = stripped.partition("=")
            key = key.strip()
            value = value.strip()
            if key and key not in os.environ:
                os.environ[key] = value


def _cloudfront_distribution_id() -> str:
    """Return CloudFront distribution ID from environment, with hardcoded fallback."""
    _load_env_file()
    dist_id = os.environ.get("AWS_CLOUDFRONT_DISTRIBUTION_ID_R", "")
    if not dist_id:
        dist_id = os.environ.get("AWS_CLOUDFRONT_DISTRIBUTION_ID", "")
    if not dist_id:
        dist_id = _CLOUDFRONT_DISTRIBUTION_ID
    return dist_id


def _r_quoted(value: str) -> str:
    """Wrap a value in an R double-quoted string literal."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _parse_dcf(text: str) -> dict[str, str]:
    """Parse a single DCF (Debian Control File) record into a dict."""
    record: dict[str, str] = {}
    current_key = ""
    for line in text.splitlines():
        if not line.strip():
            break
        if line.startswith(" ") or line.startswith("\t"):
            if current_key:
                record[current_key] = record[current_key] + " " + line.strip()
        elif ":" in line:
            current_key, _, val = line.partition(":")
            current_key = current_key.strip()
            record[current_key] = val.strip()
    return record


def _extract_description_from_tarball(tarball_bytes: bytes) -> dict[str, str]:
    """Extract and parse DESCRIPTION from an in-memory tarball."""
    with tarfile.open(fileobj=io.BytesIO(tarball_bytes), mode="r:gz") as tf:
        for member in tf.getmembers():
            parts = member.name.split("/")
            if len(parts) == 2 and parts[1] == "DESCRIPTION":
                f = tf.extractfile(member)
                if f is not None:
                    return _parse_dcf(f.read().decode("utf-8", errors="replace"))
    return {}


def _stream_description_from_s3(key: str) -> dict[str, str]:
    """Stream a tarball from S3 and extract only its DESCRIPTION file."""
    aws = _aws()
    result = subprocess.run(
        [aws, "s3", f"--profile={_PROFILE}", "cp", f"{_S3_URI}/{key}", "-"],
        capture_output=True,
        check=True,
    )
    return _extract_description_from_tarball(result.stdout)


def _s3_list_packages(prefix: str) -> list[dict[str, str]]:
    """List package tarballs under a given S3 prefix.

    Returns a list of dicts with 'Key' and 'ETag' (MD5 hex, no quotes).
    Only includes .tar.gz and .tgz files; skips Archive/ subdirs.
    """
    aws = _aws()
    result = subprocess.run(
        [
            aws,
            "s3api",
            "list-objects-v2",
            "--bucket",
            _BUCKET,
            "--prefix",
            prefix.rstrip("/") + "/",
            f"--profile={_PROFILE}",
            "--output",
            "json",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    data = json.loads(result.stdout)
    out = []
    for obj in data.get("Contents", []):
        key = obj["Key"]
        # Skip subdirectories (Archive/) and non-tarball files
        suffix = key.removeprefix(prefix.rstrip("/") + "/")
        if "/" in suffix:
            continue
        if not (suffix.endswith(".tar.gz") or suffix.endswith(".tgz")):
            continue
        etag = obj["ETag"].strip('"')
        out.append({"Key": key, "ETag": etag, "Filename": suffix})
    return out


def _s3_list_binary_prefixes() -> list[str]:
    """Discover all bin/macosx/<platform>/contrib/<Rver>/ prefixes in S3."""
    aws = _aws()
    result = subprocess.run(
        [
            aws,
            "s3api",
            "list-objects-v2",
            "--bucket",
            _BUCKET,
            "--prefix",
            "bin/",
            f"--profile={_PROFILE}",
            "--output",
            "json",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    data = json.loads(result.stdout)
    prefixes: set[str] = set()
    for obj in data.get("Contents", []):
        key = obj["Key"]
        # Match bin/macosx/<platform>/contrib/<Rver>/
        parts = key.split("/")
        if len(parts) >= 6 and parts[0] == "bin" and parts[1] == "macosx" and parts[3] == "contrib":
            prefix = "/".join(parts[:5]) + "/"
            prefixes.add(prefix)
    return sorted(prefixes)


def _build_packages_text(entries: list[dict[str, str]], *, binary: bool = False) -> str:
    """Build the PACKAGES DCF text from a list of entry dicts."""
    fields = _SOURCE_FIELDS + (_BINARY_EXTRA_FIELDS if binary else [])
    blocks = []
    for entry in sorted(entries, key=lambda e: (e.get("Package", ""), e.get("Version", ""))):
        lines = []
        for field in fields:
            val = entry.get(field, "")
            if val:
                lines.append(f"{field}: {val}")
        if lines:
            blocks.append("\n".join(lines))
    return "\n\n".join(blocks) + "\n"


def _upload_manifest(packages_text: str, s3_prefix: str, tmp_dir: str) -> None:
    """Write PACKAGES, PACKAGES.gz, PACKAGES.rds and upload all three to S3."""
    from koopa.r import _r_eval

    aws = _aws()
    pkg_path = os.path.join(tmp_dir, "PACKAGES")
    pkg_gz_path = os.path.join(tmp_dir, "PACKAGES.gz")

    with open(pkg_path, "w") as fh:
        fh.write(packages_text)

    with open(pkg_path, "rb") as f_in, gzip.open(pkg_gz_path, "wb") as f_out:
        f_out.write(f_in.read())

    # PACKAGES.rds must be written by R (it's a serialized R object)
    code = _WRITE_RDS_R.replace("DIR", _r_quoted(tmp_dir))
    _r_eval(code, capture=True)

    prefix = s3_prefix.rstrip("/")
    for filename in ("PACKAGES", "PACKAGES.gz", "PACKAGES.rds"):
        local = os.path.join(tmp_dir, filename)
        s3_key = f"{prefix}/{filename}"
        subprocess.run(
            [
                aws,
                "s3",
                f"--profile={_PROFILE}",
                "cp",
                "--content-type",
                "binary/octet-stream",
                local,
                f"{_S3_URI}/{s3_key}",
            ],
            check=True,
        )


def _reindex_prefix(s3_prefix: str, *, binary: bool = False) -> None:
    """Regenerate and upload PACKAGES manifests for one S3 prefix.

    Streams only the DESCRIPTION file from each tarball — no full downloads.
    Uses S3 ETag as MD5sum (valid for single-part uploads).
    """
    from koopa.alert import alert

    alert(f"Reindexing '{s3_prefix}'.")
    objects = _s3_list_packages(s3_prefix)

    entries = []
    for obj in objects:
        desc = _stream_description_from_s3(obj["Key"])
        if not desc.get("Package"):
            print(f"Warning: no DESCRIPTION found in {obj['Key']!r}", file=sys.stderr)
            continue
        entry = dict(desc)
        entry["MD5sum"] = obj["ETag"]
        if binary:
            entry["File"] = obj["Filename"]
        entries.append(entry)

    # Always write manifests — even when empty. An empty-but-valid PACKAGES file
    # makes R fall back to source silently; a missing file causes a warning.
    packages_text = _build_packages_text(entries, binary=binary)

    with tempfile.TemporaryDirectory() as tmp_dir:
        _upload_manifest(packages_text, s3_prefix, tmp_dir)

    alert(f"Uploaded PACKAGES manifests to '{s3_prefix}' ({len(entries)} packages).")


def _archive_old_source(pkg_name: str, new_filename: str) -> None:
    """Move any existing source tarball for pkg_name to Archive/<pkg_name>/.

    Called before uploading a new version so the old one is preserved, mirroring
    drat's latestOnly=TRUE + archivePackages behaviour.
    """
    from koopa.alert import alert

    aws = _aws()
    # List current tarballs for this package in src/contrib/ (exact prefix match)
    result = subprocess.run(
        [
            aws,
            "s3api",
            "list-objects-v2",
            "--bucket",
            _BUCKET,
            "--prefix",
            f"src/contrib/{pkg_name}_",
            f"--profile={_PROFILE}",
            "--output",
            "json",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    data = json.loads(result.stdout)
    for obj in data.get("Contents", []):
        key = obj["Key"]
        filename = key.removeprefix("src/contrib/")
        # Only move .tar.gz files in the flat contrib dir (skip Archive/ entries)
        if "/" in filename or not filename.endswith(".tar.gz"):
            continue
        if filename == new_filename:
            continue
        archive_key = f"src/contrib/Archive/{pkg_name}/{filename}"
        alert(f"Archiving '{filename}' → Archive/{pkg_name}/.")
        subprocess.run(
            [
                aws,
                "s3",
                f"--profile={_PROFILE}",
                "mv",
                f"{_S3_URI}/{key}",
                f"{_S3_URI}/{archive_key}",
            ],
            check=True,
        )


def _upload_package(local_path: str, s3_key: str) -> None:
    """Upload a package tarball to S3."""
    aws = _aws()
    subprocess.run(
        [
            aws,
            "s3",
            f"--profile={_PROFILE}",
            "cp",
            "--content-type",
            "application/x-tar",
            local_path,
            f"{_S3_URI}/{s3_key}",
        ],
        check=True,
    )


def _r_build(package_dir: str, build_dir: str) -> tuple[str, str, str]:
    """Build source + macOS binary tarballs via R CMD build / R CMD INSTALL --build.

    build_dir must be a Python-managed directory that outlives the R session.
    Returns (src_path, bin_path, bin_subpath). The bin_subpath is determined by
    contrib.url(..., type='binary') from the running R, so it's always correct
    for the current platform (e.g. sonoma-arm64/contrib/4.6).
    """
    from koopa.r import _r_eval

    code = (
        _BUILD_R.replace("PKG_DIR", _r_quoted(package_dir))
        .replace("BUILD_DIR", _r_quoted(build_dir))
        .replace("INDEX_URL", _r_quoted(_INDEX_URL))
    )
    result = _r_eval(code, capture=True)
    lines = [ln for ln in result.stdout.splitlines() if ln.strip()]
    if len(lines) < 3:
        msg = f"Expected 3 lines from R build script, got: {result.stdout!r}"
        raise RuntimeError(msg)
    return lines[-3], lines[-2], lines[-1]


def _invalidate_cloudfront() -> None:
    """Invalidate PACKAGES* manifest paths on CloudFront."""
    aws = _aws()
    dist_id = _cloudfront_distribution_id()
    subprocess.run(
        [
            aws,
            "cloudfront",
            "create-invalidation",
            "--distribution-id",
            dist_id,
            "--no-cli-pager",
            "--output",
            "text",
            "--paths",
            *_CLOUDFRONT_PATHS,
            f"--profile={_PROFILE}",
        ],
        check=True,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def publish(
    package_dir: str,
    *,
    check: bool = True,
    deploy: bool = True,
    invalidate: bool = True,
) -> None:
    """Build and publish an R package to r.acidgenomics.com.

    Uploads tarballs directly to S3 and regenerates PACKAGES manifests
    by streaming DESCRIPTION files — no local git repo or drat required.

    Parameters
    ----------
    package_dir
        Path to an R package source directory (must contain DESCRIPTION).
    check
        Run R CMD check --as-cran --no-manual before building.
    deploy
        Upload to S3 and regenerate PACKAGES manifests after building.
    invalidate
        Invalidate CloudFront PACKAGES* caches (only when deploy=True).
    """
    from koopa.alert import alert

    pkg_path = Path(package_dir).expanduser().resolve()
    if not (pkg_path / "DESCRIPTION").is_file():
        msg = f"No DESCRIPTION found in '{pkg_path}'."
        raise FileNotFoundError(msg)

    if check:
        from koopa.r import r_check

        alert(f"Checking '{pkg_path.name}'.")
        r_check(str(pkg_path))

    alert(f"Building '{pkg_path.name}'.")
    with tempfile.TemporaryDirectory(prefix="koopa-r-build-") as build_dir:
        src_path, bin_path, bin_subpath = _r_build(str(pkg_path), build_dir)

        src_base = os.path.basename(src_path)
        bin_base = os.path.basename(bin_path)

        if deploy:
            # Package name from tarball basename: "goalie_0.7.9.tar.gz" → "goalie"
            pkg_name = src_base.rsplit("_", 1)[0]
            src_key = f"src/contrib/{src_base}"
            bin_key = f"{bin_subpath}/{bin_base}"

            alert(f"Archiving previous version of '{pkg_name}' in src/contrib.")
            _archive_old_source(pkg_name, src_base)

            alert(f"Uploading '{src_base}' to s3://{_BUCKET}/{src_key}.")
            _upload_package(src_path, src_key)

            alert(f"Uploading '{bin_base}' to s3://{_BUCKET}/{bin_key}.")
            _upload_package(bin_path, bin_key)

            alert("Regenerating src/contrib PACKAGES manifests.")
            _reindex_prefix("src/contrib", binary=False)

            alert(f"Regenerating {bin_subpath} PACKAGES manifests.")
            _reindex_prefix(bin_subpath, binary=True)

            if invalidate:
                alert("Invalidating CloudFront PACKAGES* caches.")
                _invalidate_cloudfront()

            alert(f"Published '{src_base}' to {_INDEX_URL}")
        else:
            alert(f"Built '{src_base}' and '{bin_base}' (deploy skipped).")


def archive_src(*, invalidate: bool = True) -> None:
    """Move superseded source tarballs in src/contrib/ to Archive/<Pkg>/.

    Groups tarballs by package name, keeps only the latest version of each
    in the flat src/contrib/ directory, and S3-mv's superseded versions to
    src/contrib/Archive/<Pkg>/<filename>. Regenerates PACKAGES manifests
    and optionally invalidates CloudFront.

    Parameters
    ----------
    invalidate
        Invalidate CloudFront PACKAGES* caches after archiving.
    """
    from koopa.alert import alert

    alert("Listing src/contrib packages.")
    objects = _s3_list_packages("src/contrib")
    if not objects:
        alert("No packages found in src/contrib.")
        return

    # Group by package name, collect (version_tuple, filename, key) per package.
    from collections import defaultdict

    groups: dict[str, list[tuple[tuple[int, ...], str, str]]] = defaultdict(list)
    for obj in objects:
        filename = obj["Filename"]
        # Parse "PkgName_X.Y.Z.tar.gz" → name="PkgName", ver=(X,Y,Z)
        stem = filename[: -len(".tar.gz")]
        parts = stem.rsplit("_", 1)
        if len(parts) != 2:
            continue
        pkg_name, ver_str = parts
        try:
            ver_tuple = tuple(int(x) for x in ver_str.split("."))
        except ValueError:
            continue
        groups[pkg_name].append((ver_tuple, filename, obj["Key"]))

    aws = _aws()
    archived = 0
    for pkg_name, versions in groups.items():
        if len(versions) <= 1:
            continue
        # Sort descending; keep the first (latest), archive the rest.
        versions.sort(key=lambda t: t[0], reverse=True)
        for _, filename, key in versions[1:]:
            archive_key = f"src/contrib/Archive/{pkg_name}/{filename}"
            alert(f"Archiving '{filename}' → Archive/{pkg_name}/.")
            subprocess.run(
                [
                    aws,
                    "s3",
                    f"--profile={_PROFILE}",
                    "mv",
                    f"{_S3_URI}/{key}",
                    f"{_S3_URI}/{archive_key}",
                ],
                check=True,
            )
            archived += 1

    if archived:
        alert(f"Archived {archived} superseded tarball(s). Regenerating manifests.")
        _reindex_prefix("src/contrib", binary=False)
        if invalidate:
            _invalidate_cloudfront()
    else:
        alert("src/contrib is already clean — no superseded versions found.")


def publish_from_github(
    pkg_name: str,
    *,
    org: str = "acidgenomics",
    check: bool = False,
    invalidate: bool = True,
) -> None:
    """Clone an R package from GitHub and publish it to r.acidgenomics.com.

    Clones https://github.com/<org>/<pkg_name> into a temporary directory,
    builds source + binary tarballs, uploads them to S3, and regenerates
    PACKAGES manifests. The clone is cleaned up automatically.

    Parameters
    ----------
    pkg_name
        GitHub repository name (e.g. "r-goalie").
    org
        GitHub organisation. Defaults to "acidgenomics".
    check
        Run R CMD check before building. Off by default for batch builds.
    invalidate
        Invalidate CloudFront PACKAGES* caches after publishing.
    """
    import shutil

    from koopa.alert import alert

    git = shutil.which("git")
    if git is None:
        msg = "git is not installed."
        raise RuntimeError(msg)

    url = f"https://github.com/{org}/{pkg_name}"
    alert(f"Cloning '{url}'.")
    with tempfile.TemporaryDirectory(prefix="koopa-r-clone-") as clone_dir:
        subprocess.run(
            [git, "clone", "--depth=1", url, clone_dir],
            check=True,
        )
        publish(clone_dir, check=check, invalidate=invalidate)


def reindex(*, invalidate: bool = True) -> None:
    """Regenerate all PACKAGES manifests from current S3 bucket contents.

    Reindexes src/contrib (source packages) and the active binary prefix
    (sonoma-arm64/contrib/<Rver> paths found in S3). Also writes empty PACKAGES
    manifests to skeleton prefixes so R clients on those platforms fall back to
    source silently instead of warning about a missing index.

    Parameters
    ----------
    invalidate
        Invalidate CloudFront PACKAGES* caches after reindexing.
    """
    from koopa.alert import alert

    alert("Reindexing src/contrib.")
    _reindex_prefix("src/contrib", binary=False)

    # Active binary prefixes — only sonoma-arm64; discover all R versions present.
    active_prefixes = [
        p.rstrip("/") for p in _s3_list_binary_prefixes() if _ACTIVE_BINARY_PREFIX in p
    ]
    alert(f"Active binary prefixes: {active_prefixes}")
    for prefix in active_prefixes:
        _reindex_prefix(prefix, binary=True)

    # Skeleton prefixes — write empty manifests to suppress R client warnings.
    for prefix in _SKELETON_BINARY_PREFIXES:
        alert(f"Writing empty skeleton PACKAGES for '{prefix}'.")
        with tempfile.TemporaryDirectory() as tmp_dir:
            _upload_manifest("", prefix, tmp_dir)

    if invalidate:
        alert("Invalidating CloudFront PACKAGES* caches.")
        _invalidate_cloudfront()

    alert("Reindex complete.")


def deploy(*, invalidate: bool = True) -> None:
    """Alias for reindex() — kept for CLI symmetry and AcidDevTools compatibility.

    Parameters
    ----------
    invalidate
        Invalidate CloudFront PACKAGES* caches after reindexing.
    """
    reindex(invalidate=invalidate)
