"""R package repository management for r.acidgenomics.com.

Cloud-native approach: S3 is the source of truth. No local git repo or drat
package required. Tarballs are uploaded directly; PACKAGES manifests are
regenerated by streaming only the DESCRIPTION file from each tarball and using
S3 ETags (== MD5 for single-part uploads) for checksums.
"""

import gzip
import io
import json
import os
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

_PROFILE = "acidgenomics"
_INDEX_URL = "https://r.acidgenomics.com/"

# CloudFront paths invalidated after every publish (manifests only — tarballs are immutable).
_CLOUDFRONT_PATHS = [
    "/bin/macosx/sonoma-arm64/contrib/*/PACKAGES*",
    "/src/contrib/PACKAGES*",
]

# Binary prefix where we actively publish. Only the latest macOS (Sequoia) on Apple Silicon.
_ACTIVE_BINARY_PREFIX = "bin/macosx/sonoma-arm64/contrib"

# Skeleton binary prefixes — empty PACKAGES manifests so R clients on these platforms
# fall back to source silently instead of warning about a missing index.
# Add a new entry whenever a new R minor is released.
_SKELETON_BINARY_PREFIXES: list[str] = [
    # big-sur-arm64: historical binaries deleted; keep empty index for older macOS arm64 Macs.
    "bin/macosx/big-sur-arm64/contrib/4.3",
    "bin/macosx/big-sur-arm64/contrib/4.4",
    "bin/macosx/big-sur-arm64/contrib/4.5",
    "bin/macosx/big-sur-arm64/contrib/4.6",
]

# Top-level prefixes reserved for package artifacts/assets; a pkgdown docs
# directory name must not collide with any of these.
_RESERVED_PREFIXES = {"bin", "css", "extdata", "images", "packages", "src", "testdata"}

# Docs path template for the landing page, relative to the bucket root.
# Post-migration form; was "packages/{name}/" before publish_docs() moved to
# syncing docs at s3://<r-bucket>/<name>/ directly.
_DOCS_PATH = "{name}/"

# Curated sections for the generated landing page, in display order. Any
# src/contrib package absent from every list here is appended to
# "Infrastructure" with a warning, so a newly published package can never
# silently vanish from the page.
_CATEGORIES: list[tuple[str, list[str]]] = [
    ("Import/export", ["pipette", "acidgenomes", "acidplyr", "goalie", "syntactic"]),
    ("Visualization", ["acidplots"]),
    ("RNA sequencing", ["deseqanalysis", "acidgsea", "acidexperiment"]),
    ("Single-cell RNA sequencing", ["pointillism", "chromium", "acidsinglecell"]),
    ("Annotation databases", ["cellosaurus", "eggnog", "panther", "wormbase"]),
    (
        "Infrastructure",
        [
            "basejump",
            "acidbase",
            "acidcli",
            "acidgenerics",
            "acidmarkdown",
            "acidroxygen",
            "acidtest",
            "aciddevtools",
        ],
    ),
]

# DCF fields written to PACKAGES for source packages (in order).
_SOURCE_FIELDS = [
    "Package",
    "Version",
    "Depends",
    "Imports",
    "Suggests",
    "License",
    "MD5sum",
    "NeedsCompilation",
]

# Additional fields for binary PACKAGES.
_BINARY_EXTRA_FIELDS = ["Built", "File"]

# R script to build source + binary tarballs.
# Sentinels PKG_DIR, BUILD_DIR, and INDEX_URL are replaced before eval.
# BUILD_DIR is a Python-managed temp dir so tarballs survive the R session.
_BUILD_R = """\
stopifnot(requireNamespace("desc", quietly = TRUE))
pkg <- PKG_DIR
td <- BUILD_DIR
descFile <- file.path(pkg, "DESCRIPTION")
stopifnot(file.exists(descFile))
name <- desc::desc_get_field("Package", file = descFile)
version <- desc::desc_get_field("Version", file = descFile)
owd <- setwd(td)
on.exit(setwd(owd), add = TRUE)
R <- file.path(R.home(), "bin", "R")
message(sprintf("Building %s %s.", name, version))
build_args <- c("CMD", "build", "--log", "--md5",
    "--no-build-vignettes", "--no-manual", shQuote(pkg))
system2(R, build_args)
src <- file.path(td, paste0(name, "_", version, ".tar.gz"))
stopifnot(file.exists(src))
repos <- c(INDEX_URL, if (requireNamespace("BiocManager", quietly=TRUE))
    BiocManager::repositories() else c(CRAN="https://cloud.r-project.org"))
deps <- desc::desc_get_deps(file = descFile)
deps <- deps[deps[["type"]] %in% c("Imports", "Depends"), "package"]
deps <- setdiff(deps, c("R", name))
if (length(deps) > 0L) {
    message(sprintf("Installing %d missing dependencies.", length(deps)))
    install.packages(deps, repos = repos)
}
system2(R, c("CMD", "INSTALL", "--build", shQuote(src)))
bin_expected <- file.path(td, paste0(name, "_", version, ".tgz"))
bin_candidates <- list.files(c(td, getwd()), pattern = "[.]tgz$", full.names = TRUE)
bin <- if (file.exists(bin_expected)) bin_expected else {
    if (length(bin_candidates) > 0L) bin_candidates[[1L]] else bin_expected
}
stopifnot(file.exists(bin))
bin_url <- contrib.url(INDEX_URL, type = "binary")
bin_subpath <- sub(paste0("^", gsub("/$", "", INDEX_URL), "/?"), "", bin_url)
cat(src, bin, bin_subpath, sep = "\\n")
"""

# R one-liner to write PACKAGES.rds from a PACKAGES text file in the same dir.
_WRITE_RDS_R = """\
setwd(DIR)
pkgs <- read.dcf("PACKAGES")
saveRDS(pkgs, "PACKAGES.rds", compress = "xz")
"""

# R script to build a pkgdown site. Sentinel PKG_DIR is replaced before eval.
_BUILD_DOCS_R = """\
stopifnot(requireNamespace("pkgdown", quietly = TRUE))
pkgdown::build_site(pkg = PKG_DIR, preview = FALSE)
"""


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _aws() -> str:
    """Return path to aws CLI, raising if absent."""
    import shutil

    path = shutil.which("aws")
    if path is None:
        msg = "aws CLI is not installed."
        raise RuntimeError(msg)
    return path


def _bucket() -> str:
    """Return the R package S3 bucket name (loaded from environment)."""
    from koopa.aws import koopa_s3_bucket

    return koopa_s3_bucket("r")


def _s3_uri() -> str:
    """Return the S3 URI prefix for the R package bucket."""
    return f"s3://{_bucket()}"


def _cloudfront_distribution_id() -> str:
    """Return CloudFront distribution ID from environment, raising if absent."""
    from koopa.aws import load_dotenv

    load_dotenv()
    dist_id = os.environ.get("AWS_CLOUDFRONT_DISTRIBUTION_ID_R", "")
    if not dist_id:
        dist_id = os.environ.get("AWS_CLOUDFRONT_DISTRIBUTION_ID", "")
    if not dist_id:
        msg = "AWS_CLOUDFRONT_DISTRIBUTION_ID_R (or AWS_CLOUDFRONT_DISTRIBUTION_ID) must be set."
        raise RuntimeError(msg)
    return dist_id


def _r_quoted(value: str) -> str:
    """Wrap a value in an R double-quoted string literal."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _parse_dcf(text: str) -> dict[str, str]:
    """Parse a single DCF (Debian Control File) record into a dict."""
    record: dict[str, str] = {}
    current_key = ""
    for line in text.splitlines():
        if not line.strip():
            break
        if line.startswith(" ") or line.startswith("\t"):
            if current_key:
                record[current_key] = record[current_key] + " " + line.strip()
        elif ":" in line:
            current_key, _, val = line.partition(":")
            current_key = current_key.strip()
            record[current_key] = val.strip()
    return record


def _extract_description_from_tarball(tarball_bytes: bytes) -> dict[str, str]:
    """Extract and parse DESCRIPTION from an in-memory tarball."""
    with tarfile.open(fileobj=io.BytesIO(tarball_bytes), mode="r:gz") as tf:
        for member in tf.getmembers():
            parts = member.name.split("/")
            if len(parts) == 2 and parts[1] == "DESCRIPTION":
                f = tf.extractfile(member)
                if f is not None:
                    return _parse_dcf(f.read().decode("utf-8", errors="replace"))
    return {}


def _stream_description_from_s3(key: str) -> dict[str, str]:
    """Stream a tarball from S3 and extract only its DESCRIPTION file."""
    aws = _aws()
    result = subprocess.run(
        [aws, "s3", f"--profile={_PROFILE}", "cp", f"{_s3_uri()}/{key}", "-"],
        capture_output=True,
        check=True,
    )
    return _extract_description_from_tarball(result.stdout)


def _s3_list_packages(prefix: str) -> list[dict[str, str]]:
    """List package tarballs under a given S3 prefix.

    Returns a list of dicts with 'Key' and 'ETag' (MD5 hex, no quotes).
    Only includes .tar.gz and .tgz files; skips Archive/ subdirs.
    """
    aws = _aws()
    result = subprocess.run(
        [
            aws,
            "s3api",
            "list-objects-v2",
            "--bucket",
            _bucket(),
            "--prefix",
            prefix.rstrip("/") + "/",
            f"--profile={_PROFILE}",
            "--output",
            "json",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    data = json.loads(result.stdout)
    out = []
    for obj in data.get("Contents", []):
        key = obj["Key"]
        # Skip subdirectories (Archive/) and non-tarball files
        suffix = key.removeprefix(prefix.rstrip("/") + "/")
        if "/" in suffix:
            continue
        if not (suffix.endswith(".tar.gz") or suffix.endswith(".tgz")):
            continue
        etag = obj["ETag"].strip('"')
        out.append({"Key": key, "ETag": etag, "Filename": suffix})
    return out


def _s3_list_binary_prefixes() -> list[str]:
    """Discover all bin/macosx/<platform>/contrib/<Rver>/ prefixes in S3."""
    aws = _aws()
    result = subprocess.run(
        [
            aws,
            "s3api",
            "list-objects-v2",
            "--bucket",
            _bucket(),
            "--prefix",
            "bin/",
            f"--profile={_PROFILE}",
            "--output",
            "json",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    data = json.loads(result.stdout)
    prefixes: set[str] = set()
    for obj in data.get("Contents", []):
        key = obj["Key"]
        # Match bin/macosx/<platform>/contrib/<Rver>/
        parts = key.split("/")
        if len(parts) >= 6 and parts[0] == "bin" and parts[1] == "macosx" and parts[3] == "contrib":
            prefix = "/".join(parts[:5]) + "/"
            prefixes.add(prefix)
    return sorted(prefixes)


def _build_packages_text(entries: list[dict[str, str]], *, binary: bool = False) -> str:
    """Build the PACKAGES DCF text from a list of entry dicts."""
    fields = _SOURCE_FIELDS + (_BINARY_EXTRA_FIELDS if binary else [])
    blocks = []
    for entry in sorted(entries, key=lambda e: (e.get("Package", ""), e.get("Version", ""))):
        lines = []
        for field in fields:
            val = entry.get(field, "")
            if val:
                lines.append(f"{field}: {val}")
        if lines:
            blocks.append("\n".join(lines))
    return "\n\n".join(blocks) + "\n"


def _upload_manifest(packages_text: str, s3_prefix: str, tmp_dir: str) -> None:
    """Write PACKAGES, PACKAGES.gz, PACKAGES.rds and upload all three to S3."""
    from koopa.r import _r_eval

    aws = _aws()
    pkg_path = os.path.join(tmp_dir, "PACKAGES")
    pkg_gz_path = os.path.join(tmp_dir, "PACKAGES.gz")

    with open(pkg_path, "w") as fh:
        fh.write(packages_text)

    with open(pkg_path, "rb") as f_in, gzip.open(pkg_gz_path, "wb") as f_out:
        f_out.write(f_in.read())

    # PACKAGES.rds must be written by R (it's a serialized R object)
    code = _WRITE_RDS_R.replace("DIR", _r_quoted(tmp_dir))
    _r_eval(code, capture=True)

    prefix = s3_prefix.rstrip("/")
    for filename in ("PACKAGES", "PACKAGES.gz", "PACKAGES.rds"):
        local = os.path.join(tmp_dir, filename)
        s3_key = f"{prefix}/{filename}"
        subprocess.run(
            [
                aws,
                "s3",
                f"--profile={_PROFILE}",
                "cp",
                "--content-type",
                "binary/octet-stream",
                local,
                f"{_s3_uri()}/{s3_key}",
            ],
            check=True,
        )


def _reindex_prefix(s3_prefix: str, *, binary: bool = False) -> list[dict[str, str]]:
    """Regenerate and upload PACKAGES manifests for one S3 prefix.

    Streams only the DESCRIPTION file from each tarball — no full downloads.
    Uses S3 ETag as MD5sum (valid for single-part uploads). Returns the parsed
    entries (full DESCRIPTION fields, including Description) so callers such
    as the landing page generator can reuse them without re-streaming.
    """
    from koopa.alert import alert

    alert(f"Reindexing '{s3_prefix}'.")
    objects = _s3_list_packages(s3_prefix)

    entries = []
    for obj in objects:
        desc = _stream_description_from_s3(obj["Key"])
        if not desc.get("Package"):
            print(f"Warning: no DESCRIPTION found in {obj['Key']!r}", file=sys.stderr)
            continue
        entry = dict(desc)
        entry["MD5sum"] = obj["ETag"]
        if binary:
            entry["File"] = obj["Filename"]
        entries.append(entry)

    # Always write manifests — even when empty. An empty-but-valid PACKAGES file
    # makes R fall back to source silently; a missing file causes a warning.
    packages_text = _build_packages_text(entries, binary=binary)

    with tempfile.TemporaryDirectory() as tmp_dir:
        _upload_manifest(packages_text, s3_prefix, tmp_dir)

    alert(f"Uploaded PACKAGES manifests to '{s3_prefix}' ({len(entries)} packages).")
    return entries


def _archive_old_source(pkg_name: str, new_filename: str) -> None:
    """Move any existing source tarball for pkg_name to Archive/<pkg_name>/.

    Called before uploading a new version so the old one is preserved, mirroring
    drat's latestOnly=TRUE + archivePackages behaviour.
    """
    from koopa.alert import alert

    aws = _aws()
    # List current tarballs for this package in src/contrib/ (exact prefix match)
    result = subprocess.run(
        [
            aws,
            "s3api",
            "list-objects-v2",
            "--bucket",
            _bucket(),
            "--prefix",
            f"src/contrib/{pkg_name}_",
            f"--profile={_PROFILE}",
            "--output",
            "json",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    data = json.loads(result.stdout)
    for obj in data.get("Contents", []):
        key = obj["Key"]
        filename = key.removeprefix("src/contrib/")
        # Only move .tar.gz files in the flat contrib dir (skip Archive/ entries)
        if "/" in filename or not filename.endswith(".tar.gz"):
            continue
        if filename == new_filename:
            continue
        archive_key = f"src/contrib/Archive/{pkg_name}/{filename}"
        alert(f"Archiving '{filename}' → Archive/{pkg_name}/.")
        subprocess.run(
            [
                aws,
                "s3",
                f"--profile={_PROFILE}",
                "mv",
                f"{_s3_uri()}/{key}",
                f"{_s3_uri()}/{archive_key}",
            ],
            check=True,
        )


def _upload_package(local_path: str, s3_key: str) -> None:
    """Upload a package tarball to S3."""
    aws = _aws()
    subprocess.run(
        [
            aws,
            "s3",
            f"--profile={_PROFILE}",
            "cp",
            "--content-type",
            "application/x-tar",
            local_path,
            f"{_s3_uri()}/{s3_key}",
        ],
        check=True,
    )


def _r_build(package_dir: str, build_dir: str) -> tuple[str, str, str]:
    """Build source + macOS binary tarballs via R CMD build / R CMD INSTALL --build.

    build_dir must be a Python-managed directory that outlives the R session.
    Returns (src_path, bin_path, bin_subpath). The bin_subpath is determined by
    contrib.url(..., type='binary') from the running R, so it's always correct
    for the current platform (e.g. sonoma-arm64/contrib/4.6).

    Stderr is passed through to the terminal so build/install errors are visible.
    Only stdout (the final 3 lines of paths) is captured.
    """
    import shutil

    rscript = shutil.which("Rscript")
    if rscript is None:
        msg = "Rscript is not installed."
        raise RuntimeError(msg)

    code = (
        _BUILD_R.replace("PKG_DIR", _r_quoted(package_dir))
        .replace("BUILD_DIR", _r_quoted(build_dir))
        .replace("INDEX_URL", _r_quoted(_INDEX_URL))
    )
    # Capture stdout only; let stderr flow to the terminal so errors are visible.
    result = subprocess.run(
        [rscript, "-e", code],
        capture_output=False,
        stdout=subprocess.PIPE,
        text=True,
        check=True,
    )
    lines = [ln for ln in result.stdout.splitlines() if ln.strip()]
    if len(lines) < 3:
        msg = f"Expected 3 lines from R build script, got: {result.stdout!r}"
        raise RuntimeError(msg)
    return lines[-3], lines[-2], lines[-1]


def _generate_landing(entries: list[dict[str, str]]) -> str:
    """Render the root landing page HTML from src/contrib DESCRIPTION entries.

    Reuses the Package/Description fields already parsed by _reindex_prefix()
    for src/contrib — no extra S3 calls or tarball streams. Packages are
    grouped by _CATEGORIES; any package present in S3 but absent from every
    category warns to stderr and is appended to "Infrastructure" so it is
    never silently dropped from the page.
    """
    by_lower = {entry["Package"].lower(): entry for entry in entries if entry.get("Package")}
    categorized = {name for _, names in _CATEGORIES for name in names}

    uncategorized = sorted(by_lower.keys() - categorized)
    for name in uncategorized:
        print(
            f"Warning: '{name}' is not in _CATEGORIES; adding to 'Infrastructure'.",
            file=sys.stderr,
        )

    sections: list[tuple[str, list[tuple[str, str, str]]]] = []
    for heading, names in _CATEGORIES:
        section_names = names + uncategorized if heading == "Infrastructure" else names
        section_entries = []
        for name in section_names:
            entry = by_lower.get(name)
            if entry is None:
                continue
            display_name = entry["Package"]
            description = " ".join(entry.get("Description", "").split())
            section_entries.append((display_name, _DOCS_PATH.format(name=name), description))
        if section_entries:
            sections.append((heading, section_entries))

    from koopa.landing import render_landing

    return render_landing(
        "R packages",
        sections,
        license_name="Apache 2.0",
        license_url="https://www.apache.org/licenses/LICENSE-2.0",
        copyright_years="2019-pres.",
    )


def _upload_landing(html_content: str, tmp_dir: str) -> None:
    """Write the landing page to a temp file and upload it to s3://bucket/index.html."""
    local = os.path.join(tmp_dir, "index.html")
    with open(local, "w") as fh:
        fh.write(html_content)
    subprocess.run(
        [
            _aws(),
            "s3",
            f"--profile={_PROFILE}",
            "cp",
            "--content-type",
            "text/html",
            local,
            f"{_s3_uri()}/index.html",
        ],
        check=True,
    )


def _invalidate_cloudfront(paths: list[str] | None = None) -> None:
    """Invalidate the given CloudFront paths (defaults to PACKAGES* manifests)."""
    aws = _aws()
    dist_id = _cloudfront_distribution_id()
    subprocess.run(
        [
            aws,
            "cloudfront",
            "create-invalidation",
            "--distribution-id",
            dist_id,
            "--no-cli-pager",
            "--output",
            "text",
            "--paths",
            *(paths if paths is not None else _CLOUDFRONT_PATHS),
            f"--profile={_PROFILE}",
        ],
        check=True,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def publish(
    package_dir: str,
    *,
    check: bool = True,
    deploy: bool = True,
    invalidate: bool = True,
    tag: bool = True,
) -> None:
    """Build and publish an R package to r.acidgenomics.com.

    Uploads tarballs directly to S3 and regenerates PACKAGES manifests
    by streaming DESCRIPTION files — no local git repo or drat required.

    Parameters
    ----------
    package_dir
        Path to an R package source directory (must contain DESCRIPTION).
    check
        Run R CMD check --as-cran --no-manual before building.
    deploy
        Upload to S3 and regenerate PACKAGES manifests after building.
    invalidate
        Invalidate CloudFront PACKAGES* caches (only when deploy=True).
    tag
        Create an annotated git tag vX.Y.Z and push it to origin after a
        successful deploy. Only runs when the package dir is a git repo.
        Tag message: "<Package> v<Version> (<Date>)".
    """
    from koopa.alert import alert

    pkg_path = Path(package_dir).expanduser().resolve()
    if not (pkg_path / "DESCRIPTION").is_file():
        msg = f"No DESCRIPTION found in '{pkg_path}'."
        raise FileNotFoundError(msg)

    if check:
        from koopa.r import r_check

        alert(f"Checking '{pkg_path.name}'.")
        r_check(str(pkg_path))

    alert(f"Building '{pkg_path.name}'.")
    with tempfile.TemporaryDirectory(prefix="koopa-r-build-") as build_dir:
        src_path, bin_path, bin_subpath = _r_build(str(pkg_path), build_dir)

        src_base = os.path.basename(src_path)
        bin_base = os.path.basename(bin_path)

        if deploy:
            # Package name from tarball basename: "goalie_0.7.9.tar.gz" → "goalie"
            pkg_name = src_base.rsplit("_", 1)[0]
            src_key = f"src/contrib/{src_base}"
            bin_key = f"{bin_subpath}/{bin_base}"

            alert(f"Archiving previous version of '{pkg_name}' in src/contrib.")
            _archive_old_source(pkg_name, src_base)

            alert(f"Uploading '{src_base}' to s3://{_bucket()}/{src_key}.")
            _upload_package(src_path, src_key)

            alert(f"Uploading '{bin_base}' to s3://{_bucket()}/{bin_key}.")
            _upload_package(bin_path, bin_key)

            alert("Regenerating src/contrib PACKAGES manifests.")
            src_entries = _reindex_prefix("src/contrib", binary=False)

            alert(f"Regenerating {bin_subpath} PACKAGES manifests.")
            _reindex_prefix(bin_subpath, binary=True)

            alert("Generating landing page.")
            landing_html = _generate_landing(src_entries)
            _upload_landing(landing_html, build_dir)

            if invalidate:
                alert("Invalidating CloudFront PACKAGES* and landing page caches.")
                _invalidate_cloudfront([*_CLOUDFRONT_PATHS, "/", "/index.html"])

            alert(f"Published '{src_base}' to {_INDEX_URL}")

            if tag:
                from koopa.git import git_create_tag, git_push_tag, git_tag_exists, is_git_repo
                from koopa.system import today

                if is_git_repo(str(pkg_path)):
                    desc = _parse_dcf((pkg_path / "DESCRIPTION").read_text())
                    version = desc["Version"]
                    date = desc.get("Date") or today()
                    tag_name = f"v{version}"
                    message = f"{desc['Package']} v{version} ({date})"
                    if git_tag_exists(tag_name, str(pkg_path)):
                        alert(f"Tag '{tag_name}' already exists locally; skipping creation.")
                    else:
                        alert(f"Tagging '{tag_name}'.")
                        git_create_tag(tag_name, message, str(pkg_path))
                    git_push_tag(tag_name, str(pkg_path))
        else:
            alert(f"Built '{src_base}' and '{bin_base}' (deploy skipped).")


def publish_docs(package_dir: str, *, invalidate: bool = True) -> None:
    """Build and publish a package's pkgdown site to r.acidgenomics.com.

    The rendered site is synced to s3://<r-bucket>/<name>/ where <name> is the
    lowercased ``Package`` field read from DESCRIPTION. Docs are served at
    https://r.acidgenomics.com/<name>/ on the same domain and bucket as the
    package repo. src/contrib/ and bin/ are not touched.

    Parameters
    ----------
    package_dir
        Path to an R package source directory (must contain DESCRIPTION and
        a ``_pkgdown.yml`` config).
    invalidate
        Whether to invalidate the CloudFront cache after uploading.
    """
    import shutil

    from koopa.alert import alert
    from koopa.aws import aws_s3_sync

    pkg_path = Path(package_dir).expanduser().resolve()
    desc_file = pkg_path / "DESCRIPTION"
    if not desc_file.is_file():
        msg = f"No DESCRIPTION found in '{pkg_path}'."
        raise FileNotFoundError(msg)
    if not (pkg_path / "_pkgdown.yml").is_file():
        msg = f"No _pkgdown.yml found in '{pkg_path}'."
        raise FileNotFoundError(msg)

    desc = _parse_dcf(desc_file.read_text())
    raw_name = desc.get("Package", "")
    if not raw_name:
        msg = f"Package field not found in '{desc_file}'."
        raise RuntimeError(msg)
    name = raw_name.lower()
    if name in _RESERVED_PREFIXES:
        msg = f"Package name '{name}' collides with a reserved path on r.acidgenomics.com."
        raise ValueError(msg)

    rscript = shutil.which("Rscript")
    if rscript is None:
        msg = "Rscript is not installed."
        raise RuntimeError(msg)

    docs_dir = pkg_path / "docs"
    alert(f"Building pkgdown site for '{name}' in '{pkg_path}'.")
    code = _BUILD_DOCS_R.replace("PKG_DIR", _r_quoted(str(pkg_path)))
    subprocess.run([rscript, "-e", code], check=True)
    if not docs_dir.is_dir():
        msg = f"pkgdown did not produce a docs/ directory in '{pkg_path}'."
        raise RuntimeError(msg)

    try:
        dest = f"{_s3_uri()}/{name}/"
        alert(f"Syncing docs to '{dest}'.")
        aws_s3_sync(str(docs_dir) + "/", dest, delete=True, profile=_PROFILE)

        if invalidate:
            alert(f"Invalidating CloudFront cache for '/{name}/*'.")
            _invalidate_cloudfront([f"/{name}/*"])
    finally:
        shutil.rmtree(docs_dir, ignore_errors=True)

    alert(f"Docs published: https://r.acidgenomics.com/{name}/")


def archive_src(*, invalidate: bool = True) -> None:
    """Move superseded source tarballs in src/contrib/ to Archive/<Pkg>/.

    Groups tarballs by package name, keeps only the latest version of each
    in the flat src/contrib/ directory, and S3-mv's superseded versions to
    src/contrib/Archive/<Pkg>/<filename>. Regenerates PACKAGES manifests
    and optionally invalidates CloudFront.

    Parameters
    ----------
    invalidate
        Invalidate CloudFront PACKAGES* caches after archiving.
    """
    from koopa.alert import alert

    alert("Listing src/contrib packages.")
    objects = _s3_list_packages("src/contrib")
    if not objects:
        alert("No packages found in src/contrib.")
        return

    # Group by package name, collect (version_tuple, filename, key) per package.
    from collections import defaultdict

    groups: dict[str, list[tuple[tuple[int, ...], str, str]]] = defaultdict(list)
    for obj in objects:
        filename = obj["Filename"]
        # Parse "PkgName_X.Y.Z.tar.gz" → name="PkgName", ver=(X,Y,Z)
        stem = filename[: -len(".tar.gz")]
        parts = stem.rsplit("_", 1)
        if len(parts) != 2:
            continue
        pkg_name, ver_str = parts
        try:
            ver_tuple = tuple(int(x) for x in ver_str.split("."))
        except ValueError:
            continue
        groups[pkg_name].append((ver_tuple, filename, obj["Key"]))

    aws = _aws()
    archived = 0
    for pkg_name, versions in groups.items():
        if len(versions) <= 1:
            continue
        # Sort descending; keep the first (latest), archive the rest.
        versions.sort(key=lambda t: t[0], reverse=True)
        for _, filename, key in versions[1:]:
            archive_key = f"src/contrib/Archive/{pkg_name}/{filename}"
            alert(f"Archiving '{filename}' → Archive/{pkg_name}/.")
            subprocess.run(
                [
                    aws,
                    "s3",
                    f"--profile={_PROFILE}",
                    "mv",
                    f"{_s3_uri()}/{key}",
                    f"{_s3_uri()}/{archive_key}",
                ],
                check=True,
            )
            archived += 1

    if archived:
        alert(f"Archived {archived} superseded tarball(s). Regenerating manifests.")
        _reindex_prefix("src/contrib", binary=False)
        if invalidate:
            _invalidate_cloudfront()
    else:
        alert("src/contrib is already clean — no superseded versions found.")


def clean_orphan_binaries(*, invalidate: bool = True) -> None:
    """Delete binary tarballs that have no matching source package in src/contrib.

    A binary is an orphan when its package name does not appear in src/contrib
    at *any* version (i.e. the source package was fully retired).  Version
    mismatches (binary older/newer than source) are not orphans — those are
    handled by republishing.

    Iterates every active binary prefix discovered in S3.

    Parameters
    ----------
    invalidate
        Invalidate CloudFront PACKAGES* caches if any orphans are deleted.
    """
    from koopa.alert import alert

    # Build the set of package names present in src/contrib.
    alert("Listing src/contrib packages.")
    src_objects = _s3_list_packages("src/contrib")
    src_names: set[str] = set()
    for obj in src_objects:
        stem = obj["Filename"][: -len(".tar.gz")]
        parts = stem.rsplit("_", 1)
        if len(parts) == 2:
            src_names.add(parts[0])

    active_prefixes = [
        p.rstrip("/") for p in _s3_list_binary_prefixes() if _ACTIVE_BINARY_PREFIX in p
    ]

    aws = _aws()
    deleted = 0
    for prefix in active_prefixes:
        alert(f"Checking binary prefix '{prefix}' for orphans.")
        bin_objects = _s3_list_packages(prefix)
        for obj in bin_objects:
            filename = obj["Filename"]
            stem = filename[: -len(".tgz")]
            parts = stem.rsplit("_", 1)
            if len(parts) != 2:
                continue
            pkg_name = parts[0]
            if pkg_name not in src_names:
                alert(f"Deleting orphan binary '{filename}' (no source package).")
                subprocess.run(
                    [
                        aws,
                        "s3",
                        f"--profile={_PROFILE}",
                        "rm",
                        f"{_s3_uri()}/{obj['Key']}",
                    ],
                    check=True,
                )
                deleted += 1

    if deleted:
        alert(f"Deleted {deleted} orphan binary/binaries. Regenerating manifests.")
        for prefix in active_prefixes:
            _reindex_prefix(prefix, binary=True)
        if invalidate:
            _invalidate_cloudfront()
    else:
        alert("No orphan binaries found.")


def publish_from_github(
    pkg_name: str,
    *,
    org: str = "acidgenomics",
    check: bool = False,
    invalidate: bool = True,
) -> None:
    """Clone an R package from GitHub and publish it to r.acidgenomics.com.

    Clones https://github.com/<org>/<pkg_name> into a temporary directory,
    builds source + binary tarballs, uploads them to S3, and regenerates
    PACKAGES manifests. The clone is cleaned up automatically.

    Parameters
    ----------
    pkg_name
        GitHub repository name (e.g. "r-goalie").
    org
        GitHub organisation. Defaults to "acidgenomics".
    check
        Run R CMD check before building. Off by default for batch builds.
    invalidate
        Invalidate CloudFront PACKAGES* caches after publishing.
    """
    import shutil

    from koopa.alert import alert

    git = shutil.which("git")
    if git is None:
        msg = "git is not installed."
        raise RuntimeError(msg)

    url = f"https://github.com/{org}/{pkg_name}"
    alert(f"Cloning '{url}'.")
    with tempfile.TemporaryDirectory(prefix="koopa-r-clone-") as clone_dir:
        subprocess.run(
            [git, "clone", "--depth=1", url, clone_dir],
            check=True,
        )
        publish(clone_dir, check=check, invalidate=invalidate, tag=False)


def reindex(*, invalidate: bool = True) -> None:
    """Regenerate all PACKAGES manifests from current S3 bucket contents.

    Reindexes src/contrib (source packages) and the active binary prefix
    (sonoma-arm64/contrib/<Rver> paths found in S3). Also writes empty PACKAGES
    manifests to skeleton prefixes so R clients on those platforms fall back to
    source silently instead of warning about a missing index.

    Parameters
    ----------
    invalidate
        Invalidate CloudFront PACKAGES* caches after reindexing.
    """
    from koopa.alert import alert

    alert("Reindexing src/contrib.")
    src_entries = _reindex_prefix("src/contrib", binary=False)

    # Active binary prefixes — only sonoma-arm64; discover all R versions present.
    active_prefixes = [
        p.rstrip("/") for p in _s3_list_binary_prefixes() if _ACTIVE_BINARY_PREFIX in p
    ]
    alert(f"Active binary prefixes: {active_prefixes}")
    for prefix in active_prefixes:
        _reindex_prefix(prefix, binary=True)

    # Skeleton prefixes — write empty manifests to suppress R client warnings.
    for prefix in _SKELETON_BINARY_PREFIXES:
        alert(f"Writing empty skeleton PACKAGES for '{prefix}'.")
        with tempfile.TemporaryDirectory() as tmp_dir:
            _upload_manifest("", prefix, tmp_dir)

    alert("Generating landing page.")
    landing_html = _generate_landing(src_entries)
    with tempfile.TemporaryDirectory() as tmp_dir:
        _upload_landing(landing_html, tmp_dir)

    if invalidate:
        alert("Invalidating CloudFront PACKAGES* and landing page caches.")
        _invalidate_cloudfront([*_CLOUDFRONT_PATHS, "/", "/index.html"])

    alert("Reindex complete.")


def deploy(*, invalidate: bool = True) -> None:
    """Alias for reindex() — kept for CLI symmetry and AcidDevTools compatibility.

    Parameters
    ----------
    invalidate
        Invalidate CloudFront PACKAGES* caches after reindexing.
    """
    reindex(invalidate=invalidate)
