"""Generate koopa.1 man page in roff format.

Auto-generates ``share/man/man1/koopa.1`` by reusing the authoritative
command/platform tables from ``generate_completion.py`` and the handler
registry in ``cli_develop.py``. Only descriptions and argument synopses
live here — command names and platform tags are never duplicated.

Usage::

    koopa develop generate-man          # print to stdout
    koopa develop generate-man --write  # overwrite koopa.1
"""

import os
from datetime import date

from koopa.cli_docs import (
    ADMIN_DESCRIPTIONS as _ADMIN_DESCRIPTIONS,
)
from koopa.cli_docs import (
    DEVELOP_DESCRIPTIONS as _DEVELOP_DESCRIPTIONS,
)
from koopa.cli_docs import (
    DEVELOP_SYNOPSIS as _DEVELOP_SYNOPSIS,
)
from koopa.cli_docs import (
    INSTALL_FLAGS as _INSTALL_FLAGS,
)
from koopa.cli_docs import (
    REINSTALL_FLAGS as _REINSTALL_FLAGS,
)
from koopa.cli_docs import (
    SYSTEM_DESCRIPTIONS as _SYSTEM_DESCRIPTIONS,
)
from koopa.cli_docs import (
    SYSTEM_SYNOPSIS as _SYSTEM_SYNOPSIS,
)
from koopa.cli_docs import (
    TOP_COMMANDS as _TOP_COMMANDS,
)

# ---------------------------------------------------------------------------
# roff helpers
# ---------------------------------------------------------------------------


def _roff_name(text: str) -> str:
    """Escape hyphens for roff .TP term lines.

    Parameters
    ----------
    text : str
        Command or flag name to escape.

    Returns
    -------
    str
        Text with hyphens escaped for roff.
    """
    return text.replace("-", r"\-")


def _bold(text: str) -> str:
    return rf"\fB{text}\fR"


def _italic(text: str) -> str:
    return rf"\fI{text}\fR"


def _section(name: str) -> list[str]:
    return [".", f'.SH "{name}"']


def _subsection(name: str) -> list[str]:
    return [f'.SS "{name}"']


def _tp(term: str, desc: str) -> list[str]:
    return [".TP", term, desc]


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------


def generate_man() -> str:
    """Generate the ``koopa.1`` man page in roff format.

    Returns
    -------
    str
        The full ``koopa.1`` man page content in roff format.
    """
    from koopa.generate_completion import (
        _ADMIN_COMMANDS,
        _SYSTEM_COMMANDS,
        _load_develop_commands,
    )

    month_year = date.today().strftime("%B %Y")
    lines: list[str] = []

    lines += [
        ".\\\" Auto-generated by 'koopa develop generate-man'. Do not edit manually.",
        ".",
        f'.TH "KOOPA" "1" "{month_year}" "" ""',
        ".",
    ]

    lines += _section("NAME")
    lines.append(rf"{_bold('koopa')} \- shell bootloader for data science")

    lines += _section("SYNOPSIS")
    lines.append(rf"{_bold('koopa')} {_italic('command')} [options] [args...]")

    lines += _section("DESCRIPTION")
    lines.append(
        "koopa is a shell bootloader for data science that manages installation,"
        " configuration, and updates of command-line applications and libraries."
    )

    lines += _section("GLOBAL OPTIONS")
    lines += _tp(
        rf"{_bold('--help')}, {_bold('-h')}",
        "Show help. Place after a command to view command-specific help.",
    )
    lines += _tp(_bold("--version"), "Print version information.")
    lines += _tp(_bold("--verbose"), "Enable verbose output.")

    lines += _section("COMMANDS")
    lines += _subsection("Package management")
    for name, synopsis, desc in _TOP_COMMANDS[:5]:
        term = _bold(_roff_name(name))
        if synopsis:
            term += f" {_italic(synopsis)}"
        lines += _tp(term, desc)

    lines += _subsection("Utility commands")
    for name, synopsis, desc in _TOP_COMMANDS[5:]:
        term = _bold(_roff_name(name))
        if synopsis:
            term += f" {_italic(synopsis)}"
        lines += _tp(term, desc)

    lines += _section("INSTALL OPTIONS")
    for flag, desc in _INSTALL_FLAGS:
        lines += _tp(_bold(_roff_name(flag)), desc)

    lines += _section("REINSTALL OPTIONS")
    for flag, desc in _REINSTALL_FLAGS:
        lines += _tp(_bold(_roff_name(flag)), desc)

    # SYSTEM SUBCOMMANDS — names/platforms from the canonical generate_completion table.
    lines += _section("SYSTEM SUBCOMMANDS")
    common = [(n, p) for n, p in _SYSTEM_COMMANDS if p is None]
    macos_sys = [(n, p) for n, p in _SYSTEM_COMMANDS if p == "macos"]

    for name, _ in common:
        term = _bold(f"system {_roff_name(name)}")
        synopsis = _SYSTEM_SYNOPSIS.get(name, "")
        if synopsis:
            term += f" {_italic(synopsis)}"
        lines += _tp(term, _SYSTEM_DESCRIPTIONS.get(name, ""))

    if macos_sys:
        lines += _subsection(r"macOS\-specific system subcommands")
        for name, _ in macos_sys:
            term = _bold(f"system {_roff_name(name)}")
            synopsis = _SYSTEM_SYNOPSIS.get(name, "")
            if synopsis:
                term += f" {_italic(synopsis)}"
            lines += _tp(term, _SYSTEM_DESCRIPTIONS.get(name, ""))

    # ADMIN SUBCOMMANDS — require sudo/admin privileges.
    lines += _section("ADMIN SUBCOMMANDS")
    common_admin = [(n, p) for n, p in _ADMIN_COMMANDS if p is None]
    linux_admin = [(n, p) for n, p in _ADMIN_COMMANDS if p == "linux"]
    macos_admin = [(n, p) for n, p in _ADMIN_COMMANDS if p == "macos"]

    for name, _ in common_admin:
        lines += _tp(_bold(f"admin {_roff_name(name)}"), _ADMIN_DESCRIPTIONS.get(name, ""))

    if linux_admin:
        lines += _subsection(r"Linux\-specific admin subcommands")
        for name, _ in linux_admin:
            lines += _tp(_bold(f"admin {_roff_name(name)}"), _ADMIN_DESCRIPTIONS.get(name, ""))

    if macos_admin:
        lines += _subsection(r"macOS\-specific admin subcommands")
        for name, _ in macos_admin:
            lines += _tp(_bold(f"admin {_roff_name(name)}"), _ADMIN_DESCRIPTIONS.get(name, ""))

    # DEVELOP SUBCOMMANDS — names from _DEVELOP_HANDLERS via _load_develop_commands().
    lines += _section("DEVELOP SUBCOMMANDS")
    for name in _load_develop_commands():
        term = _bold(f"develop {_roff_name(name)}")
        synopsis = _DEVELOP_SYNOPSIS.get(name, "")
        if synopsis:
            term += f" {_italic(synopsis)}"
        lines += _tp(term, _DEVELOP_DESCRIPTIONS.get(name, ""))

    # RUN SUBCOMMANDS — utility commands accessed via 'koopa run'.
    lines += _section("RUN SUBCOMMANDS")
    from koopa.cli_bin import _HANDLERS as _RUN_HANDLERS

    for name in sorted(_RUN_HANDLERS.keys()):
        lines += _tp(_bold(f"run {_roff_name(name)}"), "")

    lines += _section("COPYRIGHT")
    lines.append("This software is licensed under the Apache License, Version 2.0.")
    lines.append(r"See \fBLICENSE\fR file for details.")

    return "\n".join(lines) + "\n"


def write_man(*, path: str = "") -> None:
    """Write ``koopa.1`` to disk.

    Parameters
    ----------
    path : str, optional
        Output file path. Defaults to ``share/man/man1/koopa.1`` under the
        koopa prefix.
    """
    from koopa.prefix import koopa_prefix

    if not path:
        path = os.path.join(koopa_prefix(), "share", "man", "man1", "koopa.1")
    content = generate_man()
    with open(path, "w") as fh:
        fh.write(content)
