.TH DOWNLOAD-CRAN-LATEST 1 2019-11-10 Bash
.SH NAME
download-cran-latest \-
Download latest CRAN release tarball
.SH SYNOPSIS
.B download-cran-latest
.I package_name
.SH DESCRIPTION
Downloads latest release into current working directory. Can pass this file to 'R CMD INSTALL'.
.SH EXAMPLE
.nf
.B download-cran-latest tibble
.fi
