.TH IP-ADDRESS 1 2019-12-12 Bash
.SH NAME
ip-address \-
IP address
.SH SYNOPSIS
.B ip-address
.SH DESCRIPTION
For macOS, multiple values may return, representing wired and wireless IPs.
.SH SEE ALSO
Alternate approach for macOS:
.B ipconfig getifaddr en0
.PP
https://apple.stackexchange.com/questions/20547

