.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CAMEL\-CASE" "1" "October 2023" "" ""
.
.SH "NAME"
\fBcamel\-case\fR \- convert input into camel case
.
.SH "SYNOPSIS"
\fBcamel\-case\fR [\fB\-\-rename\fR] [\fB\-\-strict\fR] [\fB\-\-prefix\fR] STRING|FILE\.\.\.
.
.SH "DESCRIPTION"
Runs in string mode by default\. File rename mode can be enabled by setting \fB\-\-rename\fR flag\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-rename\fR
Rename input files\. Assumes we\'re renaming files in current working directory, but also supports explicit and/or mixed file paths\. Doesn\'t work recursively\.
.
.TP
\fB\-\-strict\fR
Enforce strict camel case output, coercing acronyms\. For example, \'geneID\' becomes \'geneId\'\.
.
.TP
\fB\-\-prefix\fR
Include \'x\' prefix for names that are syntactically invalid in R\. Note that this includes input beginning with a number\. Disabled by default\.
.
.SH "NOTE"
Bash script that calls \fBRscript\fR internally\. Requires the syntactic package to be installed\.
.
.SH "SEE ALSO"
syntactic R package \fIhttps://syntactic\.acidgenomics\.com/\fR
.
.SH "EXAMPLES"
.
.nf

$ camel\-case \'hello world\' \'foo bar\'
## helloWorld fooBar

$ camel\-case \-\-strict \'gene ID\'
## geneId

$ camel\-case \-\-rename \'foo\-bar\.fastq\.gz\'
## \./fooBar\.fastq\.gz

$ camel\-case \-\-rename \-\-prefix \'1\-control\-A\.fastq\.gz\'
## \./x1ControlA\.fastq\.gz
.
.fi

