#!/usr/bin/env bash

KOOPA_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." \
    >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${KOOPA_HOME}/shell/bash/include/header.sh"

_koopa_assert_has_sudo



# Script                                                                    {{{1
# ==============================================================================

sudo find "$TMPDIR" -mindepth 1 -maxdepth 1 -ctime +7 -exec rm -frv {} \;
