#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(koopa header bash)"

# Install TeX packages using tlmgr.
# Updated 2019-06-25.

printf "Installing TeX packages recommended for RStudio.\n"

_koopa_assert_has_sudo

sudo tlmgr update --self

packages=( \
    collection-fontsrecommended  # priority
    collection-latexrecommended  # priority
    bera  # beramono
    caption
    changepage
    csvsimple
    enumitem
    etoolbox
    fancyhdr
    footmisc
    framed
    geometry
    hyperref
    inconsolata
    marginfix
    mathtools
    natbib
    nowidow
    parnotes
    parskip
    placeins
    preprint  # authblk
    sectsty
    soul
    titlesec
    titling
    xstring \
)

for package in "${packages[@]}"
do
    sudo tlmgr install "$package"
done
