#!/usr/bin/env bash

KOOPA_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." \
    >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${KOOPA_HOME}/shell/bash/include/header.sh"

_koopa_assert_has_sudo



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install pip package manager for Python.

$(_koopa_help_args)

details:
    Installs into '/usr/local/' by default.

see also:
    https://pip.pypa.io/en/stable/installing/

note:
    Bash script.
    Updated 2019-10-08.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

_koopa_assert_is_not_installed pip

curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
sudo "/usr/local/bin/python3" "get-pip.py"
rm "get-pip.py"
