#!/usr/bin/env bash

KOOPA_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." \
    >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${KOOPA_HOME}/shell/bash/include/header.sh"

_koopa_help "$@"
_koopa_assert_has_sudo
_koopa_assert_is_not_installed pip

_koopa_note "Usage of pip inside a virtual environment is recommended."

curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
sudo "/usr/local/bin/python3" "get-pip.py"
rm "get-pip.py"
