#!/usr/bin/env bash

KOOPA_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." \
    >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${KOOPA_HOME}/shell/bash/include/header.sh"

_koopa_assert_has_sudo



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
usage: install-tex-packages [--help|-h]

Install TeX packages using tlmgr.

optional arguments:
    --help, -h
        Show this help message and exit.

note:
    Bash script.
    Updated 2019-09-24.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

printf "Installing TeX packages recommended for RStudio.\n"

sudo tlmgr update --self

packages=( \
    collection-fontsrecommended  # priority
    collection-latexrecommended  # priority
    bera  # beramono
    caption
    changepage
    csvsimple
    enumitem
    etoolbox
    fancyhdr
    footmisc
    framed
    geometry
    hyperref
    inconsolata
    marginfix
    mathtools
    natbib
    nowidow
    parnotes
    parskip
    placeins
    preprint  # authblk
    sectsty
    soul
    titlesec
    titling
    xstring
)

for package in "${packages[@]}"
do
    sudo tlmgr install "$package"
done
