#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header bash)"

# Link cellar into local build directory
# Modified 2019-06-23.

_koopa_assert_has_sudo
_koopa_build_link_cellar "$@"
