#!/usr/bin/env bash

KOOPA_PREFIX="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${KOOPA_PREFIX}/shell/bash/include/header.sh"

_koopa_assert_has_args "$@"

flags=(
    # "--exclude=bam"
    # "--exclude=cram"
    # "--exclude=fastq"
    # "--exclude=sam"
    "--exclude=.Rproj.user"
    "--exclude=.git"
    "--exclude=.gitignore"
    "--exclude=work"
    "--human-readable"
    "--no-links"
    "--progress"
    "--recursive"
    "--size-only"
    "--stats"
    "--verbose"
)

rsync "${flags[@]}" --rsync-path="sudo rsync" "$@"
