#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../shell/bash/include/header.sh"

koopa::rsync_cloud() {
    local flags
    koopa::assert_has_args "$#"
    koopa::assert_is_installed rsync
    flags=(
        # '--exclude=bam'
        # '--exclude=cram'
        # '--exclude=fastq'
        # '--exclude=sam'
        '--exclude=.Rproj.user'
        '--exclude=.git'
        '--exclude=.gitignore'
        '--exclude=work'
        '--human-readable'
        '--no-links'
        '--progress'
        '--recursive'
        '--size-only'
        '--stats'
        '--verbose'
    )
    rsync "${flags[@]}" --rsync-path='sudo rsync' "$@"
    return 0
}

koopa::rsync_cloud "$@"
