#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../shell/bash/include/header.sh"
koopa::assert_has_no_args "$@"

if ! koopa::is_installed tlmgr
then
    koopa::warning "tlmgr is not installed."
    exit 0
fi

koopa::h1 "Updating TeX Live."

sudo tlmgr update --self
sudo tlmgr update --list
sudo tlmgr update --all
