#!/usr/bin/env bash

KOOPA_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." \
    >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${KOOPA_HOME}/shell/bash/include/header.sh"

_koopa_assert_has_sudo



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Update TeX installation.

$(_koopa_help_args)

see also:
    https://tex.stackexchange.com/questions/55437

note:
    Bash script.
    Requires that texlive is already installed.
    Updated 2019-10-20.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

if ! _koopa_is_installed tlmgr
then
    >&2 printf "Error: tlmgr is not installed.\n"
    exit 0
fi

echo "Updating Tex Live."

sudo tlmgr update --self
sudo tlmgr update --list
sudo tlmgr update --all
