.TH CONVERT-UTF8-NFD-TO-NFC 1 2019-11-09 Bash
.SH NAME
convert-utf8-nfd-to-nfc \-
Convert UTF-8 NFD to NFC
.SH SYNOPSIS
.B convert-utf8-nfd-to-nfc
file|dir ...
.SH DESCRIPTION
Unicode on macOS is insane. macOS for some reason uses NFD, whereas every other popular platform uses NFC. This script is particularly useful for handling files created on macOS that have been copied to a Linux file system (e.g. onto NAS). Uses standard file globbing to match.
.SH NOTE
Requires convmv to be installed.
