#!/usr/bin/env bash

KOOPA_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." \
    >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${KOOPA_HOME}/shell/bash/include/header.sh"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

List cellar program versions.

$(_koopa_help_args)

note:
    Bash script.
    Updated 2019-10-26.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

prefix="$(_koopa_cellar_prefix)"
(
    cd "$prefix" || exit 1
    ls -1 -- *
)
