#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# openSUSE uses zypper package manager by default.
# zypper cheat sheet:
# https://en.opensuse.org/images/1/17/Zypper-cheat-sheet-1.pdf
# """

sudo zypper refresh
sudo zypper --non-interactive update

packages=(
    # fish
    # gnu_parallel
    # texlive
    # zsh
    R-base
    R-base-devel
    autoconf
    bzip2
    curl
    gcc
    gcc-c++
    gcc-fortran
    gettext
    git
    gzip
    libbz2-devel
    libcurl-devel
    libevent-devel
    libffi-devel
    lzma-devel
    make
    ncurses-devel
    openssl-devel
    pcre-devel
    readline-devel
    sudo
    tar
    tree
    wget
    which
    xz
    zlib-devel
)
sudo zypper --non-interactive install "${packages[@]}"
