# /etc/zsh/zshenv: system-wide .zshenv file for zsh(1).
#
# This file is sourced on all invocations of the shell.
# If the -f flag is present or if the NO_RCS option is
# set within this file, all other initialization files
# are skipped.
#
# This file should contain commands to set the command
# search path, plus other important environment variables.
# This file should not contain commands that produce
# output or assume the shell is attached to a tty.
#
# Global Order: zshenv, zprofile, zshrc, zlogin
#
# Updated 2020-01-15.

_src_etc_profile()
{
    # Make '/etc/profile' happier, and have possible '~/.zshenv' options like
    # 'NOMATCH' ignored.
    emulate -L ksh

    # Source profile scripts.
    if [ -f /etc/profile ]
    then
        source /etc/profile
    fi
}
_src_etc_profile

unset -f _src_etc_profile
