#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header darwin)"

# Disable quarantine on installed applications.
# Modified 2019-06-23.

# This is useful for installed Homebrew casks.

sudo xattr -r -d com.apple.quarantine /Applications/*.app
