#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_koopa_assert_has_no_args "$@"

_koopa_h1 "Configuring macOS system."

_koopa_enable_passwordless_sudo

install-homebrew
install-homebrew-packages
install-python
install-python-packages
install-r-cran-gfortran
install-r-packages
install-conda
install-rbenv-ruby
update-defaults

_koopa_success "Configuration was successful."
