#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

sudo rm -rv "${HOME}/Desktop"
ln -fnsv "${HOME}/Dropbox/Desktop" "${HOME}/."

sudo rm -rv "${HOME}/Documents"
ln -fnsv "${HOME}/Dropbox/Documents" "${HOME}/."

sudo killAll Finder
