#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Symlink Desktop and Documents on Dropbox.

$(_koopa_help_args)

note:
    Bash script.
    Updated 2019-09-26.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

# Desktop.
sudo rm -rv ~/Desktop
ln -fnsv ~/Dropbox/Desktop ~/.

# Documents.
sudo rm -rv ~/Documents
ln -fnsv ~/Dropbox/Documents ~/.

# Relaunch Finder.
sudo killAll Finder
