#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header darwin)"

# Flush DNS cache.
# Modified 2019-06-23.

sudo dscacheutil -flushcache
sudo killall -HUP mDNSResponder
say flushed
