#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Flush DNS cache.

$(_koopa_help_args)

note:
    Bash script.
    Updated 2019-09-26.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

sudo dscacheutil -flushcache
sudo killall -HUP mDNSResponder
say flushed
