#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
koopa::assert_has_no_args "$#"

# """
# https://apple.stackexchange.com/questions/93573/
# """

name_fancy="Xcode CLT"
koopa::install_start "$name_fancy"

prefix="$(xcode-select -p 2>/dev/null)"
if [[ -d "$prefix" ]]
then
    sudo rm -fr "$prefix"
fi

xcode-select --install
sudo xcodebuild -license accept
sudo xcode-select -r
xcode-select -p

koopa::install_success "$name_fancy"
