#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_no_args "$@"
_koopa_assert_has_sudo

r_version="3.6-branch"
macos_version="el-capitan"
tmp_dir="$(_koopa_tmp_dir)/r-devel"

_koopa_message "Installing r-devel ${r_version} for ${macos_version}."

(
    rm -fr "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="R-${r_version}-${macos_version}-sa-x86_64.tar.gz"
    url="https://mac.r-project.org/${macos_version}/R-${r_version}/${file}"
    _koopa_download "$url"
    # Back up, if necessary.
    if [[ -d "/Library/Frameworks/R.framework" ]]
    then
        _koopa_note "Backing up existing 'R.framework'."
        sudo mv "/Library/Frameworks/R.framework" \
            "/Library/Frameworks/R.framework.bak"
    fi
    # Now we're ready to install.
    sudo tar -xzvf "$file" -C /
    rm -fr "$tmp_dir"
)

# Create versioned symlinks.
sudo mv "/Library/Frameworks/R.framework" \
    "/Library/Frameworks/R-${r_version}.framework"
sudo ln -fnsv "/Library/Frameworks/R-${r_version}.framework" \
    "/Library/Frameworks/R.framework"

_koopa_message "R-${r_version} installed correctly."
_koopa_message "Ensure that 'R_LIBS_USER' in '~/.Renviron' is correct."
