#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

r_version="3.6-branch"
macos_version="el-capitan"
tmp_dir="$(_koopa_tmp_dir)/r-devel"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install R-devel for macOS.

$(_koopa_help_args)

details:
    Note that this step will overwrite an existing R installation, located at:
    '/Library/Frameworks/R.framework'.

    If necessary, rename your previous install first (e.g. 'R-3.6.1.framework').
    Use symlinks to point 'R.framework' to a specific version.

    Pulling down a bioc-devel Docker image is now recommended instead.

see also:
    https://mac.r-project.org/

note:
    Bash script.
    Updated 2019-09-26.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

printf "Installing r-devel %s for %s.\n" "$r_version" "$macos_version"

(
    rm -fr "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    tarball="R-${r_version}-${macos_version}-sa-x86_64.tar.gz"
    wget "https://mac.r-project.org/${macos_version}/R-${r_version}/${tarball}"
    # Back up, if necessary.
    if [[ -d "/Library/Frameworks/R.framework" ]]
    then
        printf "Backing up existing 'R.framework'.\n"
        sudo mv \
            "/Library/Frameworks/R.framework" \
            "/Library/Frameworks/R.framework.bak"
    fi
    # Now we're ready to install.
    sudo tar fvxz "$tarball" -C /
    rm -fr "$tmp_dir"
)

# Create versioned symlinks.
sudo mv \
    "/Library/Frameworks/R.framework" \
    "/Library/Frameworks/R-${r_version}.framework"
sudo ln -s \
    "/Library/Frameworks/R-${r_version}.framework" \
    "/Library/Frameworks/R.framework"

printf "R-%s installed correctly.\n" "$r_version"
printf "Ensure that 'R_LIBS_USER' in '~/.Renviron' is correct.\n"
