#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

name="gfortran"
version="6.1"
prefix="/usr/local/${name}"

_koopa_exit_if_dir "$prefix"

_koopa_h1 "Installing ${name} ${version} to '${prefix}'."

tmp_dir="$(_koopa_tmp_dir)"

(
    _koopa_cd_tmp_dir "$tmp_dir"
    file="${name}-${version}.pkg"
    url="https://cran.r-project.org/bin/macosx/tools/${file}"
    _koopa_download "$url"
    sudo installer -pkg "$file" -target /
) 2>&1 | tee "$(_koopa_tmp_log_file)"

rm -fr "$tmp_dir"

_koopa_install_success "$name"
_koopa_note "Restart the shell to complete installation."
