#!/usr/bin/env bash
set -Eeu -o pipefail

# Install OpenSSL.
# Modified 2019-06-18.

# See also:
# - https://www.openssl.org/source/

# shellcheck source=/dev/null
source "${KOOPA_DIR}/system/include/os/darwin/sudo.sh"

tmp_dir="${KOOPA_TMP_DIR}/openssl"
version="$(koopa variable openssl)"

printf "Installing openssl %s.\n" "$version"

(
    rm -rf "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    curl -O "https://www.openssl.org/source/openssl-${version}.tar.gz"
    tar -xvzf "openssl-${version}.tar.gz"
    cd "openssl-${version}" || exit 1
    ./Configure darwin64-x86_64-cc
    make
    make test
    sudo make install
    rm -rf "$tmp_dir"
)

cat << EOF
Reload the current shell.

> command -v openssl
> openssl version
> openssl ciphers -v
EOF
