#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

reinstall=0
pos=()
while (("$#"))
do
    case "$1" in
        --reinstall)
            reinstall=1
            shift 1
            ;;
        --)
            shift 1
            break
            ;;
        --*|-*)
            koopa::invalid_arg "$1"
            ;;
        *)
            pos+=("$1")
            shift 1
            ;;
    esac
done
[[ "${#pos[@]}" -gt 0 ]] && set -- "${pos[@]}"

name_fancy="Python"
name="python"
version="$(koopa::variable "$name")"
framework_dir="/Library/Frameworks/Python.framework"

if ! koopa::is_current_version "$name" || [[ "$reinstall" -eq 1 ]]
then
    koopa::sys_rm "$framework_dir"
fi

koopa::exit_if_dir "$framework_dir"

koopa::install_start "$name_fancy" "$framework_dir"

tmp_dir="$(koopa::tmp_dir)"

(
    koopa::cd "$tmp_dir"
    file="python-${version}-macosx10.9.pkg"
    url="https://www.python.org/ftp/python/${version}/${file}"
    koopa::download "$url"
    sudo installer -pkg "$file" -target /
) 2>&1 | tee "$(koopa::tmp_log_file)"

rm -fr "$tmp_dir"

koopa::install_success "$name_fancy"
koopa::restart
