#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh" --no-header-checks
_koopa_assert_has_no_args "$@"

_koopa_exit_if_installed brew

_koopa_h1 "Installing Homebrew."

_koopa_h2 "Installing Xcode command line tools (CLT)."
xcode-select --install || true

tmp_dir="$(_koopa_tmp_dir)/homebrew"

(
    _koopa_cd_tmp_dir "$tmp_dir"
    file="install"
    url="https://raw.githubusercontent.com/Homebrew/install/master/${file}"
    _koopa_download "$url"
    /usr/bin/ruby "$file"
) 2>&1 | tee "$(_koopa_tmp_log_file)"

_koopa_success "Installation of Homebrew was successful."
_koopa_note "Restart the shell to complete installation."
