#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

name_fancy="Python"
name="python"
version="$(_koopa_variable "$name")"
framework_dir="/Library/Frameworks/Python.framework"

_koopa_exit_if_dir "$framework_dir"

_koopa_install_start "$name_fancy" "$framework_dir"

tmp_dir="$(_koopa_tmp_dir)"

(
    _koopa_cd_tmp_dir "$tmp_dir"
    file="python-${version}-macosx10.9.pkg"
    url="https://www.python.org/ftp/python/${version}/${file}"
    _koopa_download "$url"
    sudo installer -pkg "$file" -target /
) 2>&1 | tee "$(_koopa_tmp_log_file)"

rm -fr "$tmp_dir"

_koopa_install_success "$name_fancy"
_koopa_restart
