#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Reinstall Xcode command line tools (CLI).

$(_koopa_help_args)

see also:
    https://stackoverflow.com/questions/34617452

EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

sudo rm -frv /Library/Developer/CommandLineTools
xcode-select --install
sudo xcodebuild -license accept
