#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(koopa header darwin)"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Reinstall Xcode command line tools (CLI).

$(_koopa_help_args)

see also:
    https://stackoverflow.com/questions/34617452

EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

sudo rm -frv /Library/Developer/CommandLineTools
xcode-select --install
sudo xcodebuild -license accept
