#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(koopa header darwin)"

# Open application as administrator.
# Updated 2019-06-25.

_koopa_assert_has_sudo

sudo open -a "$1"
