#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(koopa header darwin)"
_koopa_assert_has_sudo



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Open application as administrator.

required positional arguments with defaults:
    1.  Application name.

$(_koopa_help_args)

note:
    Bash script.
    Updated 2019-09-26.
EOF
}

_koopa_help "$@"



# Arguments                                                                 {{{1
# ==============================================================================

name="$1"



# Script                                                                    {{{1
# ==============================================================================

sudo -a "${name}.app"
