#!/usr/bin/env bash
set -Eeu -o pipefail

# Symlink Desktop and Documents on Dropbox.
# Modified 2019-06-18.

# shellcheck source=/dev/null
source "${KOOPA_DIR}/system/include/os/darwin/sudo.sh"

sudo rm -r ~/Desktop
ln -s ~/Dropbox/Desktop ~/.

sudo rm -r ~/Documents
ln -s ~/Dropbox/Documents ~/.

sudo killAll Finder
