#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_koopa_assert_has_no_args "$@"

# https://www.java.com/en/download/help/mac_uninstall_java.xml

name_fancy="Oracle Java"

_koopa_uninstall_start "$name_fancy"

rm -frv \
    "${HOME}/Library/Caches/com.oracle.java.Java-Updater" \
    "${HOME}/Library/Application Support/Oracle/Java" \
    "${HOME}/Library/Preferences/com.apple.java.util.prefs.plist" \
    "${HOME}/Library/Preferences/com.oracle.java.JavaAppletPlugin.plist" \
    "${HOME}/Library/Safari/LocalStorage/https_www.java.com_0.localstorage"*

sudo rm -frv \
    "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin" \
    "/Library/LaunchAgents/com.oracle.java.Java-Updater.plist" \
    "/Library/LaunchDaemons/com.oracle.java.Helper-Tool.plist" \
    "/Library/PreferencePanes/JavaControlPanel.prefPane" \
    "/Library/Preferences/com.oracle.java.Helper-Tool.plist"

_koopa_uninstall_success "$name_fancy"
