#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
checks=0 source "${script_dir}/../include/header.sh"

# FIXME
# """
# https://docs.brew.sh/FAQ
# """
koopa::exit_if_not_installed brew
name_fancy="Homebrew"
koopa::uninstall_start "$name_fancy"
koopa::assert_has_no_args "$#"
# Note that macOS Catalina now uses Zsh instead of Bash by default.
koopa::h2 "Changing default shell to system Zsh."
chsh -s /bin/zsh "$USER"
koopa::h2 "Resetting permissions in '/usr/local'."
sudo chown -Rhv "$USER" "/usr/local/"*
tmp_dir="$(koopa::tmp_dir)"
(
    koopa::cd "$tmp_dir"
    file="uninstall.sh"
    url="https://raw.githubusercontent.com/Homebrew/install/master/${file}"
    koopa::download "$url"
    chmod +x "$file"
    "./${file}"
) 2>&1 | tee "$(koopa::tmp_log_file)"
rm -fr "$tmp_dir"
koopa::uninstall_success "$name_fancy"
