#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_koopa_assert_has_no_args "$@"

name_fancy="Adobe Creative Cloud preferences"

_koopa_uninstall_start "$name_fancy"

rm -frv \
    "${HOME}/Documents/Adobe" \
    "${HOME}/Library/Application Support/Adobe"* \
    "${HOME}/Library/Caches/Adobe"* \
    "${HOME}/Library/Caches/com.adobe"* \
    "${HOME}/Library/Preferences/Adobe"* \
    "${HOME}/Library/Preferences/ByHost/com.adobe"* \
    "${HOME}/Library/Preferences/Macromedia" \
    "${HOME}/Library/Preferences/com."{a,A}"dobe"* \
    "${HOME}/Library/Saved Application State/com."{a,A}"dobe"*

sudo rm -frv \
    "/Library/Application Support/Adobe"* \
    "/Library/Application Support/regid."*".com.adobe" \
    "/Library/Caches/com."{a,A}"dobe"* \
    "/Library/Fonts/"{a,A}"dobe"* \
    "/Library/Preferences/com."{a,A}"dobe"* \
    "/Library/ScriptingAdditions/Adobe Unit Types.osax" \
    "/Users/Shared/Adobe"

_koopa_uninstall_success "$name_fancy"
