#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_koopa_assert_has_no_args "$@"

name_fancy="Microsoft OneDrive"

_koopa_uninstall_start "$name_fancy"

rm -fr \
    "${HOME}/Library/Containers/com.microsoft.OneDrive-mac.FinderSync" \
    "${HOME}/Library/Application Scripts/com.microsoft.OneDrive-mac.FinderSync" \
    "${HOME}/Library/Group Containers/UBF8T346G9.OneDriveSyncClientSuite"

sudo rm -fr "/Applications/OneDrive.app"

_koopa_uninstall_success "$name_fancy"
