#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh" --no-header-checks
_koopa_assert_has_no_args "$@"

# """
# https://docs.brew.sh/FAQ
# """

_koopa_exit_if_not_installed brew

_koopa_h1 "Uninstalling Homebrew."

url="https://raw.githubusercontent.com/Homebrew/install/master/uninstall"
/usr/bin/ruby -e "$(curl -fsSL "$url")"

_koopa_success "Uninstallation of Homebrew was successful."
