#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_koopa_assert_has_no_args "$@"

rm -frv ~/Documents/Adobe
sudo rm -frv /Library/Application\ Support/Adobe*
sudo rm -frv /Library/Application\ Support/regid.*.com.adobe
sudo rm -frv /Library/Caches/com.{a,A}dobe*
sudo rm -frv /Library/Fonts/{a,A}dobe*
sudo rm -frv /Library/Preferences/com.{a,A}dobe*
sudo rm -frv /Library/ScriptingAdditions/Adobe\ Unit\ Types.osax
sudo rm -frv /Users/Shared/Adobe
sudo rm -frv ~/Library/Application\ Support/Adobe*
sudo rm -frv ~/Library/Caches/Adobe*
sudo rm -frv ~/Library/Caches/com.adobe*
sudo rm -frv ~/Library/Preferences/Adobe*
sudo rm -frv ~/Library/Preferences/ByHost/com.adobe*
sudo rm -frv ~/Library/Preferences/Macromedia
sudo rm -frv ~/Library/Preferences/com.{a,A}dobe*
sudo rm -frv ~/Library/Saved\ Application\ State/com.{a,A}dobe*
