#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_no_args "$@"
_koopa_assert_has_sudo



# Script                                                                    {{{1
# ==============================================================================

if _koopa_is_installed mas
then
    _koopa_message "Updating App Store apps via 'mas'."
    mas upgrade
fi

print

_koopa_message "Updating macOS via 'softwareupdate'."
_koopa_note "Restart may be required."

sudo softwareupdate --install --recommended --restart
