#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Update macOS directly from the command line.

$(_koopa_help_args)

details:
    Install recommended software updates and reboot, if necessary.
    Note that this will not upgrade to a newer macOS release.

seealso:
    softwareupdate --help
    softwareupdate --list

note:
    Bash script.
    Updated 2019-10-23.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

if _koopa_is_installed mas
then
    _koopa_message "Updating App Store apps via 'mas'."
    mas upgrade
fi

print

_koopa_message "Updating macOS via 'softwareupdate'."
_koopa_note "Restart may be required."

sudo softwareupdate --install --recommended --restart
