#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_h2 "Installing Amazon Linux base system."

_koopa_assert_has_no_args "$@"

install-fedora-base

# Install utils such as chsh.
sudo yum install -y util-linux-user
