#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install base programs recommended for Amazon Linux 2.

$(_koopa_help_args)

note:
    Bash script.
    Updated 2019-06-23.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

install-fedora-base

# Install utils such as chsh.
sudo yum install -y util-linux-user
