#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_no_args "$@"

# Check if EPEL is already enabled.
if sudo yum repolist | grep -q "epel/"
then
    _koopa_success "EPEL 8 is already enabled."
    exit 0
fi

sudo yum install -y \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
sudo yum-config-manager --enable epel
sudo yum -y install epel-release
