#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_exit_if_installed yum-cron
_koopa_assert_is_installed systemctl

name="yum-cron"
service_name="${name}.service"

_koopa_install_start "$name"

# Note that this requires EPEL to be enabled.
sudo yum -y install "$name"

sudo systemctl enable "$service_name"
sudo systemctl start "$service_name"

_koopa_install_success "$name"
