#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

koopa::install_rhel_base() {
    # """
    # Install Red Hat Enterprise Linux (RHEL) base system.
    # @note Updated 2020-07-02.
    #
    # Note that RHEL 8+ now uses dnf instead of yum.
    # """
    local dev extra name_fancy pkgs
    koopa::assert_is_installed dnf sudo
    dev=1
    extra=1
    koopa::is_docker && extra=0
    # Install Fedora base first.
    "${script_dir}/../../fedora/sbin/install-base" "$@"
    name_fancy="Red Hat Enterprise Linux (RHEL) base system"
    koopa::install_start "$name_fancy"

    # Default {{{1
    # ==========================================================================

    koopa::h2 "Installing default packages."
    # 'dnf-plugins-core' installs 'config-manager'.
    sudo dnf -y install dnf-plugins-core util-linux-user
    sudo dnf config-manager --set-enabled PowerTools
    enable-epel

    # Developer {{{1
    # ==========================================================================

    if [[ "$dev" -eq 1 ]]
    then
        koopa::h2 "Installing developer libraries."
        pkgs=(
            libgit2
            libssh2
        )
        sudo dnf -y install "${pkgs[@]}"
    fi

    # Extra {{{1
    # ==========================================================================

    if [[ "$extra" -eq 1 ]]
    then
        koopa::h2 "Installing extra recommended packages."
        sudo dnf -y install python3
    fi

    koopa::install_success "$name_fancy"
    return 0
}

koopa::install_rhel_base "$@"
