#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

name="shiny-server"

_koopa_exit_if_docker
_koopa_exit_if_installed "$name"
_koopa_assert_has_no_args "$@"
_koopa_assert_is_rhel_7
_koopa_assert_is_installed R
_koopa_assert_is_r_package_installed shiny

tmp_dir="$(_koopa_tmp_dir)/${name}"
version="$(_koopa_variable "$name")"

_koopa_h1 "Installing ${name} ${version}."

(
    _koopa_cd_tmp_dir "$tmp_dir"
    file="shiny-server-${version}-x86_64.rpm"
    url="https://download3.rstudio.org/centos6.3/x86_64/${file}"
    _koopa_download "$url"
    sudo yum install -y --nogpgcheck "$file"
)

rm -fr "$tmp_dir"

_koopa_success "Installation of $name was successful."
