#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# Is LLVM 8+ available yet?
#
# Missing:
# - 'llvm7*'
# - file-devel
# - fish
# - gdal
# - gdal-devel
# - leptonica-devel
# - neovim
# - pandoc
# - pandoc-citeproc
# - poppler-cpp-devel
# """

all=0
dev=0
extra=0

while (("$#"))
do
    case "$1" in
        --all)
            all=1
            shift 1
            ;;
        --build-dep)
            # Passthrough to 'install-fedora-base'.
            shift 1
            ;;
        --dev)
            dev=1
            shift 1
            ;;
        --dist-upgrade)
            # Passthrough to 'install-fedora-base'.
            shift 1
            ;;
        --extra)
            extra=1
            shift 1
            ;;
        *)
            _koopa_invalid_arg "$1"
            ;;
    esac
done

if [[ "$all" -eq 1 ]]
then
    dev=1
    extra=1
fi

_koopa_h1 "Installing Red Hat Enterprise Linux (RHEL) 8 base system."

install-fedora-base "$@"

# default  {{{1
# ==============================================================================

_koopa_h2 "Installing default packages."
sudo yum -y install util-linux-user

# developer  {{{1
# ==============================================================================

if [[ "$dev" -eq 1 ]]
then
    _koopa_h2 "Installing developer libraries."
    pkgs=(
        libgit2
        libssh2
    )
    sudo yum -y install "${pkgs[@]}"
fi

# extra  {{{1
# ==============================================================================

if [[ "$extra" -eq 1 ]]
then
    _koopa_h2 "Installing extra recommended packages."
    sudo yum -y install python3
fi
