#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# Is LLVM 8+ available yet?
#
# Missing:
# - 'llvm7*'
# - file-devel
# - fish
# - gdal
# - gdal-devel
# - leptonica-devel
# - neovim
# - pandoc
# - pandoc-citeproc
# - poppler-cpp-devel
# """

_koopa_h2 "Installing Red Hat Enterprise Linux (RHEL) 8 base system."

_koopa_assert_has_no_args "$@"
_koopa_assert_is_installed sudo

install-fedora-base
sudo yum -y install \
    libgit2 \
    libssh2 \
    python3 \
    util-linux-user
