#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

# """
# RStudio Server on Fedora / RHEL / CentOS.
# https://rstudio.com/products/rstudio/download-server/redhat-centos/
#
# System config:
# /etc/rstudio
#
# Verify install:
# > sudo rstudio-server stop
# > sudo rstudio-server verify-installation
# > sudo rstudio-server start
# > sudo rstudio-server status
# """

reinstall=0
pos=()
while (("$#"))
do
    case "$1" in
        --reinstall)
            reinstall=1
            shift 1
            ;;
        --)
            shift 1
            break
            ;;
        --*|-*)
            koopa::invalid_arg "$1"
            ;;
        *)
            pos+=("$1")
            shift 1
            ;;
    esac
done
[[ "${#pos[@]}" -gt 0 ]] && set -- "${pos[@]}"

name="rstudio-server"
version="$(koopa::variable "$name")"
name_fancy="RStudio Server ${version}"

if ! koopa::is_current_version "$name"
then
    reinstall=1
fi

if [[ "$reinstall" -eq 0 ]]
then
    koopa::exit_if_installed "$name"
fi

koopa::install_start "$name_fancy"

koopa::assert_has_no_args "$@"
koopa::assert_is_installed R

if koopa::is_rhel_8
then
    os_id="fedora28"
else
    koopa::stop "Unsupported RHEL/CentOS version."
fi

tmp_dir="$(koopa::tmp_dir)"

(
    koopa::cd_tmp_dir "$tmp_dir"
    rm -fr "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="${name}-rhel-${version}-x86_64.rpm"
    url="https://download2.rstudio.org/server/${os_id}/x86_64/${file}"
    koopa::download "$url"
    sudo yum -y install "$file"
) 2>&1 | tee "$(koopa::tmp_log_file)"

rm -fr "$tmp_dir"

koopa::install_success "$name_fancy"
