#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

dev=1
extra=1

_koopa_assert_has_no_args "$@"

_koopa_is_docker && extra=0

# Install Fedora base first.
"${script_dir}/../../fedora/sbin/install-base" "$@"

name_fancy="Red Hat Enterprise Linux (RHEL) base system"

_koopa_install_start "$name_fancy"

# default {{{1
# ==============================================================================

_koopa_h2 "Installing default packages."

# 'dnf-plugins-core' installs 'config-manager'.
sudo dnf -y install dnf-plugins-core util-linux-user
sudo dnf config-manager --set-enabled PowerTools
enable-epel

# developer {{{1
# ==============================================================================

if [[ "$dev" -eq 1 ]]
then
    _koopa_h2 "Installing developer libraries."
    pkgs=(
        libgit2
        libssh2
    )
    sudo dnf -y install "${pkgs[@]}"
fi

# extra {{{1
# ==============================================================================

if [[ "$extra" -eq 1 ]]
then
    _koopa_h2 "Installing extra recommended packages."
    sudo dnf -y install python3
fi

_koopa_install_success "$name_fancy"
