#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_exit_if_installed yum-cron
_koopa_assert_is_installed systemctl

# Note that this requires EPEL to be enabled.
sudo yum -y install yum-cron

sudo systemctl enable yum-cron.service
sudo systemctl start yum-cron.service
# > sudo systemctl status yum-cron.service

_koopa_success "Installation of yum-cron was successful."
