#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_koopa_assert_has_no_args "$@"


name="rstudio-server-pro"
tmp_dir="$(_koopa_tmp_dir)/${name}"
version="$(_koopa_variable "$name")"

if _koopa_is_rhel_7
then
    os_id="centos6"
elif _koopa_is_rhel_8
then
    os_id="fedora28"
else
    _koopa_stop "RHEL 7 or 8 is required."
fi

_koopa_message "Installing ${name} ${version} (${os_id})."

# Remove existing config files.
# > sudo rm -frv /etc/rstudio

(
    rm -fr "$tmp_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir" || exit 1
    file="rstudio-server-rhel-pro-${version}-x86_64.rpm"
    url="https://download2.rstudio.org/server/${os_id}/x86_64/${file}"
    _koopa_download "$url"
    sudo yum -y install "$file"
    rm -fr "$tmp_dir"
)

# > sudo "$name" stop
# > sudo "$name" verify-installation
# > sudo "$name" start
# > sudo "$name" status
# > sudo "$name" license-manager status

command -v rstudio-server
rstudio-server version
rstudio-server license-manager verify

cat << EOF
Activate product license key (if necessary):
> sudo rstudio-server license-manager activate <product-key>

If you want to move your license of RStudio Server to another system you should
first deactivate it on the old system with the command:
> sudo rstudio-server license-manager deactivate
EOF

