#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_exit_if_docker
_koopa_exit_if_installed docker

name_fancy="Docker"

_koopa_install_start "$name_fancy"

_koopa_assert_has_no_args "$@"
_koopa_assert_is_installed systemctl

# Remove legacy versions, if necessary.
sudo yum -y remove \
    docker \
    docker-client \
    docker-client-latest \
    docker-common \
    docker-engine \
    docker-latest \
    docker-latest-logrotate \
    docker-logrotate

sudo yum -y install \
    device-mapper-persistent-data \
    lvm2 \
    yum-utils

sudo yum-config-manager \
    --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum repolist

sudo yum -y install containerd.io
sudo yum -y install docker-ce docker-ce-cli

# Ensure current user is added to Docker group.
_koopa_add_user_to_group "docker"

# Move '/var/lib/docker' to '/n/var/lib/docker'.
_koopa_link_docker

# Ready to start Docker.
sudo systemctl start docker

_koopa_install_success "$name_fancy"
_koopa_restart
