install.packages("BiocManager")

install.packages("remotes")

library(BiocManager)
library(remotes)



## CRAN ====
install("Rcpp")
install("RcppArmadillo")
install("RcppRoll")
install("data.table")
install("dplyr")
install("shiny")
install("shinydashboard")
install("tidyverse")
install("rgl")

install("ADGofTest")
install("CVST")
install("DT")
install("DiagrammeR")
install("GSA")
install("KMsurv")
install("Seurat")
install("VennDiagram")
install("ade4")
install("assertr")
install("available")
install("aws.signature")
install("bindr")
install("bindrcpp")
install("caret")
install("cmprsk")
install("dimRed")
install("diptest")
install("downloader")
install("dynamicTreeCut")
install("exactRankTests")
install("flexmix")
install("fpc")
install("ggpubr")
install("ggsci")
install("ggsignif")
install("janitor")
install("km.ci")
install("lars")
install("maxstat")
install("mixtools")
install("mongolite")
install("morpheus")
install("msigdbr")
install("profvis")
install("pspline")
install("rentrez")
install("snakecase")
install("stabledist")
install("survMisc")
install("survminer")
install("tesseract")
install("trimcluster")
install("varhandle")
install("visNetwork")
install("xlsx")

## cBioPortal
install("cgdsr")



## Bioconductor ====
install("BiocCheck")
install("BiocVersion")
install("ChIPpeakAnno")
install("ChIPseeker")
install("DESeq2")
install("DiffBind")
install("GEOquery")
install("GenomicFiles")
install("Homo.sapiens")
install("OrganismDbi")
install("Rqc")
install("TxDb.Hsapiens.UCSC.hg19.knownGene")
install("TxDb.Hsapiens.UCSC.hg38.knownGene")
install("bamsignals")
install("biovizBase")
install("bumphunter")
install("ddalpha")
install("derfinder")
install("derfinderHelper")
install("ggbio")
install("monocle")
install("scater")
install("scran")



## GitHub ====
install_github("cole-trapnell-lab/monocle3")

install_github("acidgenomics/basejump")
install_github("acidgenomics/acidplots")
install_github("acidgenomics/bcbioRNASeq")
install_github("acidgenomics/bcbioSingleCell")
install_github("acidgenomics/DESeqAnalysis")
install_github("acidgenomics/pfgsea")
install_github("acidgenomics/Chromium")
install_github("acidgenomics/pointillism")

install_github("acidgenomics/lintr")
install_github("acidgenomics/bb8")
