#!/usr/bin/env Rscript

args <- commandArgs()
whichFile <- grep(pattern = "--file", x = args)
file <- args[whichFile]
file <- sub(pattern = "^--file=", replacement = "", x = file)
koopaPrefix <- normalizePath(file.path(dirname(file), ".."))
source(file.path(koopaPrefix, "lang", "r", "include", "header.R"))

local({
    args <- parseArgs(
        flags = c("prefix", "recursive"),
        positional = TRUE
    )
    positional <- args[["positional"]]
    prefix <- "prefix" %in% args[["flags"]]
    recursive <- "recursive" %in% args[["flags"]]
    kebabCase(
        object = positional,
        rename = TRUE,
        recursive = recursive,
        prefix = prefix
    )
})
