.TH BCBIO-ADMIN-RUN-TESTS 1 2019-11-09 Bash
.SH NAME
bcbio-admin-run-tests \-
Run bcbio unit tests
.SH SYNOPSIS
.B bcbio-admin-run-tests
[\fB\-\-bcbio-prefix="/usr/local/bcbio"\fP]
[\fB\-\-version="development"\fP]
.SH OPTIONS
.TP
.B \-\-bcbio-prefix
Top level bcbio installation prefix. On a typical VM setup, this will include 'development' and 'stable' subdirectories, and potentially additional versioned installs (e.g. 1.1.8).
.TP
.B \-\-version
Versioned bcbio installation subdirectory name inside prefix defined by '\-\-bcbio-prefix' flag. Defaults to 'development' but 'stable' will also work on a standard VM setup.
.SH DESCRIPTION
Run RNA-seq and ChIP-seq unit tests.
.SH SEE ALSO
Refer to 'tests/data/automated/' for YAML recipes.
