.TH PATCH-BCBIO 1 2019-12-02 Bash
.SH NAME
patch-bcbio \-
Patch bcbio-nextgen installation
.SH SYNOPSIS
.B patch-bcbio
[\fB\-\-git-dir\fP=\fI"~/git/bcbio-nextgen"\fP]
[\fB\-\-bcbio-python\fP=\fI"AUTO"\fP]
[\fB\-\-install-dir\fP=\fI"AUTO"\fP]
.SH OPTIONS
.TP
.B \-\-git-dir
(Forked) bcbio-nextgen git repo.
.TP
.B \-\-bcbio-python
Path to 'bcbio_python'.
If unset, the script attempts to locate automatically, based on PATH.
.TP
.B \-\-install-dir
Path to bcbio installation.
This is the path that contains 'anaconda/', 'config/', 'galaxy/', 'genomes/',
and 'manifest/' subdirectories.
For example, on Azure this is '/data00/bcbio/development/install'.
If unset, the script attempts to locate automatically based on '--bcbio-python'.
.SH DESCRIPTION
Patch bcbio-nextgen installation.
.SH EXAMPLE
.nf
.B patch-bcbio \-\-git-dir="~/git/bcbio-nextgen" \-\-bcbio-python="/usr/local/bcbio/development/tools/bin/bcbio_python"
.fi
.SH SEE ALSO
https://bcbio-nextgen.readthedocs.io/
