#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header bash)"

test_docker() {
    # """
    # Install and test koopa inside Docker.
    # Updated 2022-10-07.
    # """
    local app dict
    koopa_assert_has_args_le "$#" 1
    declare -A app
    declare -A dict
    app['docker']="$(koopa_locate_docker)"
    [[ -x "${app['docker']}" ]] || return 1
    dict['distro']="${1:-debian}"
    dict['image']="acidgenomics/koopa:${dict['distro']}"
    koopa_alert "Running Docker test in '${dict['image']}' image."
    dict['cmd']="\
        if [ -d '/opt/koopa' ]; \
        then sudo rm -fr '/opt/koopa'; \
        else rm -fr ~/.local/share/koopa; fi \
     && curl -sSL https://koopa.acidgenomics.com/install \
            | bash -s -- --non-interactive --test"
    "${app['docker']}" pull "${dict['image']}"
    "${app['docker']}" run -it "${dict['image']}" bash -c "${dict['cmd']}"
    koopa_alert_success 'Installation test was successful.'
    return 0
}

test_docker "$@"
