#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(koopa header bash)"

main() {
    # """
    # Check that all scripts support '--help' flag.
    # Updated 2022-10-07.
    # """
    local app dict man_file man_files
    declare -A app
    app['head']="$(koopa_locate_head)"
    [[ -x "${app['head']}" ]] || return 1
    declare -A dict=(
        ['man_prefix']="$(koopa_man_prefix)"
        ['status']=0
    )
    koopa_alert 'Running man file integrity checks.'
    readarray -t man_files <<< "$( \
        koopa_find \
            --max-depth=1 \
            --min-depth=1 \
            --pattern='*.1' \
            --prefix="${dict['man_prefix']}/man1" \
            --sort \
            --type 'f' \
    )"
    koopa_assert_is_array_non_empty "${man_files[@]:-}"
    for man_file in "${man_files[@]}"
    do
        if ! koopa_str_detect_regex \
            --string="$("${app['head']}" -n 1 "$man_file")" \
            --pattern='^\.TH '
        then
            koopa_alert_note "ERROR: '${man_file}'."
            dict['status']=1
        fi
    done
    return "${dict['status']}"
}

main "$@"
