#!/usr/bin/env zsh
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${(%):-%N}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

autoload -Uz compaudit

if [ -z "$(compaudit 2>/dev/null)" ]
then
    _koopa_success "Zsh compinit is configured correctly."
    exit 0
fi

_koopa_h1 "Fixing Zsh compinit configuration with compaudit."
compaudit 2>/dev/null | xargs sudo chmod g-w
