.TH AWS-BATCH-FETCH-AND-RUN 1 2020-05-03 Bash
.SH NAME
aws-batch-fetch-and-run \-
AWS Batch fetch and run
.SH SYNOPSIS
.B aws-batch-fetch-and-run
.SH DESCRIPTION
Fetch and run a script from S3 on AWS Batch.
Requires definition of 'BATCH_FILE_URL' global variable.
.SH SEE ALSO
.IP
\(bu
.UR https://aws.amazon.com/blogs/compute/creating-a-simple-fetch-and-run-aws-batch-job/
Creating a simple "fetch and run" AWS batch job
.UE
.IP
\(bu
.UR https://github.com/FredHutch/url-fetch-and-run
FredHutch url-fetch-and-run GitHub repo
.UE
.IP
\(bu
.UR https://fredhutch.github.io/aws-batch-at-hutch-docs/
Using AWS Batch at Fred Hutch
.UE
.SH EXAMPLES
.nf
.B export BATCH_FILE_URL="s3://batch/test.sh"
.B aws-batch-fetch-and-run
.fi
