.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CONDA\-CREATE\-BIOINFO\-ENVS" "1" "February 2021" "" ""
.
.SH "NAME"
\fBconda\-create\-bioinfo\-envs\fR \- create conda environments for bioinformatics
.
.SH "SYNOPSIS"
\fBconda\-create\-bioinfo\-envs\fR [\fB\-\-all\fR]
.
.SH "DESCRIPTION"
Installs non\-R bioinformatics tools\. For R, compile from source instead\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-all\fR
Install all (extra) conda environments\.

