.TH CONDA-CREATE-ENV-BIOINFO 1 2019-10-26 Bash
.SH NAME
conda-create-env-bioinfo \- create multiple conda environments for bioinformatics
.SH SYNOPSIS
.B conda-create-env-bioinfo
.SH DESCRIPTION
Create multiple Conda environments for bioinformatics.
Installs non-R bioinformatics tools.
For R, compile from source instead.
