.TH CONDA-CREATE-ENV 1 2019-10-26 Bash
.SH NAME
conda-create-env \- create a conda environment
.SH SYNOPSIS
.B conda-create-env
.IR name
.SH DESCRIPTION
Quickly create a new conda environment based on a single recipe NAME, without prompting.
.SH EXAMPLE
conda-create-env kallisto
.SH SEE ALSO
.IP
\(bu conda create
.IP
\(bu https://steinbaugh.com/posts/conda.html
