.TH CONDA-CREATE-ENV-INTERNAL 1 2019-11-09 Bash
.SH NAME
conda-create-env-internal \-
Create an internal Conda environment
.SH SYNOPSIS
.B conda-create-env-internal
.IR NAME
.SH DESCRIPTION
Create an internal conda environment that isn't accessible by name in the environment list.
Useful when running on a conservative Linux release (i.e. RHEL 7) that bundles very old versions of software that are hard to install. This can be a useful approach to upgrading Pandoc or TeX Live, for example.
.SH EXAMPLE
conda-create-env-internal pandoc
.SH SEE ALSO
.IP
\(bu conda env list
.IP
\(bu https://steinbaugh.com/posts/conda.html
