.TH CONDA-CREATE-ENV-INTERNAL 1 2019-10-26 Bash
.SH NAME
conda-create-env-internal \- create a python development conda environment
.SH SYNOPSIS
.B conda-create-env-python-dev
.SH DESCRIPTION
Create a Python developer environment, which bundles some useful packages for unit testing and code linting.
Consider using Spacemacs, Doom Emacs, or Vim as a Python IDE.
.PP
Code formatting:
    - black
      https://pypi.org/project/black/
    - flake8
      http://flake8.pycqa.org/
.PP
Linters:
    - pylint
      https://www.pylint.org/
    - pyflakes
      https://pypi.org/project/pyflakes/
.PP
Unit testing:
    - pytest
      http://pytest.org/
.SH EXAMPLE
conda-create-env-python-dev
.SH SEE ALSO
IDE options:
    - Visual Studio Code
    - Spyder
    - PyCharm
    - Jupyter
.PP
https://steinbaugh.com/posts/conda.html
