.TH CONDA-CREATE-ENV 1 2019-11-09 Bash
.SH NAME
conda-create-env \-
Create a Conda environment
.SH SYNOPSIS
.B conda-create-env
.I name
.SH OPTIONS
.TP
.B name
Environment name.
.SH DESCRIPTION
Quickly create a new conda environment based on a single recipe NAME, without
prompting.
.SH EXAMPLE
.nf
.B conda-create-env kallisto
.fi
.SH SEE ALSO
.IP
\(bu conda create
.IP
\(bu https://steinbaugh.com/posts/conda.html
