.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "COPY\-BAM\-FILES" "1" "February 2021" "" ""
.
.SH "NAME"
\fBcopy\-bam\-files\fR \- copy bam files
.
.SH "SYNOPSIS"
copy\-bam\-files \fIsource_dir\fR \fItarget_dir\fR
.
.SH "DESCRIPTION"
Copy multiple BAM and corresponding BAM\.BAI index files from a source directory to a target directory\.
.
.SH "OPTIONS"
.
.TP
\fIsource_dir\fR
Source directory\.
.
.TP
\fItarget_dir\fR
Target directory\.

