.TH CURRENT-FLYBASE-VERSION 1 2020-01-20 Bash
.SH NAME
current-flybase-version \-
FlyBase release version
.SH SYNOPSIS
.B current-flybase-version
[\fB--dmel\fP]
.SH OPTIONS
.TP
.B \-\-dmel
Return the current Drosophila melanogaster genome build version.
Example: 'dmel_r6.29'.
.SH DESCRIPTION
Extract the current FlyBase release version from ftp.flybase.net.
Example: 'FB2019_04'.
.SH SEE ALSO
https://flybase.org/
