.TH DOCKER-RUN-IMAGE 1 2019-11-10 Bash
.SH NAME
docker-run-image \-
Pull and run a Docker image
.SH SYNOPSIS
.B docker-run-image
[\fB\-\-bash\fP]
[\fB\-\-workdir\fP=\fI"/mnt/work"\fP]
.I image
.SH OPTIONS
.TP
.B \-\-bash
Run image as an interactive Bash session.
.TP
.B \-\-workdir
Local working directory mount path.
.TP
.B IMAGE
Docker image name. Use the full name: '<user>/<image>:<tag>'. Defaults to images on DockerHub. Tag is optional, but can be included (e.g. ':latest').
.SH DESCRIPTION
Script wrapper to call 'docker pull' and 'docker run' with suitable defaults for the Acid Genomics Docker images available on Docker Hub.
.SH EXAMPLE
.nf
.B docker-run-image acidgenomics/bioconductor:devel
.fi
