.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DOWNLOAD\-REFSEQ\-GENOME" "1" "August 2020" "" ""
.
.SH "NAME"
\fBdownload\-refseq\-genome\fR \- download refseq genome
.
.SH "SYNOPSIS"
\fBdownload\-refseq\-genome\fR [\fB\-\-build\fR=\fIbuild\fR] [\fB\-\-type\fR=\fItype\fR] [\fB\-\-annotation\fR=\fIannotation\fR] [\fB\-\-output\-dir\fR=\fIoutput_dir\fR] [\fB\-\-decompress\fR]
.
.SH "DESCRIPTION"
Download RefSeq genome and corresponding annotation files\. Creates a new directory in the current working directory\. Only \fIHomo sapiens\fR genome is supported\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-\-build\fR=\fIbuild\fR: Genome build (e\.g\. "GRCh38")\. Defaults to GRCh38\.
.
.IP "\(bu" 4
\fB\-\-type\fR=\fItype\fR: Genome type: \fBall\fR (default): Download all reference types; \fBgenome\fR: Primary assembly (DNA); \fBtranscriptome\fR: Transcripts (cDNA/RNA); \fBnone\fR: Skip download\.
.
.IP "\(bu" 4
\fB\-\-annotation\fR=\fIannotation\fR: \fBall\fR (default): Download all annotation formats; \fBgtf\fR: GTF (GFFv2); \fBgff\fR: GFF3; \fBnone\fR: Skip download\.
.
.IP "\(bu" 4
\fB\-\-output\-dir\fR=\fIoutput_dir\fR Output directory\. Defaults to working directory\.
.
.IP "\(bu" 4
\fB\-\-decompress\fR: Decompress files (but keep the compressed originals)\.
.
.IP "" 0
.
.SH "SEE ALSO"
Primary RefSeq URLs:
.
.IP "\(bu" 4
https://www\.ncbi\.nlm\.nih\.gov/projects/genome/guide/human/
.
.IP "\(bu" 4
ftp://ftp\.ncbi\.nlm\.nih\.gov/refseq/
.
.IP "\(bu" 4
ftp://ftp\.ncbi\.nlm\.nih\.gov/genomes/refseq/
.
.IP "" 0
.
.P
Current GRCh38 assembly: ftp://ftp\.ncbi\.nlm\.nih\.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/
.
.IP "\(bu" 4
DNA: GRCh38_latest_genomic\.fna\.gz
.
.IP "\(bu" 4
RNA: GRCh38_latest_rna\.fna\.gz
.
.IP "\(bu" 4
GTF: GRCh38_latest_genomic\.gtf\.gz
.
.IP "\(bu" 4
GFF: GRCh38_latest_genomic\.gff\.gz
.
.IP "" 0
.
.P
Preformatted for analysis pipelines (UCSC IDs): ftp://ftp\.ncbi\.nlm\.nih\.gov/genomes/all/GCA/000/001/405/GCA_000001405\.15_GRCh38/seqs_for_alignment_pipelines\.ucsc_ids/
.
.IP "\(bu" 4
Full: GCA_000001405\.15_GRCh38_full_analysis_set\.fna\.gz
.
.IP "\(bu" 4
No ALT: GCA_000001405\.15_GRCh38_no_alt_analysis_set\.fna\.gz
.
.IP "" 0
.
.P
Full version information in URL: ftp://ftp\.ncbi\.nlm\.nih\.gov/genomes/Homo_sapiens/109\.20190905/GCF_000001405\.39_GRCh38\.p13/
.
.IP "\(bu" 4
DNA: GCF_000001405\.39_GRCh38\.p13_genomic\.fna\.gz
.
.IP "\(bu" 4
RNA: GCF_000001405\.39_GRCh38\.p13_rna\.fna\.gz
.
.IP "\(bu" 4
GTF: GCF_000001405\.39_GRCh38\.p13_genomic\.gtf\.gz
.
.IP "\(bu" 4
GFF: GCF_000001405\.39_GRCh38\.p13_genomic\.gff\.gz
.
.IP "" 0
.
.P
Alternate paths:
.
.IP "\(bu" 4
ftp://ftp\.ncbi\.nlm\.nih\.gov/genomes/Homo_sapiens/
.
.IP "\(bu" 4
ftp://ftp\.ncbi\.nlm\.nih\.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/
.
.IP "" 0
.
.SH "NOTE"
Python script\.
