.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DOWNLOAD\-REFSEQ\-GENOME" "1" "August 2021" "" ""
.
.SH "NAME"
\fBdownload\-refseq\-genome\fR \- download refseq genome
.
.SH "SYNOPSIS"
\fBdownload\-refseq\-genome\fR \fB\-\-organism\fR=\fIorganism\fR [\fB\-\-taxonomic\-group\fR=\fItaxonomic_group\fR] [\fB\-\-genome\-build\fR=\fIgenome_build\fR] [\fB\-\-output\-dir\fR=\fIoutput_dir\fR]
.
.SH "DESCRIPTION"
Download RefSeq genome and corresponding annotation files\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fBorganism\fR=\fIorganism\fR: Full Latin organism name (e\.g\. \fB"Homo sapiens"\fR)\.
.
.IP "\(bu" 4
\fBtaxonomic\-group\fR=\fItaxonomic_group\fR: NCBI FTP server taxnomic group subdirectory path (e\.g\. \fB"vertebrate_mammalian"\fR)\. Defining this manually avoids having to query the FTP server\.
.
.IP "\(bu" 4
\fB\-\-genome\-build\fR=\fIbuild\fR: Genome build (e\.g\. \fB"GCF_000001405\.39_GRCh38\.p12"\fR)\. Defaults to current genome build\.
.
.IP "\(bu" 4
\fB\-\-output\-dir\fR=\fIoutput_dir\fR Output directory\. Defaults to working directory\.
.
.IP "" 0
.
.SH "SEE ALSO"
Primary RefSeq URLs:
.
.IP "\(bu" 4
https://www\.ncbi\.nlm\.nih\.gov/projects/genome/guide/human/
.
.IP "\(bu" 4
ftp://ftp\.ncbi\.nlm\.nih\.gov/refseq/
.
.IP "\(bu" 4
ftp://ftp\.ncbi\.nlm\.nih\.gov/genomes/refseq/
.
.IP "" 0
.
.P
Current GRCh38 assembly: ftp://ftp\.ncbi\.nlm\.nih\.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/
.
.IP "\(bu" 4
DNA: GRCh38_latest_genomic\.fna\.gz
.
.IP "\(bu" 4
RNA: GRCh38_latest_rna\.fna\.gz
.
.IP "\(bu" 4
GTF: GRCh38_latest_genomic\.gtf\.gz
.
.IP "\(bu" 4
GFF: GRCh38_latest_genomic\.gff\.gz
.
.IP "" 0
.
.P
Preformatted for analysis pipelines (UCSC IDs): ftp://ftp\.ncbi\.nlm\.nih\.gov/genomes/all/GCA/000/001/405/GCA_000001405\.15_GRCh38/seqs_for_alignment_pipelines\.ucsc_ids/
.
.IP "\(bu" 4
Full: GCA_000001405\.15_GRCh38_full_analysis_set\.fna\.gz
.
.IP "\(bu" 4
No ALT: GCA_000001405\.15_GRCh38_no_alt_analysis_set\.fna\.gz
.
.IP "" 0
.
.P
Full version information in URL: ftp://ftp\.ncbi\.nlm\.nih\.gov/genomes/Homo_sapiens/109\.20190905/GCF_000001405\.39_GRCh38\.p13/
.
.IP "\(bu" 4
DNA: GCF_000001405\.39_GRCh38\.p13_genomic\.fna\.gz
.
.IP "\(bu" 4
RNA: GCF_000001405\.39_GRCh38\.p13_rna\.fna\.gz
.
.IP "\(bu" 4
GTF: GCF_000001405\.39_GRCh38\.p13_genomic\.gtf\.gz
.
.IP "\(bu" 4
GFF: GCF_000001405\.39_GRCh38\.p13_genomic\.gff\.gz
.
.IP "" 0
.
.P
Alternate paths:
.
.IP "\(bu" 4
ftp://ftp\.ncbi\.nlm\.nih\.gov/genomes/Homo_sapiens/
.
.IP "\(bu" 4
ftp://ftp\.ncbi\.nlm\.nih\.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/
.
.IP "" 0
.
.SH "NOTE"
R function, defined in r\-acidgenomes package\.
