.TH DOWNLOAD-SRA-ACCESSION-LIST 1 2019-11-20 Bash
.SH NAME
download-sra-accession-list \-
Download SRA accession list
.SH SYNOPSIS
.B download-sra-accession-list
.I id
[file=\fI"SraAccList.txt"\fP]
.SH OPTIONS
.TP
.B id
SRP or PRJNA project identifier.
.TP
.B file
Output file.
.SH EXAMPLE
.nf
.B download-sra-accession-list SRP000000
.PP
.B download-sra-accession-list PRJNA000000
.fi
.SH NOTE
Requires efetch from entrez-direct to be installed. Available via bioconda.
