.TH DOWNLOAD-SRA-RUN-INFO-TABLE 1 2019-11-20 Bash
.SH NAME
download-sra-run-info-table \-
Download SRA run info table
.SH SYNOPSIS
.B download-sra-run-info-table
.I id
[file=\fI"SraRunTable.txt"\fP]
.SH OPTIONS
.TP
.B id
SRP or PRJNA project identifier.
.TP
.B file
Output file.
.SH EXAMPLE
.nf
.B download-sra-run-info-table SRP000000
.PP
.B download-sra-run-info-table PRJNA000000
.fi
.SH NOTE
Requires efetch from entrez-direct to be installed. Available via bioconda.
