.TH DOWNLOAD-GSEA-MSIGDB-SCSIG 1 2019-11-10 Bash
.SH NAME
download-gsea-msigdb-scsig \-
Download GSEA MSigDb SCSig gene set signature files
.SH SYNOPSIS
.B download-gsea-msigdb-scsig
.SH DESCRIPTION
SCSig collection: Signatures of Single Cell Identities.
.SH NOTE
Always downloads to the current working directory.
