.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DOWNLOAD\-ENSEMBL\-GENOME" "1" "August 2021" "" ""
.
.SH "NAME"
\fBdownload\-ensembl\-genome\fR \- download ensembl genome
.
.SH "SYNOPSIS"
\fBdownload\-ensembl\-genome\fR \fB\-\-organism\fR=\fIorganism\fR [\fB\-\-genome\-build\fR=\fIgenome_build\fR] [\fB\-\-release\fR=\fIrelease\fR] [\fB\-\-output\-dir\fR=\fIoutput_dir\fR] [\fB\-\-decompress\fR]
.
.SH "DESCRIPTION"
Download Ensembl genome and corresponding annotation files\.
.
.P
Creates a new directory in the current working directory by default\.
.
.P
\fBImportant!\fR When working in R, be sure to match the Ensembl release version to the latest version supported by AnnotationHub\.
.
.P
The legacy Homo sapiens GRCh37 (hg19) genome build is supported\. If requested, the release version is set internally automatically\.
.
.P
Verify checksums in shell with:
.
.IP "" 4
.
.nf

$ grep "$(sum *\.gz)" "CHECKSUMS"
.
.fi
.
.IP "" 0
.
.SH "OPTIONS"
.
.TP
\fB\-\-organism\fR=\fIorganism\fR
Latin name (e\.g\. \fB"Homo sapiens"\fR)\.
.
.TP
\fB\-\-genome\-build\fR=\fIgenome_build\fR
Genome build (e\.g\. \fB"GRCh38"\fR)\. Defaults to current genome build\.
.
.TP
\fB\-\-release\fR=\fIrelease\fR
Ensembl release version (e\.g\. \fB100\fR)\. Defaults to current release\.
.
.TP
\fB\-\-output\-dir\fR=\fIoutput_dir\fR
Output directory\. Defaults to working directory\.
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
https://useast\.ensembl\.org/
.
.IP "\(bu" 4
ftp://ftp\.ensembl\.org/pub/
.
.IP "" 0
.
.P
Which Homo sapiens genome assembly FASTA to use?
.
.IP "\(bu" 4
https://steinbaugh\.com/posts/bcbio\-homo\-sapiens\-genome\.html
.
.IP "\(bu" 4
https://lh3\.github\.io/2017/11/13/which\-human\-reference\-genome\-to\-use
.
.IP "\(bu" 4
https://bioinformatics\.stackexchange\.com/questions/540/
.
.IP "" 0
.
.P
Using STAR aligner for RNA\-seq? Here\'s a relevant section from the manual: https://github\.com/alexdobin/STAR/blob/master/doc/STARmanual\.pdf
.
.IP "" 4
.
.nf

## 2\.2\.1 Which chromosomes/scaffolds/patches to include?
## Examples of acceptable genome sequence files:
## \- ENSEMBL: files marked with \'\.dna\.primary\.assembly\'\.
## \- GENCODE: files marked with PRI (primary)\.
.
.fi
.
.IP "" 0
.
.P
GRCh38 alternatives to Ensembl primary assembly:
.
.IP "\(bu" 4
GENCODE assembly\.
.
.IP "\(bu" 4
ftp://ftp\.ncbi\.nlm\.nih\.gov/genomes/all/GCA/000/001/405/ GCA_000001405\.15_GRCh38/ seqs_for_alignment_pipelines\.ucsc_ids/ GCA_000001405\.15_GRCh38_no_alt_analysis_set\.fna\.gz
.
.IP "\(bu" 4
ftp://ftp\.ncbi\.nlm\.nih\.gov/genbank/genomes/Eukaryotes/ vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines/ GCA_000001405\.15_GRCh38_full_plus_hs38d1_analysis_set\.fna
.
.IP "\(bu" 4
http://ftp\.1000genomes\.ebi\.ac\.uk/vol1/ftp/technical/reference/ GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla\.fa
.
.IP "" 0
.
.P
GRCh37 alternatives to Ensembl primary assembly:
.
.IP "\(bu" 4
ftp://ftp\-trace\.ncbi\.nih\.gov/1000genomes/ftp/technical/reference/ human_g1k_v37\.fasta\.gz
.
.IP "" 0
.
.P
Note that Ensembl GTF is missing annotations for some transcripts defined in transcriptome FASTA (human and mouse)\. In this case, use \'*\.chr_patch_hapl_scaff\.gtf\.gz\' GTF file for annotations\.
.
.P
See related issues:
.
.IP "\(bu" 4
https://github\.com/COMBINE\-lab/salmon/issues/122
.
.IP "\(bu" 4
https://github\.com/COMBINE\-lab/salmon/issues/336
.
.IP "" 0
.
.SH "NOTE"
R function, defined in r\-acidgenomes package\.
