.TH DOWNLOAD-SRA-RUN-TABLE 1 2019-11-20 Bash
.SH NAME
download-sra-run-table \-
Download SRA run table
.SH SYNOPSIS
.B download-sra-run-table
ID [FILE="SraRunTable.txt"]
.SH OPTIONS
.TP
.BR ID
SRP or PRJNA project identifier.
.TP
.BR FILE
Output file.
.SH EXAMPLE
download-sra-run-table SRP000000
.PP
download-sra-run-table PRJNA000000
.SH NOTE
Requires efetch from entrez-direct to be installed. Available via bioconda.
