.TH EXTRACT 1 2019-11-10 Bash
.SH NAME
extract \-
Extract files from a compressed archive
.SH SYNOPSIS
.B extract
.I file
.SH DESCRIPTION
Decompress a compressed archive file automatically without having to manually set any file format flags, such as those that need to be based to 'tar'.
.SH EXAMPLE
.nf
.B extract example.tar.gz
.fi
