.TH FASTQ-LANEPOOL 1 2019-12-02 Bash
.SH NAME
fastq-lanepool \-
Pool (concatenate) lane-split FASTQ files
.SH SYNOPSIS
.B fastq-lanepool
[\fB\-\-source-dir\fP=\fI"XXX"\fP]
[\fB\-\-target-dir\fP=\fI"XXX"\fP]
[\fB\-\-prefix\fP=\fI"XXX"\fP]
.SH OPTIONS
.TP
.B \-\-source-dir
Source directory path containing lane-split FASTQ files.
.TP
.B \-\-target-dir
Target directory path where to return concatenated, lane-pooled FASTQs.
.TP
.B \-\-prefix
Name prefix for concatenated FASTQ files.
.SH DESCRIPTION
Matches against '_L00[1-9]_' lane pattern internally.
Defaults to input and output in current working directory.
Supports both compressed ('*.fastq.gz') and decompressed ('*.fastq') FASTQ files.
.SH EXAMPLE
.nf
.B fastq-lanepool --source-dir="." --target-dir="." --prefix="lanepool"
Input (2 paired-end, lane-split samples):
## sample1_L001_R1.fastq.gz
## sample1_L002_R1.fastq.gz
## sample1_L003_R1.fastq.gz
## sample1_L004_R1.fastq.gz
## sample1_L001_R2.fastq.gz
## sample1_L002_R2.fastq.gz
## sample1_L003_R2.fastq.gz
## sample1_L004_R2.fastq.gz
## sample2_L001_R1.fastq.gz
## sample2_L002_R1.fastq.gz
## sample2_L003_R1.fastq.gz
## sample2_L004_R1.fastq.gz
## sample2_L001_R2.fastq.gz
## sample2_L002_R2.fastq.gz
## sample2_L003_R2.fastq.gz
## sample2_L004_R2.fastq.gz
Output:
## lanepool_sample1_R1.fastq.gz
## lanepool_sample1_R2.fastq.gz
## lanepool_sample2_R1.fastq.gz
## lanepool_sample2_R2.fastq.gz
.fi
