.TH FASTQ-DUMP-FROM-SRA-FILE-LIST 1 2019-12-02 Bash
.SH NAME
fastq-dump-from-sra-file-list \-
FASTQ dump from Sequence Read Archive (SRA) accession list
.SH SYNOPSIS
.B fastq-dump-from-sra-file-list
[filelist=\fI"SRR_Acc_List.txt"\fP]
.SH OPTIONS
.TP
.B filelist
SRA access file list.
.SH DESCRIPTION
Requires sratools to be installed, which contains fastq-dump.
.PP
This script loops across an SRA accession file list and calls 'fastq-dump --split-files' internally.
.PP
Note that this will skip FASTQ files that have already been extracted. This is useful because fastq-dump can take a long time and get interrupted.
.SH SEE ALSO
Use fasterq-dump instead of fastq-dump, since it supports multiple threads.
.PP
Single cell RNA-seq barcode formats:
.IP
\(bu 10X Genomics (https://kb.10xgenomics.com/hc/en-us/articles/115003802691)
.IP
\(bu Harvard inDrops v3 (https://singlecellcore.hms.harvard.edu)
.SH EXAMPLE
.nf
.B fastq-dump-from-sra-file-list SRR_Acc_List.txt
.fi
