.TH FLYBASE-VERSION 1 2019-11-09 Bash
.SH NAME
flybase-version \-
FlyBase release version
.SH SYNOPSIS
.B flybase-version
[\fB--dmel\fP]
.SH OPTIONS
.TP
.B \-\-dmel
Return current Drosophila melanogaster genome build version.
Example: 'dmel_r6.29'.
.SH DESCRIPTION
Extract the FlyBase release version from ftp.flybase.net.
Example: 'FB2019_04'.
.SH SEE ALSO
https://flybase.org/
