.TH GIT-RESET-FORK-TO-UPSTREAM 1 2019-12-02 Bash
.SH NAME
git-reset-fork-to-upstream \-
Reset fork to upstream.
.SH SYNOPSIS
.B git-reset-fork-to-upstream
[dir=\fI"."\fP]
.SH OPTIONS
.B dir
Directory path.
.SH EXAMPLE
.nf
.B git-reset-fork-to-upstream .
.fi
.SH SEE ALSO
https://stackoverflow.com/questions/42332769
