.TH INDROPS-I5-SAMPLE-INDEX-COUNTS 1 2019-12-03 Bash
.SH NAME
indrops-i5-sample-index-counts \-
inDrops sample barcode counts from i5 indexes
.SH SYNOPSIS
.B indrops-i5-sample-index-counts
[dir=\fI"."\fP]
.SH OPTIONS
.TP
.B dir
Directory path.
.SH DESCRIPTION
Checks against R3 FASTQ files inside directory.
Outputs 'sample-barcodes.log' file.
.SH SEE ALSO
https://singlecellcore.hms.harvard.edu/
.SH NOTE
Modified version of script by @roryk.
