.TH INSTALL-CONDA 1 2019-11-06 Bash
.SH NAME
install-conda \-
Install Conda
.SH SYNOPSIS
.B install-conda
.SH DESCRIPTION
Installs into \fBkoopa app-prefix\fP as 'conda'.
.SH SEE ALSO
.IP
\(bu https://conda.io/miniconda.html
.IP
\(bu https://www.anaconda.com/download
.IP
\(bu https://docs.anaconda.com/anaconda/install/
