.TH INSTALL-RCHECK 1 2019-12-12 Bash
.SH NAME
install-rcheck \-
Install Rcheck scripts for R package locally
.SH SYNOPSIS
.B install-rcheck
.SH DESCRIPTION
Run this script inside a git repo where you want to enable Rcheck CI.
If necessary, Rcheck repo will be cloned from GitHub and installed for current user only into 'XDG_DATA_HOME' at 'Rcheck'.
Symlink will be added at '.Rcheck'.
.SH SEE ALSO
https://github.com/acidgenomics/Rcheck/
