.TH INSTALL-PERLBREW-PERL 1 2019-12-12 Bash
.SH NAME
install-perlbrew-perl
Install latest recommended Perl release via perlbrew
.SH SYNOPSIS
.B install-perlbrew-perl
.SH DESCRIPTION
Installs into 'PERLBREW_ROOT'.
.SH SEE ALSO
.IP
\(bu install-perlbrew
.IP
\(bu https://perlbrew.pl/
.IP
\(bu https://metacpan.org/pod/App::perlbrew
.IP
\(bu https://github.com/gugod/App-perlbrew/wiki/Perlbrew-In-Shell-Scripts

