.SH INSTALL-ENSEMBL-PERL-API 1 2019-12-03 Bash
.SH NAME
install-ensembl-perl-api \-
Install Ensembl Perl API
.SH SYNOPSIS
install-ensembl-perl-api
.SH DESCRIPTION
Installs into \fBkoopa app-prefix\fR at 'ensembl'.
.SH SEE ALSO
.IP
\(bu https://useast.ensembl.org/info/docs/api/api_installation.html
.IP
\(bu https://useast.ensembl.org/info/docs/api/api_git.html
.IP
\(bu https://github.com/Ensembl/ensembl-git-tools/blob/master/README.md
