.TH INSTALL-PERLBREW 1 2019-12-03 Bash
.SH NAME
install-perlbrew \-
Install Perlbrew
.SH SYNOPSIS
.B install-perlbrew
.SH DESCRIPTION
Installs into \fBkoopa app-prefix\fR at 'perlbrew'.
.SH SEE ALSO
.IP
\(bu https://perlbrew.pl/
.IP
\(bu https://metacpan.org/pod/App::perlbrew
.IP
\(bu https://github.com/gugod/App-perlbrew/wiki/Perlbrew-In-Shell-Scripts
