.TH KEBAB-CASE 1 2019-11-09 Bash
.SH NAME
kebab-case \-
Convert input into kebab case
.SH SYNOPSIS
.B kebab-case
[\fB\-\-rename\fP]
[\fB\-\-prefix\fP]
.I string|file ...
.SH OPTIONS
.TP
.B \-\-rename
Rename input files. Assumes we're renaming files in current working directory, but also supports explicit and/or mixed file paths. Doesn't work recursively.
.TP
.B \-\-prefix
Include "x" prefix for names that are syntactically invalid in R. Note that this includes input beginning with a number. Disabled by default.
.SH DESCRIPTION
Runs in string mode by default. File rename mode can be enabled by setting '--rename' flag.
.SH SEE ALSO
.IP
\(bu 'syntactic::kebabCase()' in R.
.IP
\(bu https://syntactic.acidgenomics.com/
.SH EXAMPLE
.nf
.B kebab-case "hello world" "foo bar" "geneID"
## hello-world foo-bar gene-id
.PP
.B kebab-case --rename "foo_bar.fastq.gz"
## ./foo-bar.fastq.gz
.PP
.B kebab-case --rename --prefix 1_control_A.fastq.gz
## ./x1-control-a.fastq.gz
.fi
.SH NOTE
Bash script that calls Rscript internally. Requires the syntactic package to be installed.
