.TH KEBAB-CASE 1 2019-11-09 Bash
.SH NAME
kebab-case \-
Convert input into kebab case
.SH SYNOPSIS
.B kebab-case
[\fB\-\-rename\fR]
[\fB\-\-prefix\fR]
.IR string|file ...
.SH OPTIONS
.TP
.BR \-\-rename
Rename input files. Assumes we're renaming files in current working directory, but also supports explicit and/or mixed file paths. Doesn't work recursively.
.TP
.BR \-\-prefix
Include "x" prefix for names that are syntactically invalid in R. Note that this includes input beginning with a number. Disabled by default.
.SH DESCRIPTION
Runs in string mode by default. File rename mode can be enabled by setting '--rename' flag.
.SH SEE ALSO
.IP
\(bu 'syntactic::kebabCase()' in R.
.IP
\(bu https://syntactic.acidgenomics.com/
.SH EXAMPLE
kebab-case "hello world" "foo bar" "geneID"
    ## hello-world foo-bar gene-id
.PP
kebab-case --rename "foo_bar.fastq.gz"
    ## ./foo-bar.fastq.gz
.PP
kebab-case --rename --prefix 1_control_A.fastq.gz
    ## ./x1-control-a.fastq.gz
.SH NOTE
Bash script that calls Rscript internally. Requires the syntactic package to be installed.
