.TH LINK-EMACS 1 2019-12-12 Bash
.SH NAME
link-emacs \-
Link Emacs installation
.SH SYNOPSIS
.B link-emacs
.I name
.SH OPTIONS
.TP
.B name
Name of Emacs directory.
Currently supports 'doom', 'minimal' (i.e. minmal ESS config), and 'spacemacs'.
Looks for '~/emacs-NAME/' directory internally.
.SH DESCRIPTION
Links at '~/.emacs.d/'.
.SH EXAMPLE
.B link-emacs spacemacs
