.TH MD5SUM-CHECK-TO-NEW-MD5-FILE 1 2019-12-12 Bash
.SH NAME
md5sum-check-to-new-md5-file \-
Run md5sum and generate an MD5 checksum file
.SH SYNOPSIS
.B md5sum-check-to-new-md5-file
.I files ...
.SH OPTIONS
.TP
.B ...
Files to checksum.
.SH DESCRIPTION
Outputs to 'md5sum-<TIMESTAMP>.md5' file containing timestamp in name.
