.TH MOVE-INTO-DATED-DIRS-BY-TIMESTAMP 1 2019-12-12 Bash
.SH NAME
move-into-dated-dirs-by-timestamp \-
Move files into dated subdirectories by timestamp
.SH SYNOPSIS
.B move-into-dated-dirs-by-timestamp
.I files ...
.SH OPTIONS
.TP
.B ...
File paths.
Assuming we're matching inside current working directory.
