.TH NFILETYPES 1 2019-12-12 Bash
.SH NAME
nfiletypes \-
List the number of files of each extension type in current directory
.SH SYNOPSIS
.B nfiletypes
[\fIdir="."\fP]
.SH OPTIONS
.TP
.B ...
Directory path.
.SH DESCRIPTION
Does not search recursively.
.SH SEE ALSO
Stephen Turner tweet
(https://twitter.com/strnr/status/1159503398716227584)
