.TH RUN-SALMON 1 2019-12-11 Bash
.SH NAME
run-salmon \-
Run salmon on multiple FASTQs inside a directory.

--fasta-file="FASTA"
--index-file="INDEX"
[--fastq-dir="${fastq_dir}"]
[--output-dir="${output_dir}"]

required arguments:
    --fasta-file
        Transcriptome-level (i.e. cDNA) FASTA file.
        Ensembl or GENCODE reference is recommended over RefSeq or UCSC.
        Example: Homo_sapiens.GRCh38.cdna.all.fa.gz
        This will generate a new salmon index, which gets saved in the output
        directory specified by '--output-dir'.
    [OR]
    --index-file
        Salmon index, previously generated using 'salmon index'.
        Example: salmon.idx
        If '--fasta-file' is defined, this gets generated on the fly.

required arguments with defaults:
    --fastq-dir
        Directory path containing paired-end FASTQ files.
        Defaults to '${fastq_dir}'.
    --output-dir
        Output directory path.
        Defaults to '${output_dir}'.

.SH DESCRIPTION
    This script supports quick analysis of multiple paired-end FASTQ samples
    inside a directory. It builds a salmon index on the fly, if necessary
    (unless the '--index-file' argument is set), and outputs per sample
    automatically.

The script will intentionally error if the output directory specified by
\fB--output-dir\fP already exists, to prevent accidental overwrite.
.SS Strandedness
Illumina TruSeq stranded library type is first read reverse.
This corresponds to 'ISR' for salmon quant.
Previously, this was \fB--library-type fr-firststrand\fP for TopHat.

                    | Paired-end | Single-end |
    ----------------|------------|------------|
    fr-unstranded   | -l IU      | -l U       |
    fr-firststrand  | -l ISR     | -l SR      |
    fr-secondstrand | -l ISF     | -l SF      |

The \fB--libType A\fP argument will allow Salmon to automatically infer the library type.
Check the run log for the strand information.
.SH SEE ALSO
.IP
\(bu salmon quant --help-reads
.IP
\(bu https://salmon.readthedocs.io/en/latest/library_type.html
.IP
\(bu https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/rnaseq/
.IP
\(bu https://fishycat.netlify.com/en/2017/08/strandness_in_rnaseq/
