.TH SRA-PREFETCH-PARALLEL 1 2021-10-13 Bash
.SH NAME
sra-prefetch-parallel \-
Prefetch NGS data from SRA in parallel using Aspera Connect
.SH SYNOPSIS
.B sra-prefetch-parallel
id
.SH OPTIONS
.TP
.B id
SRP or PRJNA project identifier.
Alternatively, can pass in multiple SRR identifiers and this will glob match.
.SH NOTE
Requires sra-tools to be installed.
Available via bioconda.
Uses GNU parallel internally.
.SH SEE ALSO
    - https://reneshbedre.github.io/blog/fqutil.html
    - https://www.biostars.org/p/111040/
    - https://github.com/LangilleLab/microbiome_helper/wiki/Download_From_SRA
