.TH SRA-FASTQ-DUMP-PARALLEL 1 2021-10-13 Bash
.SH NAME
sra-fastq-dump-parallel \-
FASTQ dump from Sequence Read Archive (SRA) accession list in parallel
.SH SYNOPSIS
.B sra-fastq-dump-parallel
[acc_file=\fI"SRR_Acc_List.txt"\fP]
.SH OPTIONS
.TP
.B acc_file
SRA accession file list.
.SH DESCRIPTION
Requires sratools to be installed, which contains fastq-dump.
.PP
This script loops across an SRA accession file list and calls 'fasterq-dump' internally.
.PP
Note that this will skip FASTQ files that have already been extracted.
This is useful because SRA 'fastq-dump' can take a long time and get interrupted.
.SH SEE ALSO
Use fasterq-dump instead of fastq-dump, since it supports multiple threads.
.PP
Single cell RNA-seq barcode formats:
.IP
\(bu 10X Genomics (https://kb.10xgenomics.com/hc/en-us/articles/115003802691)
.IP
\(bu Harvard inDrops v3 (https://singlecellcore.hms.harvard.edu)
.SH EXAMPLE
.nf
.B sra-fastq-dump-parallel SRR_Acc_List.txt
.fi
