#!/bin/sh

#BSUB -J indrop                        # Job name
#BSUB -q medium                        # Queue name
#BSUB -N                               # Email when the report finishes
#BSUB -n 1                             # CPU cores requested per task (change for threaded jobs)
#BSUB -W 90:00                         # Runtime in HH:MM format
#BSUB -R "rusage[mem=10000]"           # Memory needed per CPU
#BSUB -e project.err                   # File to which STDERR will be written
#BSUB -o project.out                   # File to which STDOUT will be written

bcbio_nextgen.py ../config/indrop_rnaseq.yaml -n 32 -t ipython -s lsf -q medium '-rW=90:00' -r mincores=2 -r minconcores=2 --retries 3 --timeout 1000
