#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

user="$1"

sudo useradd "$user"
sudo passwd "$user"
sudo usermod -a -G wheel "$user"
sudo usermod -a -G biogroup "$user"
groups "$user"
