#!/usr/bin/env bash
set -Eeuo pipefail

# shellcheck source=/dev/null
source "$(koopa header azure)"
_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

bcbio_dir="/data00/bcbio"
version="development"
pkgs_dir="${bcbio_dir}/${version}/install/anaconda/pkgs"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)
    [pkgs_dir="${pkgs_dir}"]

Clean up extracted bcbio anaconda packages.

required positional arguments with defaults:
    1.  Anaconda packages directory.
        Defaults to '${pkgs_dir}'.

$(_koopa_help_args)

note:
    Bash script.
    Updated 2019-09-25.
EOF
}

_koopa_help "$@"



# Arguments                                                                 {{{1
# ==============================================================================

pkgs_dir="${1:-$pkgs_dir}"



# Script                                                                    {{{1
# ==============================================================================

_koopa_assert_is_dir "$pkgs_dir"

printf "Removing extracted Anaconda packages.\n"
printf "Note: Package tarballs will not be removed.\n"

find "$pkgs_dir" \
    -maxdepth 1 \
    -mindepth 1 \
    -type d \
    -exec rm -frv "{}" \;
