#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

version="${1:-"development"}"
bcbio_dir="/usr/local/bcbio"
tmp_dir="${TMPDIR:-"/tmp"}"

bin_dir="${bcbio_dir}/${version}/tools/bin"
git_dir="${bcbio_dir}/git"
tests_dir="${git_dir}/tests"

_koopa_assert_is_dir "$bin_dir"
_koopa_assert_is_dir "$tests_dir"
_koopa_assert_is_dir "$tmp_dir"



# Script                                                                    {{{1
# ==============================================================================

# Ensure tmp SSD drive is configured correctly.
sudo chown "$USER" "$tmp_dir"
sudo chmod u+rwx "$tmp_dir"

(
    export PATH="${bin_dir}:${PATH}"
    cd "$tests_dir" || exit 1
    rm -frv test_automated_output
    ./run_tests.sh hisat2
    rm -frv test_automated_output
    ./run_tests.sh star
    rm -frv test_automated_output
    # Currently failing for v1.1.6a.
    ./run_tests.sh fastrnaseq
    rm -frv test_automated_output
    ./run_tests.sh stranded
    rm -frv test_automated_output
    # Currently failing for v1.1.6a.
    ./run_tests.sh rnaseq
    rm -frv test_automated_output
    ./run_tests.sh chipseq
    rm -frv test_automated_output
    ./run_tests.sh scrnaseq
    rm -frv test_automated_output
)
