#!/usr/bin/env bash
set -Eeuo pipefail

# shellcheck source=/dev/null
source "$(koopa header azure)"



# Variables                                                                 {{{1
# ==============================================================================

bcbio_dir="/data00/bcbio"
version="${1:-development}"

bin_dir="${bcbio_dir}/${version}/tools/bin"
git_dir="${bcbio_dir}/git"
tests_dir="${git_dir}/tests"

tmp_dir="/mnt/resource"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Run bcbio-nextgen unit tests.

$(_koopa_help_args)

details:
    Refer to tests/data/automated for YAML recipes.

note:
    Bash script.
    Updated 2019-08-14.
EOF
}



# Script                                                                    {{{1
# ==============================================================================

_koopa_assert_is_dir "$bin_dir"
_koopa_assert_is_dir "$tests_dir"
_koopa_assert_is_dir "$tmp_dir"

# Ensure tmp SSD drive is configured correctly.
sudo chown "$USER" "$tmp_dir"
sudo chmod u+rwx "$tmp_dir"

(
    export PATH="${bin_dir}:${PATH}"
    cd "$tests_dir" || exit 1
    rm -frv test_automated_output
    ./run_tests.sh hisat2
    rm -frv test_automated_output
    ./run_tests.sh star
    rm -frv test_automated_output
    # Currently failing for v1.1.6a.
    ./run_tests.sh fastrnaseq
    rm -frv test_automated_output
    ./run_tests.sh stranded
    rm -frv test_automated_output
    # Currently failing for v1.1.6a.
    ./run_tests.sh rnaseq
    rm -frv test_automated_output
    ./run_tests.sh chipseq
    rm -frv test_automated_output
    ./run_tests.sh scrnaseq
    rm -frv test_automated_output
)
