#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_sudo

bcbio_dir="/usr/local/bcbio"

_koopa_message "Updating symlinks."

# Remove existing symlinks in '/usr/local/bin'.
sudo rm -fv /usr/local/bin/bcbio_nextgen.py*

(
    version="1.1.5"
    sudo ln -fnsv \
        "${bcbio_dir}/v${version}/install/anaconda/bin/bcbio_nextgen.py" \
        "/usr/local/bin/bcbio_nextgen.py-${version}"
    sudo ln -fnsv \
        "/usr/local/bin/bcbio_nextgen.py-${version}" \
        "/usr/local/bin/bcbio_nextgen.py"
)

(
    version="development"
    sudo ln -fnsv \
        "${bcbio_dir}/${version}/install/anaconda/bin/bcbio_nextgen.py" \
        "/usr/local/bin/bcbio_nextgen.py-${version}"
)
