#!/usr/bin/env bash
set -Eeuo pipefail

# shellcheck source=/dev/null
source "$(_koopa_header azure)"

# Find broken bcbio symlinks.
# Modified 2019-08-14.

_koopa_assert_has_sudo

bcbio_dir="/data00/bcbio"

find "$bcbio_dir" -xtype l
