#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

bcbio_dir="/data00/bcbio"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Update bcbio symlinks.

$(_koopa_help_args)

note:
    Bash script.
    Updated 2019-08-14.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

_koopa_message "Updating symlinks."

# Remove existing symlinks in `/usr/local/bin`.
sudo rm -fv /usr/local/bin/bcbio_nextgen.py*

(
    version="1.1.5"
    sudo ln -fnsv \
        "${bcbio_dir}/v${version}/install/anaconda/bin/bcbio_nextgen.py" \
        "/usr/local/bin/bcbio_nextgen.py-${version}"
    sudo ln -fnsv \
        "/usr/local/bin/bcbio_nextgen.py-${version}" \
        "/usr/local/bin/bcbio_nextgen.py"
)

(
    version="development"
    sudo ln -fnsv \
        "${bcbio_dir}/${version}/install/anaconda/bin/bcbio_nextgen.py" \
        "/usr/local/bin/bcbio_nextgen.py-${version}"
)
