#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_sudo



# Arguments                                                                 {{{1
# ==============================================================================

dir="${1:-"/data00/bcbio"}"



# Script                                                                    {{{1
# ==============================================================================

find-broken-symlinks "$dir"
