#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_koopa_assert_has_no_envs

export KOOPA_FORCE=1

sudo mkdir -pv /data00/n/app
sudo ln -fnsv /data00/n /n

sudo chmod 2775 /usr/local
sudo chown -Rh root:wheel /usr/local

install-rhel7-base
remove-rhel7-cruft

install-openjdk

install-cellar-coreutils
install-cellar-bash
install-cellar-zsh
install-cellar-r
install-cellar-python
install-cellar-vim
install-cellar-neovim
install-cellar-emacs
install-cellar-tmux
install-cellar-git
install-rstudio-server
install-cellar-htop
install-cellar-shellcheck
install-cellar-neofetch
install-cellar-gnupg
install-cellar-proj
install-cellar-gdal
install-cellar-hdf5

install-perlbrew
install-rbenv
install-rust

(
    _koopa_deactivate_envs
    install-perlbrew-perl
    install-rbenv-ruby
)

# Python venv
rm -frv ~/.virtualenvs
venv-create-base

# bcbio (VM33-36 only)
# > sudo mkdir -pv /data00/bcbio
# > sudo chmod 2775 /data00/bcbio
# > sudo chown -Rh mike:wheel /data00/bcbio

update-vm --all
koopa update
koopa check
