#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_is_rhel_7
_koopa_assert_has_no_envs

_koopa_enable_passwordless_sudo
_koopa_prepare_make_prefix

# Remove default user shell configuration files.
sudo rm -fv /etc/skel/.{bash_logout,bash_profile,bashrc,emacs,zshrc}
rm -fv ~/.{bash_logout,bash_profile,bashrc,emacs,zshrc}

# Prepare '/n/' share.
sudo mkdir -pv /data00/n/app
sudo ln -fnsv /data00/n /n

install-rhel-7-base
install-openjdk
install-cellar-coreutils
install-cellar-bash
install-cellar-zsh
install-cellar-fish
install-cellar-tmux
install-cellar-git
install-cellar-gnupg
install-cellar-lua
install-cellar-luarocks
install-cellar-r
install-cellar-python
install-cellar-vim
install-cellar-neovim
install-cellar-emacs
install-cellar-proj  # slow
install-cellar-gdal
install-cellar-hdf5
install-cellar-gsl
install-cellar-perl
install-cellar-ruby
install-cellar-julia
install-cellar-htop
install-cellar-shellcheck
install-cellar-neofetch
install-cellar-genrich
install-rust
install-perlbrew
install-rbenv
install-pyenv

# Check for which machine to install RStudio Server Pro.
if _koopa_is_matching_fixed "${HOSTNAME:?}" azlabapp32
then
    install-rstudio-server-pro
else
    install-rstudio-server
fi

install-shiny-server
r-javareconf

(
    _koopa_deactivate_envs
    install-perlbrew-perl
    install-rbenv-ruby
)

# Python venv
rm -frv ~/.virtualenvs
venv-create-base
