#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_koopa_assert_has_no_envs

export KOOPA_FORCE=1

_koopa_prepare_make_prefix

sudo mkdir -pv /data00/n/app
sudo ln -fnsv /data00/n /n

install-rhel-7-base
install-openjdk

install-cellar-coreutils
install-cellar-bash
install-cellar-zsh
install-cellar-fish
install-cellar-tmux
install-cellar-git
install-cellar-gnupg
install-cellar-lua
install-cellar-luarocks
# Skip this step on Debian/Ubuntu.
install-cellar-r
install-cellar-python
install-cellar-vim
install-cellar-neovim
install-cellar-emacs
install-cellar-htop
install-cellar-shellcheck
install-cellar-neofetch
install-cellar-proj
install-cellar-gdal
install-cellar-hdf5
install-cellar-genrich
install-cellar-perl
install-cellar-ruby

install-perlbrew
install-rbenv
install-rust

install-rstudio-server

r-javareconf

(
    _koopa_deactivate_envs
    install-perlbrew-perl
    install-rbenv-ruby
)

# Python venv
rm -frv ~/.virtualenvs
venv-create-base
