#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

export KOOPA_FORCE=1

_koopa_assert_has_sudo
_koopa_deactivate_envs

sudo chown -R root:wheel /usr/local
sudo chmod 2775 /usr/local

install-rhel7-base
remove-rhel7-rpm-cruft
install-openjdk

install-cellar-coreutils
install-cellar-bash
install-cellar-zsh
install-cellar-r
install-cellar-python
install-cellar-vim
install-cellar-neovim
install-cellar-emacs
install-cellar-tmux
install-cellar-git
install-rstudio-server
install-cellar-htop
install-cellar-shellcheck
install-cellar-neofetch
install-cellar-gnupg
install-cellar-proj
install-cellar-gdal
install-cellar-hdf5

install-perlbrew
install-rbenv
install-rust

(
    _koopa_deactivate_envs
    install-perlbrew-perl
    install-rbenv-ruby
)

# venv
rm -frv ~/.virtualenvs
venv-create-base

# miniconda3
sudo mkdir -pv /data00/miniconda3
sudo chown -Rh mike:wheel /data00/miniconda3
sudo chmod 2775 /data00/miniconda3
rm -frv /usr/local/miniconda3
sudo ln -fnsv /data00/miniconda3 /usr/local/miniconda3
# > rsync-miniconda3

# R site library
sudo mkdir -pv /data00/R
sudo chown -Rh mike:wheel /data00/R
sudo chmod 2775 /data00/R
# > rsync-r-site-library

update-vm

koopa update
koopa check
