#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(koopa header azure)"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Install base programs recommended for Azure VM.

$(_koopa_help_args)

note:
    Bash script.
    Updated 2019-06-23.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

install-fedora-base
install-azure-cli
