#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

cpi=0

while (("$#"))
do
    case "$1" in
        --cpi)
            cpi=1
            shift 1
            ;;
        --source)
            source=1
            shift 1
            ;;
        *)
            _koopa_invalid_arg "$1"
            ;;
    esac
done

_koopa_assert_is_rhel_7
_koopa_assert_has_no_envs

_koopa_enable_passwordless_sudo
_koopa_prepare_make_prefix

# Remove default user shell configuration files.
# FIXME Check to see if these are symlinks.
sudo rm -fv /etc/skel/.{bash_logout,bash_profile,bashrc,emacs,zshrc}
rm -fv ~/.{bash_logout,bash_profile,bashrc,emacs,zshrc}

# Don't attempt to patch system env to support '-S' flag.
# Should no longer be an issue on VMs, as of 2020.
if [[ -e "/bin/env.bak" ]]
then
    sudo rm "/bin/env"
    sudo mv "/bin/env.bak" "/bin/env"
fi

# OpenJDK moved to '/n/app'.
sudo rm -frv /opt/jdk

# Prepare '/n/' share.
sudo mkdir -pv /data00/n/app
sudo ln -fnsv /data00/n /n

install-rhel-7-base
install-azure-cli
install-openjdk

if _koopa_is_matching_fixed "$HOSTNAME" azlabapp32
then
    install-cellar-coreutils
    install-cellar-bash
    install-cellar-zsh
    install-cellar-fish
    install-cellar-tmux
    install-cellar-git
    install-cellar-gnupg
    install-cellar-lua
    install-cellar-luarocks
    install-cellar-r
    install-cellar-python
    install-cellar-vim
    install-cellar-neovim
    install-cellar-emacs
    install-cellar-sqlite
    install-cellar-proj
    install-cellar-gdal
    install-cellar-hdf5
    install-cellar-go
    install-cellar-gsl
    install-cellar-perl
    install-cellar-ruby
    install-cellar-julia
    install-cellar-htop
    install-cellar-shellcheck
    install-cellar-neofetch
    install-cellar-genrich
    install-cellar-autojump
    install-cellar-fzf
    install-cellar-the-silver-searcher
    install-rust
    install-perlbrew
    install-rbenv
    install-pyenv
    install-rstudio-server-pro
    r-javareconf
else
    install-rstudio-server
fi

install-shiny-server

if [[ "$cpi" -eq 1 ]]
then
    _koopa_message "Updating '/etc/profile.d'."
    _koopa_update_profile
    sudo ln -fnsv \
        "${KOOPA_PREFIX}/host/azure/etc/profile.d/constellation.sh" \
        "/etc/profile.d/."

    _koopa_message "Updating '/etc/cron.d'."
    sudo rm -fv "/etc/cron.d/cpi-"*
    sudo rm -fv "/etc/cron.d/constellation"
    sudo cp -v \
        "${KOOPA_PREFIX}/host/azure/etc/cron.d/constellation" \
        "/etc/cron.d/constellation"

    # Ensure that shared bioinfo user has correct dotfiles.
    if [[ -d "${KOOPA_PREFIX}/dotfiles" ]]
    then
        _koopa_message "Updating bioinfo user dotfiles."
        sudo -u bioinfo -H "$SHELL" -c "\
            rm -fv ~/.bash_logout; \
            rm -fv ~/.bash_profile; \
            rm -fv ~/.bashrc; \
            rm -fv ~/.condarc; \
            /usr/local/koopa/bin/link-dotfile --force \
                app/emacs/minimal/emacs.el emacs \
        "
    fi

    _koopa_message "Updating '/data00' structure."
    sudo rm -frv "/data00/"{R,bcbio,cellranger,cellranger-atac,conda,docker,var}

    rsync-vm --data-disk="/data00" --source-ip="10.100.100.132"

    _koopa_update_lmod_config
fi
