#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(koopa header azure)"

# Install base programs recommended for Azure VM.
# Updated 2019-06-23.

install-fedora-base
install-azure-cli
