#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_acid_assert_has_sudo

flags=(
    # "--exclude=bam"
    # "--exclude=cram"
    # "--exclude=fastq"
    # "--exclude=sam"
    "--exclude=.Rproj.user"
    "--exclude=.git"
    "--exclude=.gitignore"
    "--exclude=work"
    "--human-readable"
    "--no-links"
    "--progress"
    "--recursive"
    "--size-only"
    "--stats"
    "--verbose"
)

rsync "${flags[@]}" --rsync-path="sudo rsync" "$@"
