#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

source_user="$USER"

host_ip="$(ip-address)"
source_ip="10.100.100.132"

conda_dir="/usr/local/miniconda3"
_koopa_assert_is_dir "$conda_dir"

mapfile -t flags < <(_koopa_rsync_flags)
flags+=("--omit-dir-times")



# Script                                                                    {{{1
# ==============================================================================

# Check for accidental sync from source machine.
if [[ "$source_ip" == "$host_ip" ]]
then
    _koopa_stop "On source machine: '${source_ip}'."
fi

_koopa_message "Updating '${conda_dir}' from '${source_ip}'."
_koopa_note "Using flags: ${flags[*]}"

# shellcheck disable=SC2068
rsync ${flags[@]} \
    --rsync-path="sudo /usr/bin/rsync" \
    "${source_user}@${source_ip}:${conda_dir}/" \
    "${conda_dir}/"
