#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_acid_assert_has_sudo

source_user="$USER"

host_ip="$(ip-address)"
source_ip="10.100.100.135"

bcbio_dir="/usr/local/bcbio"

if [[ ! -d "$bcbio_dir" ]]
then
    _acid_note "bcbio is not installed at '${bcbio_dir}'. Skipping."
    exit 0
fi

mapfile -t flags < <(_acid_rsync_flags)
flags+=("--omit-dir-times")

# Check for accidental sync from source machine.
if [[ "$source_ip" == "$host_ip" ]]
then
    _acid_note "On source machine: '${source_ip}'. Skipping."
    exit 0
fi

_acid_message "Updating '${bcbio_dir}' from '${source_ip}'."
_acid_note "Using flags: ${flags[*]}"

# shellcheck disable=SC2068
rsync ${flags[@]} \
    --rsync-path="sudo /usr/bin/rsync" \
    "${source_user}@${source_ip}:${bcbio_dir}/" \
    "${bcbio_dir}/"
