#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

source_user="$USER"

host_ip="$(ip-address)"
source_ip="10.100.100.133"

cellranger_dir="/usr/local/cellranger"
cellranger_atac_dir="/usr/local/cellranger-atac"

if [[ ! -d "$cellranger_dir" ]] && [[ ! -d "$cellranger_atac_dir" ]]
then
    _koopa_note "Cell Ranger is not installed at '${cellranger_dir}'. Skipping."
    exit 0
fi

mapfile -t flags < <(_koopa_rsync_flags)
flags+=("--omit-dir-times")

# Check for accidental sync from source machine.
if [[ "$source_ip" == "$host_ip" ]]
then
    _koopa_note "On source machine: '${source_ip}'. Skipping."
    exit 0
fi

_koopa_message "Updating '${cellranger_dir}' from '${source_ip}'."
# shellcheck disable=SC2068
rsync ${flags[@]} \
    --rsync-path="sudo /usr/bin/rsync" \
    "${source_user}@${source_ip}:${cellranger_dir}/" \
    "${cellranger_dir}/"

_koopa_message "Updating '${cellranger_atac_dir}' from '${source_ip}'."
# shellcheck disable=SC2068
rsync ${flags[@]} \
    --rsync-path="sudo /usr/bin/rsync" \
    "${source_user}@${source_ip}:${cellranger_atac_dir}/" \
    "${cellranger_atac_dir}/"
