#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

host_ip="$(ip-address)"
source_user="mike"
source_ip="10.100.100.135"
bcbio_dir="/data00/bcbio"
flags="$(_koopa_rsync_flags)"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

rsync bcbio installation.

$(_koopa_help_args)

details:
    Requires sync from VM35 using Mike's account.

internal variables:
    source_ip: ${source_ip}
    source_user: ${source_user}
    bcbio_dir: ${bcbio_dir}

note:
    Bash script.
    Updated 2019-10-23.
EOF
}

_koopa_help "$@"



# Arguments                                                                 {{{1
# ==============================================================================

bcbio_dir="$(_koopa_strip_trailing_slash "$bcbio_dir")"



# Script                                                                    {{{1
# ==============================================================================

# Check for accidental sync from source machine.
if [[ "$source_ip" == "$host_ip" ]]
then
    _koopa_stop "On source machine: '${source_ip}'."
fi

dir="$bcbio_dir"
_koopa_message "Updating '${dir}' from '${source_ip}'."
# shellcheck disable=SC2086
rsync $flags                                                                   \
    --rsync-path="sudo rsync"                                                  \
    "${source_user}@${source_ip}:${dir}/"                                      \
    "${dir}/"
