#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

host_ip="$(ip-address)"
source_user="mike"
source_ip="10.100.100.133"
cellranger_dir="/data00/cellranger"
cellranger_atac_dir="/data00/cellranger-atac"
flags="$(_koopa_rsync_flags)"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

rsync Cell Ranger installation.

$(_koopa_help_args)

details:
    Requires sync from VM33 using Mike's account.

internal variables:
    source_ip: ${source_ip}
    source_user: ${source_user}
    cellranger_dir: ${cellranger_dir}
    cellranger_atac_dir: ${cellranger_atac_dir}

note:
    Bash script.
    Updated 2019-10-23.
EOF
}

_koopa_help "$@"



# Arguments                                                                 {{{1
# ==============================================================================

cellranger_dir="$(_koopa_strip_trailing_slash "$cellranger_dir")"
cellranger_atac_dir="$(_koopa_strip_trailing_slash "$cellranger_atac_dir")"



# Script                                                                    {{{1
# ==============================================================================

# Check for accidental sync from source machine.
if [[ "$source_ip" == "$host_ip" ]]
then
    _koopa_stop "On source machine: '${source_ip}'."
fi

dir="$cellranger_dir"
_koopa_message "Updating '${dir}' from '${source_ip}'."
# shellcheck disable=SC2086
rsync $flags \
    --rsync-path="sudo rsync" \
    "${source_user}@${source_ip}:${dir}/" \
    "${dir}/"

dir="$cellranger_atac_dir"
_koopa_message "Updating '${dir}' from '${source_ip}'."
# shellcheck disable=SC2086
rsync $flags                                                                   \
    --rsync-path="sudo rsync"                                                  \
    "${source_user}@${source_ip}:${dir}/"                                      \
    "${dir}/"
