#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_assert_has_sudo



# Variables                                                                 {{{1
# ==============================================================================

host_ip="$(ip-address)"
source_user="mike"
source_ip="10.100.100.133"
cellranger_dir="/usr/local/cellranger"
cellranger_atac_dir="/usr/local/cellranger-atac"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

rsync Cell Ranger installation.

$(_koopa_help_args)

details:
    Requires sync from VM33 using Mike's account.

internal variables:
    source_ip: ${source_ip}
    source_user: ${source_user}
    cellranger_dir: ${cellranger_dir}
    cellranger_atac_dir: ${cellranger_atac_dir}

note:
    Bash script.
    Updated 2019-10-15.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

# Check for accidental sync from source machine.
if [[ "$source_ip" == "$host_ip" ]]
then
    >&2 printf "Error: On source machine: %s.\n" "$source_ip"
    exit 1
fi

flags="$(_koopa_rsync_flags)"

dir="$cellranger_dir"
printf "Updating '%s' from '%s'.\n" "$(basename "$dir")" "$source_ip"
# shellcheck disable=SC2086
rsync $flags \
    --rsync-path="sudo rsync" \
    "${source_user}@${source_ip}:${dir}/" \
    "${dir}/"

dir="$cellranger_atac_dir"
printf "Updating '%s' from '%s'.\n" "$(basename "$dir")" "$source_ip"
# shellcheck disable=SC2086
rsync $flags \
    --rsync-path="sudo rsync" \
    "${source_user}@${source_ip}:${dir}/" \
    "${dir}/"
