#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(koopa header azure)"

# Sync R library across virtual machines.
# Updated 2019-06-25.

_koopa_assert_has_sudo

printf "Syncing R library from VM45.\n"

source="mike@10.100.100.145"
r_dir="/data00/R"

# Create R directory, if necessary.
if [[ ! -d "$r_dir" ]]
then
    sudo mkdir -p "$r_dir"
    sudo chown "mike:biogroup" "$r_dir"
fi

# Symlink R directory, if necessary.
if [[ ! -L "${HOME}/R" ]]
then
    rm -rf "${HOME}/R"
    ln -s "$r_dir" "${HOME}/R"
fi

rsync -av --delete "${source}:${HOME}/R/" "${HOME}/R/"
