#!/usr/bin/env bash
set -Eeu -o pipefail

# shellcheck source=/dev/null
source "$(koopa header azure)"



# Variables                                                                 {{{1
# ==============================================================================

source_dir="/var/lib/docker"
dest_dir="/data00/docker"



# Usage                                                                     {{{1
# ==============================================================================

usage() {
cat << EOF
$(_koopa_help_header)

Symlink docker installation.

$(_koopa_help_args)

internal variables:
    source_dir: ${source_dir}
    dest_dir: ${dest_dir}

note:
    Bash script.
    Updated 2019-08-14.
EOF
}

_koopa_help "$@"



# Script                                                                    {{{1
# ==============================================================================

sudo service docker stop

_koopa_assert_is_dir "$source_dir"
_koopa_assert_is_not_dir "$dest_dir"

sudo mv -v "${source_dir}/" "${dest_dir}/"
sudo ln -fnsv "$dest_dir" "$source_dir"

sudo service docker start
docker images
