#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"
_koopa_assert_has_sudo

rsync=0

while (("$#"))
do
    case "$1" in
        --rsync)
            rsync=1
            shift 1
            ;;
        *)
            _koopa_invalid_arg "$1"
            ;;
    esac
done

_koopa_update_profile

sudo rm -fv /etc/cron.d/cpi-*
sudo ln -fnsv \
    /usr/local/koopa/host/azure/etc/cron.d/constellation \
    /etc/cron.d/.

sudo yum update -y
install-rhel7-base
remove-rhel7-rpm-cruft

if [[ "$rsync" -eq 1 ]]
then
    rsync-bcbio
    rsync-miniconda3
    rsync-r-site-library
fi

# Ensure that conda has a system configuration file.
if [[ ! -f "/usr/local/miniconda3/.condarc" ]]
then
    _koopa_warning "Shared conda system configuration file missing."
fi

# Ensure that reboot script has correct permissions.
# This will get fixed automatically in the 'koopa update' call below.
# > sudo crontab -e
# > sudo chown root:wheel "${KOOPA_HOME}/host/azure/config/etc/reboot.sh"

# Ensure that shared bioinfo user has correct dotfiles.
sudo -u bioinfo -H "$SHELL" -c "\
    rm -fr ~/.condarc; \
    /usr/local/koopa/bin/link-dotfile --force app/emacs/minimal/emacs.el emacs \
"

remove-broken-symlinks "$HOME"
remove-broken-symlinks "/data00/bcbio"
remove-broken-symlinks "/data00/cellranger"
remove-broken-cellar-symlinks

sudo rm -frv /usr/local/bin/cellranger-2.1.0
sudo rm -frv /usr/local/bin/miniconda3

koopa update
koopa check
