#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

_koopa_help "$@"
_koopa_assert_has_sudo

sudo yum update -y
install-rhel7-base
remove-rhel7-rpm-cruft

rsync-bcbio
rsync-miniconda3
rsync-r-site-library

# Ensure that conda has a system configuration file.
if [[ ! -f "/usr/local/miniconda3/.condarc" ]]
then
    _koopa_warning "Shared conda system configuration file missing."
fi

# Ensure that reboot script has correct permissions.
# > sudo crontab -e
sudo chown root:wheel "${KOOPA_HOME}/host/azure/config/etc/reboot.sh"

# Ensure that shared bioinfo user has correct dotfiles.
sudo -u bioinfo -H "$SHELL" -c "\
    rm -fr ~/.condarc; \
    /usr/local/koopa/bin/link-dotfile app/emacs/minimal/emacs.el emacs \
"

remove-broken-symlinks "$HOME"
remove-broken-symlinks "/data00/bcbio"
remove-broken-symlinks "/data00/cellranger"
remove-broken-cellar-symlinks

koopa check
