#!/usr/bin/env bash
set -Eeu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=/dev/null
source "${script_dir}/../include/header.sh"

KOOPA_PREFIX="$(_koopa_prefix)"

cpi=0
yum=0

while (("$#"))
do
    case "$1" in
        --cpi)
            cpi=1
            shift 1
            ;;
        --yum)
            yum=1
            shift 1
            ;;
        *)
            _koopa_invalid_arg "$1"
            ;;
    esac
done

# Don't attempt to patch system env to support '-S' flag.
# Should no longer be an issue on VMs, as of 2020.
if [[ -e "/bin/env.bak" ]]
then
    sudo rm "/bin/env"
    sudo mv "/bin/env.bak" "/bin/env"
fi

# OpenJDK moved to '/n/app'.
sudo rm -frv /opt/jdk

_koopa_link_docker

if [[ "$yum" -eq 1 ]]
then
    _koopa_message "Updating system packages."
    install-rhel-7-base
fi

if [[ "$cpi" -eq 1 ]]
then
    _koopa_message "Updating '/etc/profile.d'."
    _koopa_update_profile
    sudo ln -fnsv \
        "${KOOPA_PREFIX}/host/azure/etc/profile.d/constellation.sh" \
        "/etc/profile.d/."

    _koopa_message "Updating '/etc/cron.d'."
    sudo rm -fv "/etc/cron.d/cpi-"*
    sudo rm -fv "/etc/cron.d/constellation"
    sudo cp -v \
        "${KOOPA_PREFIX}/host/azure/etc/cron.d/constellation" \
        "/etc/cron.d/constellation"

    # Ensure that shared bioinfo user has correct dotfiles.
    if [[ -d "${KOOPA_PREFIX}/dotfiles" ]]
    then
        _koopa_message "Updating bioinfo user dotfiles."
        sudo -u bioinfo -H "$SHELL" -c "\
            rm -fv ~/.bash_logout; \
            rm -fv ~/.bash_profile; \
            rm -fv ~/.bashrc; \
            rm -fv ~/.condarc; \
            /usr/local/koopa/bin/link-dotfile --force \
                app/emacs/minimal/emacs.el emacs \
        "
    fi

    _koopa_message "Updating '/data00' structure."
    sudo rm -frv "/data00/"{R,bcbio,cellranger,cellranger-atac,conda,docker,var}

    rsync-vm --data-disk="/data00" --source-ip="10.100.100.132"

    _koopa_update_lmod_config
    install-openjdk
fi

_koopa_success "Azure VM updated successfully."
